<!DOCTYPE html>
<html lang="en" dir="ltr">
 
<head>
    <!-- META DATA -->
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=0"
    />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="description"
      content="AST Global Dashboard"
    />
    <meta name="author" content="AST Global" />
    <meta name="keywords" content="" />

    <!-- FAVICON -->
    <link rel="apple-touch-icon" sizes="180x180" href="//localhost:1022/2024/assets/images/brand//apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="//localhost:1022/2024/assets/images/brand//favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="//localhost:1022/2024/assets/images/brand//favicon-16x16.png">
    <link rel="manifest" href="//localhost:1022/2024/assets/images/brand//site.webmanifest">
    <link rel="mask-icon" href="//localhost:1022/2024/assets/images/brand//safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- TITLE -->
    <title>AST Global Dashboard</title>

    <!-- BOOTSTRAP CSS -->
    <link
      id="style"
      href="//localhost:1022/2024/assets/plugins/bootstrap/css/bootstrap.min.css"
      rel="stylesheet"
    />

    <!-- STYLE CSS -->
    <link href="//localhost:1022/2024/assets/css/style.css" rel="stylesheet" />
    <link href="//localhost:1022/2024/assets/css/plugins.css" rel="stylesheet" />

    <!--- FONT ICONS CSS -->
    <link href="//localhost:1022/2024/assets/css/icons.css" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <!-- CUSTOM CSS -->
    <link href="//localhost:1022/2024/assets/css/custom.css" rel="stylesheet" />
  </head>

  <body class="login-img">
    <!-- BACKGROUND-IMAGE -->
    <div>
      <!-- GLOABAL LOADER -->
      <div id="global-loader">
        <div class="dimmer active">
          <div class="spinner"></div>
        </div>
      </div>
      <!-- /GLOABAL LOADER -->
      <div class="fullsize-video-bg">
        <!-- PAGE -->
        <div class="page login-page">
          <div>
            <!-- CONTAINER OPEN -->
            <div class="col col-login mx-auto mt-7">
              <div class="text-center">
                <img
                  src="//localhost:1022/2024/assets/images/brand/logo-3.png"
                  class="header-brand-img"
                  alt=""
                />
              </div>
            </div>
            <div class="container-login100">
              <div class="wrap-login100 p-0">
                <div class="card-body">
                  <form class="login100-form validate-form" name="form" method="post" id="login" name="login">
                    <span class="login100-form-title text-white"> Login </span>
                    <div
                      class="wrap-input100 validate-input"
                      data-bs-validate="Valid email is required: ex@abc.xyz"
                    >
						<?=$this->form->uname->show()?>
                      <span class="focus-input100"></span>
                      <span class="symbol-input100">
                        <i class="zmdi zmdi-email" aria-hidden="true"></i>
                      </span>
                    </div>
                    <div
                      class="wrap-input100 validate-input"
                      data-bs-validate="Password is required"
                    >
						<?=$this->form->password->show()?>
                      <span class="focus-input100"></span>
                      <span class="symbol-input100">
                        <i class="zmdi zmdi-lock" aria-hidden="true"></i>
                      </span>
                    </div>
                    <div class="text-end pt-1">
                      <p class="mb-0">
                        <a href="forgot-password.html" class="text-white ms-1"
                          >Forgot Password?</a
                        >
                      </p>
                    </div>
                    <div class="container-login100-form-btn">
                    <button type="submit"
							class="login100-form-btn btn-primary">Login</button>
                    </div>
                    
                  </form>
                </div>
                <div class="card-footer">
                  <div class="d-flex justify-content-center my-3">
                    <a
                      href="javascript:void(0);"
                      class="social-login text-center me-4"
                    >
                      <i class="fa-brands fa-google"></i>
                    </a>
                    <a
                      href="javascript:void(0);"
                      class="social-login text-center me-4"
                    >
                      <i class="fa-brands fa-facebook-f"></i>
                    </a>
                    <a
                      href="javascript:void(0);"
                      class="social-login text-center"
                    >
                      <i class="fa-brands fa-twitter"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <!-- CONTAINER CLOSED -->
          </div>
        </div>
        <div id="video-viewport">
          <video width="1920" height="1280" autoplay muted loop>
            <source
              src="//localhost:1022/2024/assets/video/video.mp4"
              type="video/mp4"
            />
            <source
              src="//localhost:1022/2024/assets/video/video.mp4"
              type="video/webm"
            />
          </video>
        </div>
      </div>

      <!-- END PAGE -->
    </div>
    <!-- BACKGROUND-IMAGE CLOSED -->

    <!-- JQUERY JS -->
    <script src="//localhost:1022/2024/assets/js/jquery.min.js"></script>

    <!-- BOOTSTRAP JS -->
    <script src="//localhost:1022/2024/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="//localhost:1022/2024/assets/plugins/bootstrap/js/bootstrap.min.js"></script>

    <!-- PERFECT SCROLLBAR JS -->
    <script src="//localhost:1022/2024/assets/plugins/p-scroll/perfect-scrollbar.js"></script>

    <!-- COLOR THEME JS -->
    <script src="//localhost:1022/2024/assets/js/themeColors.js"></script>

    <!-- SWITCHER STYLES JS -->
    <script src="//localhost:1022/2024/assets/js/swither-styles.js"></script>

    <!-- CUSTOM JS -->
    <script src="//localhost:1022/2024/assets/js/custom.js"></script>
  </body>
</html>


<style>
#uname, #password {
    font-size: 15px;
    line-height: 1.5;
    /* color: #000; */
    color: #fff;
    display: block;
    width: 100%;
    /* background: #fff; */
    background: transparent;
    height: 45px;
    padding: 0 30px 0 54px;
    /* border-radius: 5px; */
    border-bottom: 1px solid #ecf0fa;
}

input {
    outline: none;
    border: none;
}
button, input {
    overflow: visible;
}
input, button, select, optgroup, textarea {
    margin: 0;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}
button, input, optgroup, select, textarea {
    margin: 0;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}
* {
    scrollbar-width: thin;
    scrollbar-color: #4D15D1 #DFE9EB;
}
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
* {
    box-sizing: border-box;
}
*, ::after, ::before {
    box-sizing: border-box;
}
user agent stylesheet
input[type="text" i] {
    padding: 1px 2px;
}

</style>
