</head>
<body>
	<div
		class="col-sm-8 col-sm-push-1 col-md-4 col-md-push-4 col-lg-4 col-lg-push-4">
		<div class="center m-a-2">
			<div class="icon-block img-circle">
				<i class=" glyphicon glyphicon-lock muted-icon"></i>
			</div>
		</div>
		<div class="center">
			<p>Welcome to</p>
			  <h5 style="margin-top: 10px; line-height: 200%; font-family: verdana;"> CreativeSol MIS V2 </p>   </h5> 
		</div>
		<div class="card bg-transparent" style="margin-top: 5px;">
			<div class="card-header bg-white center"
				style="background: #6e8cd7; color: #fff;">
				<h4 class="card-title">Login</h4>
				<p class="card-subtitle"></p>
			</div>
			<div class="p-a-2">
				<form name="form" method="post" id="login" name="login">
					<div class="form-group">
						<?=$this->form->uname->show()?>
					</div>
					<div class="form-group">
						<?=$this->form->password->show()?>
					</div>
					<div class="form-group ">
						<button type="submit"
							class="btn  btn-primary"
							style="font-size: 120%;">Login</button>
					</div>
					<div class="center">

					</div>
				</form>
			</div>
		</div>
	</div>
</body>
</html>