<div class="dynamic-popup" id="dynamic-popup">
		<div class="modal-content modal-content-demo">



<?if(count( $this->updList)>0):?>
		<div class="modal-header">
			<h4 class="card-title">Updates/Task Notifiaction</h4>
			<button aria-label="Close" class="btn-close" data-bs-dismiss="modal">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		<div class="modal-body">
		<div class="col-md-12 card" style="padding-top: 15px; margin-bottom: 3px;"> 
		<div style="overflow-y: auto">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th width="15%" class="center">Reference</th>
					<th width="10%" class="center">Start Date.</th>
					<th width="10%" class="center">End Date</th>
					<th width="65%" class="center">Note</th>
				</tr>
			</thead>
			<tbody>

				<?php foreach( $this->updList as $update): ?>
				<tr>
					<td align="center"><?=$update['ref_name']?></td>
					<td align="center"><?=$update['upd_dttime']?></td>
					<td align="center"><?=$update['upd_enddttime']?></td>
					<td align="left"><?=$update['upd_note']?></td>
				</tr>
				<?php endforeach?>
			</tbody>
		</table>
		</div>
		</div>
		</div>
		<?endif?>
		<?if(count( $this->stepsList)>0):?>
		
		<div class="modal-header">
			<h4 class="card-title">Pending Ticket Actions</h4>
			<button aria-label="Close" class="btn-close" data-bs-dismiss="modal">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		<div class="modal-body">
		<div class="col-md-12 card" style="padding-top: 15px; margin-bottom: 3px;"> 
		<div style="overflow-y: auto">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th width="10%" class="center">Start Date.</th>
					<th width="40%" class="center">Ticket Details</th>
					<th width="40%" class="center">Steps to be carried out</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach( $this->stepsList as $steps): ?>
				<tr>
					<td align="center"><?=$steps['stp_dttime_disply']?></td>
					<td align="center"><?=$steps['tkt_details']?></td>
					<td align="center"><?=$steps['stp_steps']?></td>
				</tr>
				<?php endforeach?>
			</tbody>
		</table>
		</div>
		</div>
		</div>
		<?endif?>
		

	<div class="">
		<button type="button" class="btn btn-light" data-bs-dismiss="modal" style="margin-right: 19px;float: right;margin-top: 5px;margin-bottom: 5px;"> <i class="glyphicon glyphicon-ok text-success" ></i> Reviewed</button>
	</div>
</div>

<style>
.modal-dialog {
	width: 85%;
}
</style>
