<?php
session_name('CSOLAPP3030SESSID');
session_start ();
echo('
<!doctype html><html itemscope="" itemtype="http://schema.org/SearchResultsPage" lang="en">
<head>
<title>creativeSol Information Management System</title>
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1" name="viewport">
<link href="http://'.$_SERVER ['HTTP_HOST'].'/css/jquery-ui.min.css" rel="stylesheet">
<link href="http://'.$_SERVER ['HTTP_HOST'].'/css/bootstrap.css" rel="stylesheet">
<link href="http://'.$_SERVER ['HTTP_HOST'].'/css/general.css" rel="stylesheet">
</head>
');
?>
<div class="dynamic-popup" id="dynamic-popup">
<div class="modal-body">
<div class="col-md-12 center">

<p style="margin-top: 0px; margin-bottom: 5px;">
	<img width="800" src="<?='http://'.$_SERVER ['HTTP_HOST'].'/images/not_available.png'?>" alt="ast" 
	style="padding-left: 0;margin-top: -5rem;">
</p>

</div>
</div>
</div>
