<?php 
echo '<script src="http://' . $_SERVER['HTTP_HOST'] . '/js/highcharts.js"></script>';?>

<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="margin-top: -30px;;margin-right: 0%;">Print</button>
		<?=x(array('link'=>'erp_fund/cashflow/fedit','ref'=> $this->param['ref'],'label'=>'<button value="  Edit  " class="btn btn btn-primary pull-right" style="margin-top: -30px;margin-right: 1%;"><i class="glyphicon glyphicon-edit"></i>Edit</button>',array("param"=>'class="facebox"')))?>
		<h5 class="title-margin" style="padding-bottom: 14px;">Report: Cash Flow Details </h5>
	</div>
</div></div>
<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">


<div style="/*! padding: 3%; */padding-left: 3%;padding-right: 3%;padding-top: 2%;">
		<table class="rpt_tbl">
			<thead>
				<tr>
					<th width="1%" rowspan="4">
						<div class="title-margin">
							<img width="39" alt=""
								src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
								style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
						</div>
					</th>
				</tr>
				<tr>
					<th><div class="center" style="width: 79%;">Abdullah Salem
							Trading Est</div></th>
				</tr>
				<tr>
					<th width=""><div class="center"
							style="margin-top: 0px; margin-bottom: 10px; width: 79%;"></div></th>
				</tr>
				<tr>
					<th width=""><div class="center"
							style="margin-top: 0px; width: 79%;"> Cash Flow Details </div></th>
				</tr>
			</thead>
		</table>
	</div>

<div style="/*! padding: 3%; */padding-left: 3%;padding-right: 3%;">

		<table class="rpt_frame">
			<thead>
				<tr>
					<td width="15%" class="empty" style="border: 1px solid white;">Date:</td>
					<th width="20%" class="empty" style="border: 1px solid white;"><?= $this->cashBookDet['cb_dip_dt']?></th>
					<td width="40%"  align="right" class="empty" style="border: 1px solid white; ">Source:</td>
					<th width="40%" class="empty" style="border: 1px solid white;"><?= $this->cashBookDet['source_type']?></th>
				</tr>
				<tr>
					<td class="empty" style="border: 1px solid white;">Debit Amount:</td>
					<th class="empty" style="border: 1px solid white;"><?= $this->cashBookDet['cb_debit']?></th>
					<td align="right" class="empty" style="border: 1px solid white; ">Source Details:</td>
					<th class="empty" style="border: 1px solid white;"><?= $this->cashBookDet['source_details']?></th>
				</tr>
				<tr>
					<td width="10%" class="empty" style="border: 1px solid white;">Note:</td>
					<th colspan="3" class="empty" style="border: 1px solid white;"><?= $this->cashBookDet['cb_debit_note']?></th>
				</tr>
			</thead>
		</table>


		<div class="row mb-4" style="margin-top: 15px;">
		<div id="mh_varis" class="col-sm-12">
		<table class="rpt_frame">
				<tbody>
					<tr style="font-size: 0.8em;">
						<th class="text-center" style="padding-bottom: 5px;" width="10%">Date</th>
						<th class="text-center" style="padding-bottom: 5px;" width="40%">Details</th>
						<th class="text-center" style="padding-bottom: 5px;" width="10%">Amount (RO)</th>
						<th class="text-center" style="padding-bottom: 5px;" width="20%">Assigned To</th>
						<th class="text-center" style="padding-bottom: 5px;" width="10%">Progress</th>
						<?php if($_SESSION['user_acl']['erp_fund/cashflow/toggle']):?>
						<th class="text-center" style="padding-bottom: 5px;" width="5%">Approve</th>
						<?php endif;?>
					</tr>
				</tbody>
				<tbody >
				<?php if(count( $this->cashFlowDet)>0):?>
				<?php $i = 0; 
				foreach ( $this->cashFlowDet as $det):
					$encCfDetId = $this->encode($det['cf_id']);
					$plot[$i]['label'] = $det['cf_note'];
					$plot[$i]['amount'] = $det['cf_amount'];
					$i++;
					
				?>
					<tr index="0">
						<td class="text-center" valign="top"><?=$det['cdet_dip_dt']?>
						</td>
						<td valign="top">
							<div class="amtrow">
								<?=$det['cf_note']?>
							</div>
						</td>
						<td valign="top" align="right" style="padding-right: 5px;">
							<div class="amtrow">
								<?=$det['cf_amount']?>
							</div>
						</td>
						<td valign="top">
							<div class="cheqrow">
								<?=$det['emp_name']?>
							</div>
						</td>
						<td class="center">
							<?=x(array('link'=>'erp_fund/cashflow/billview','ref'=>$encCfDetId,'label'=>'<progress value="'.$det['pro_percentage'].'" min="0" max="100"></progress>',array("param"=>'class="facebox"')))?>
							
						</td>
						<?php if($_SESSION['user_acl']['erp_fund/cashflow/toggle']):?>
						<td>
    						<?php  $checked =  $det['cf_approve']==1?"":"checked" ;?>
    						<?=lx(array('link'=>'erp_fund/cashflow/toggle','ref'=>$encCfDetId,'label'=>'
    						<label class="switch" style="margin-left: 7px;margin-bottom: 0px;">
    						  <input type="checkbox" '.$checked.' onclick="return false;">
    						  <span class="slider round"></span>
    						</label>',array("param"=>'class="facebox"' )))?>
						</td>
						<?php endif;?>
						
					</tr>
					<?php endforeach;?>
					<?php endif;?>
				</tbody>
			</table>
		</div>
	</div>

		<table class="rpt_frame">
			<thead>
				<tr>
					<td align="right" width="50%" class="empty " style="border: 1px solid white;"><b>Total:</b></td>
					<td width="30%" class="empty" style="border: 1px solid white; "><b><?= $this->cashBookDet['cb_credit']?></b></td>
				</tr>
				<tr>
					<td align="right" width="50%" class="empty" style="border: 1px solid white;"><b>Balance:</b></td>
					<td width="30%" class="empty" style="border: 1px solid white; "><b><?=number_format( $this->cashBookDet['cb_debit']- $this->cashBookDet['cb_credit'],3)?></b></td>
				</tr>
			</thead>
		</table>
				



<div id="container" style="margin: 0 auto"></div>
</div>
</div>
</div>
</div>

<?php include "../footer";?>
<script type="text/javascript">


Highcharts.chart('container', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: ''
    },
    tooltip: {
        pointFormat: '{series.name}: <b> RO. {point.y:.3f} </b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.y:.3f} ',

                
                style: {
                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                }
            }
        }
    },
    series: [{
        name: 'RO',
        colorByPoint: true,
        data: [
			<?foreach ($plot as $val): ?>
            
        	{
            name: '<?=$val['label']?>',
            y: <?=$val['amount']?>,
        },

        <?php endforeach;?>

        ]
    }]
});
</script>
