<div class="card-block" style="padding-top: 2%;">
	<div class="full-width">
		<?=x(array('link'=>'erp_fund/cashflow/flow','label'=>'<button class="btn btn-success pull-right" >Cash Flow</button>',array("param"=>'class="facebox"')))?>
	</div>
	<h5 class="title-margin">Cash Flow List</h5>
</div>
<!--  
<div class="col-md-6">
	<div class="card" style="background-color: ghostwhite;
					border-radius: 15px;
					border-color: aquamarine;
					margin: 0 auto;
					margin-right: 18%;
					margin-left: 18%;">
			<div class="card-block" style="padding: 0;">
			<div class="card-block" style="padding: 0;padding-right: 20px;">
				<h4 class="card-title">Balance :</h4>
				<p class="card-text">
					<small class="text-muted"></small>
				</p>
			</div>
		</div>
	</div>
</div>
-->
<form method="get" id="filter" name="filter" action="list">
	<div class="col-md-12">
	</div>

<div class="col-md-12">
	<div class="card">
		<table class="table table-bordered grid">
			<thead>
				<tr>
					<th width="3%" class="center">Sl No</th>
					<th width="3%" class="center">Date</th>
					<th width="40%" class="center">Det.</th>
					<th width="4%" class="center">Debit</th>
					<th width="4%" class="center">Credit</th>
					<th width="3%" class="center">Edit</th>
					<?php if($_SESSION['user_acl']['erp_fund/cashflow/fview']):?>
					<th width="3%" class="center">View</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
			<?if(count( $this->cashBookList)>0):?>
				<?php foreach( $this->cashBookList as $cashBook):
					$encCbId = $this->encode($cashBook['cb_id']);
				
					if($cashBook['cfcount']==$cashBook['acount'])
						$icon = '<span class="glyphicon glyphicon-ok-circle" style="color:green"> </span>';
					elseif($cashBook['acount']==0)
						$icon = '<span class="glyphicon glyphicon-exclamation-sign" style="color:red">';
					else
						$icon = '<span class="glyphicon glyphicon-ok-circle" style="color:blue">';
				?>
				<tr>
					<td class="center"><?=@++ $this->offset;?></td>
					<td align="center"><?=$cashBook['cb_dip_dt']?></td>
					<td><?=$cashBook['cb_debit_note']?> <?=$cashBook['exp_details']?>  </td>
					<td align="right"><?=$cashBook['cb_debit']?></td>
					<td align="right"><?=$cashBook['cb_credit']?></td>					

					<td class="center"><?=x(array('link'=>'erp_fund/cashflow/fedit','ref'=>$encCbId,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?> 
					</td>
					<?php if($_SESSION['user_acl']['erp_fund/cashflow/fview']):?>
					<td class="center">
						<?=x(array('link'=>'erp_fund/cashflow/fview','ref'=>$encCbId,'label'=>'<button type="button" class="btn btn-default btn-lg" style="padding-top: 1px;padding-bottom: 0px;">
						  '.$icon.'
						</button>',array("param"=>'wide_opener')))?> 						
					</td>
					<?php endif;?>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<? $this->cashBookObj->pagination();?>
	</div>
</div>
</form>
<?=x(array('link'=>'erp_fund/cashflow/cashfreport','label'=>'
	<div class="col-md-3">
		<div class="card">
				<div class="card-block" style="background-color: ;">
				<div class="card-block">
					<h4 class="card-title center">Cash Flow Report</h4>
					<p class="card-text">
						<small class="text-muted"></small>
					</p>
				</div>
			</div>
		</div>
	</div>
', array("param"=>'wide_opener')),'<br><br>')?>

<?=x(array('link'=>'erp_fund/cashbook/cashreport','label'=>'
	<div class="col-md-3">
		<div class="card">
				<div class="card-block" style="background-color: ;">
				<div class="card-block">
					<h4 class="card-title center">Cash Book</h4>
					<p class="card-text">
						<small class="text-muted"></small>
					</p>
				</div>
			</div>
		</div>
	</div>
', array("param"=>'wide_opener')),'<br><br>')?>

<?php include "../footer"?>
<style>
.modal-dialog{
	 width: 85%;
}
</style>