<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" id="reset" name="reset" action='erp_fund/cashflow/toggle/ref/<?=$this->param['ref'];?>' style="margin-bottom: 0px;">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Approval</h4>
				<button aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
	
		<table class="rpt_frame">
		<tbody>
			<tr style="font-size: 0.8em;">
				<th width="2%" class="center">Sl.</th>
				<th class="text-center" style="padding-bottom: 5px;" width="40%">Details</th>
				<th class="text-center" style="padding-bottom: 5px;" width="10%">Amount (RO)</th>
			</tr>
		</tbody>
		<tbody>
	
		<?php $total =0; foreach ($this->cashFlowDetB as $cashdt):
		if($cashdt['exp_cash_flow'] || $cashdt['pay_cash_flow']):
		if($cashdt['file_id'])
			$encFileId = $this->encode($cashdt['file_id']);?>
					<tr index="0">
						<td class="center"><?=@++$sl;?></td>
						<td valign="top">
							<div class="amtrow"><?php if($cashdt['file_id']):?>
							<?=x(array('link'=>'download?file='.$encFileId,'label'=>$cashdt['exp_details'].$cashdt['pay_remarks'],array("param"=>"class='facebox'")))?>
						<?php else:?>
							<?=$cashdt['exp_details'].$cashdt['pay_remarks'];?>
						<?php endif;?>
							</div>
						</td>
						<td style="padding-right: 5px;" valign="top" align="right">
							<div class="amtrow"><?=$cashdt['exp_amount']?><?=$cashdt['pay_amount']?>
							<?php $total+= ($cashdt['exp_amount']+$cashdt['pay_amount'])?></div>
						</td>
					</tr>
			<?php 
		endif;endforeach;
		?>
		<tr>
				<td class="center"></td>
				<td valign="top" align="right"> <b> Total</b></td>
				<td style="padding-right: 5px;" valign="top" align="right">
				<div class="amtrow"><b><?=number_format($total,3)?></b></div>
				</td>
		</tr>
		<tr>
				<td class="center"></td>
				<td valign="top" align="right"> <b> Balance  ( <?=number_format((float)$cashdt['cf_amount'],3); ?> -  <?=number_format($total,3)?> )</b></td>
				<td style="padding-right: 5px;" valign="top" align="right">
				<div class="amtrow"><b><?=number_format($cashdt['cf_amount']-$total,3)?> </b></div>
				</td>
		</tr>
	
		</tbody>
		</table>
	
	<div class="modal-footer popup-footer" style="text-align: left;">
			<div class="row mb-4" style="margin-top: 15px;">
				<label class="col-sm-12 form-label" style="padding-left: 5%;"> " <?=$this->cashFlowDet['cf_note']?> - <?=number_format($this->cashFlowDet['cf_amount'],3);?> "  </label>
			</div>
			<div class="row mb-4" style="margin-top: 15px;">

				<label class="col-sm-6 form-label" style="padding-left: 5%;"> <i>Confirm the cash transaction ?  </i></label>
				<div class="col-sm-3">
	                 <?=$this->form->status->show()?>
	            </div>
			</div>	
	</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Confirm !</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal" onclick="$('#myModal').modal('hide');">Close</button>
	</div>
</form>	
</div>
<style>
.modal-dialog{
	width: 65%;
}
</style>