<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" id="add"
		action='erp_masters/building/add' style="margin-bottom: 0px;">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Add Building</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
			<div class="row mb-4" style="margin-top: 15px;">
				<label class="col-sm-2 form-label">Name</label>
				<div class="col-sm-5">
                    <?=$this->form->bld_name->show()?>
                  </div>

				<label class="col-sm-1 form-label">No.</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_no->show()?>
                  </div>
			</div>
			<div class="row mb-4">
				<label class="col-sm-2 form-label">Area</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_area->show()?>
                  </div>

				<label class="col-sm-2 form-label">Block No.</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_block_no->show()?>
                  </div>
			</div>
			<div class="row mb-4">
				<label class="col-sm-2 form-label">Plot</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_plot_no->show()?>
                  </div>
				<label class="col-sm-2 form-label">Way</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_way->show()?>
                  </div>
			</div>
			<div class="row mb-4">
				<label class="col-sm-2 form-label">Street</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_street->show()?>
                  </div>
				<label class="col-sm-2 form-label">Block Name</label>
				<div class="col-sm-4">
                    <?=$this->form->bld_block->show()?>
                  </div>
			</div>
		</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary submit-alias livepost">Save
					changes</button>
				<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
			</div>
		</div>
	</form>
</div>

<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '700px');
})
</script>

