<form method="get" id="filter" name="filter" action="dash">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<!-- CONTAINER -->
			<div class="main-container container">
				<!-- PAGE-HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">Property Status Board</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Property Status Board</li>
						</ol>
					</div>
					<div class="ms-auto pageheader-btn">
                        <?=x(array('link'=>'erp_masters/building/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')))?>
					</div>
				</div>
				<!-- PAGE-HEADER END -->
				<!-- ROW -->
				<div class="row row-sm">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Filters</h3>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-3">
										<div class="form-group">
											<label for="file_no" class="form-label">Building</label>
                                            <?=$this->form->f_building->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label for="name" class="form-label">Category</label>
                                            <?=$this->form->f_build_cat->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label for="name" class="form-label"></label>
    								<button class="btn <?=$this->filter_class?> mt-4 mb-0"
    									type="submit">Filter</button>
    								<input class="btn btn-secondary mt-4 mb-0" name="clear"
    									type="submit" value="All"></input>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div></div>


			<div class="main-content mt-0 hor-content">
				<div class="side-app">
					<!-- CONTAINER -->
					<div class="main-container container">
						<div class="row row-sm">
							<div class="col-lg-12">
								<div class="card">
									<div class="card-header">
										<h3 class="card-title">Property Status</h3>
									</div>
									<div class="card-body">
										<div class="">
											<div class="main_wrapper_flat mb-5">
												<div class="flat_map_wrap w+">
													<div id="flat-map" class="flatCharts-container"
														tabindex="0" aria-activedescendant="4_3"
														style="width: 100%; float: right; padding-right: 0px;">
														<div class="flatCharts-row"
															style="float: right; padding-bottom: 6px; margin-top: 5px;">
															<div class="flatCharts-cell flatCharts-space"
																style="width: 60px; text-align: left !important;">Status</div>
															<div id="1_2" role="checkbox" aria-checked="true"
																focusable="true" tabindex="-1"
																class="flatCharts-flat flatCharts-cell
										available"
																style="width: 90px;">Vacant</div>
															<div id="1_3" role="checkbox" aria-checked="true"
																focusable="true" tabindex="-1"
																class="flatCharts-flat flatCharts-cell
										selected"
																style="width: 90px;">Occupaid</div>
															<div id="1_4" role="checkbox" aria-checked="true"
																focusable="true" tabindex="-1"
																class="flatCharts-flat flatCharts-cell
										undermaintenence"
																style="width: 90px;">Maintenence</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="progress">
											<div title="<?=$this->sCount['Vacant%'] ?>%" class="progress-bar" role="progressbar" style="width: <?=$this->sCount['Vacant%'] ?>%; background-color: lightgrey !important" aria-valuenow="<?=$this->sCount['Vacant%'] ?>" aria-valuemin="0" aria-valuemax="100">
                                    Vacant :
                                    <?=$this->sCount['Vacant%'] ?>%</div>
											<div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: <?=$this->sCount['Agreement%'] ?>%; background-color: #26c426 !important" aria-valuenow="<?=$this->sCount['Agreement%'] ?>" aria-valuemin="0" aria-valuemax="100">
                                    Occupaid :
                                    <?=$this->sCount['Agreement%'] ?>%</div>
											<div class="progress-bar bg-info " role="progressbar" style="width: <?=$this->sCount['Maintenance%'] ?>%; background-color: orange !important" aria-valuenow="<?=$this->sCount['Maintenance%'] ?>" aria-valuemin="0" aria-valuemax="100">
                                    Maintenance :
                                    <?=$this->sCount['Maintenance%'] ?>%</div>
										</div>
									</div>
                        <?php foreach ($this->propList as $bId=>$building) {;?>
                        <div class="card-body">
										<div class="card-header">
											<h3 class="card-title">
                                    <?=$this->buildList[$bId] ?>
                                </h3>
										</div>
										<div class="wrapper">
											<div class="main_wrapper_flat mb-5">
												<div class="flat_map_wrap w+">
													<div id="flat-map" class="flatCharts-container"
														tabindex="0" aria-activedescendant="4_3">
                                            <?php foreach ($building as $fName=>$floor):?>
                                            <div class="flatCharts-row"
															style="float: left; padding-bottom: 6px; margin-top: 5px;">
															<div class="flatCharts-cell flatCharts-space"
																style="width: 160px; text-align: left !important;">
                                                    <?=$fName?>
                                                </div>
                                                <?php $i=2; foreach ($floor as $pName=>$pStatus): ?>
                                                <?php

                                    if ($pStatus == 'Agreement') {
                                        $check = 'aria-checked="true"';
                                        $avail = 'selected';
                                        $lbl = "O";
                                    } else if ($pStatus == 'Maintenance') {
                                        $check = 'aria-checked="true"';
                                        $avail = 'undermaintenence';
                                        $lbl = "M";
                                    } else {
                                        $check = 'aria-checked="false"';
                                        $avail = 'available';
                                        $lbl = "V";
                                    }
                                    ?>
                                                <div id="1_<?=$i;?>"
																role="checkbox" <?=$check;?> focusable="true"
																tabindex="-1"
																class="flatCharts-flat flatCharts-cell
                                                    <?=$avail?>">
                                                    <?=$pName?>
                                                </div>
                                                <?php $i++; endforeach;?>
                                                <div
																class="flatCharts-cell flatCharts-space"></div>
														</div>
														</br> </br>
                                            <?php  endforeach;?>
                                        </div>
												</div>
											</div>
										</div>
									</div>
                        <?}?>
                    </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

<style>
div.flatCharts-flat.selected {
	background-color: #26c426;
}

div.flatCharts-cell {
	width: 70px;
}

.flat_map_wrap {
	justify-content: flex-start;
}

.progress {
	height: 2rem;
	border-radius: 5px;
}
</style>
