<?$offset = $this->buildingObj->_voffset;?>

<form method="get" id="filter" name="filter" action="list">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<!-- CONTAINER -->
			<div class="main-container container">
				<!-- PAGE-HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">List of Buildng</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Manage
								Buildng</li>
						</ol>
					</div>
					<div class="ms-auto pageheader-btn">
                        <?=x(array('link'=>'erp_masters/building/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')))?>
					</div>
				</div>
				<!-- PAGE-HEADER END -->
				<!-- ROW -->
				<div class="row row-sm">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Filters</h3>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-3">
										<div class="form-group">
											<label for="file_no" class="form-label">Building Name</label>
                                            <?=$this->form->f_bld_name->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label for="name" class="form-label">Building No.</label>
                                            <?=$this->form->f_bld_no->show()?>
                                        </div>
									</div>
								</div>
								<button class="btn <?=$this->filter_class?> mt-4 mb-0"
									type="submit">Filter</button>
								<input class="btn btn-secondary mt-4 mb-0" name="clear"
									type="submit" value="All"></input>
							</div>
						</div>
					</div>
					<div class="">
						<div class="">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Properties</h3>
								</div>
								<div class="card-body">
									<div class="table-responsive export-table">
										<table aria-describedby=""
											class="table table-bordered no-footer">
											<thead class="border-top">
												<tr role="row">
													<th width="5%" class="center">Sl No</th>
													<th width="25%" class="center">Building Name</th>
													<th width="8%" class="center">Company</th>
													<th width="8%" class="center">No.</th>
													<th width="8%" class="center">Area</th>
													<th width="8%" class="center">Block No.</th>
													<th width="8%" class="center">Plot No.</th>
													<th width="8%" class="center">Way</th>
													<th width="8%" class="center">Street</th>
													<th width="8%" class="center">Block Name</th>
													<th width="5%" class="center">Edit</th>
													<th width="5%" class="center">View</th>
												</tr>
											</thead>
											<tbody>
			<?if(count($this->BuildingList)>0):?>
				<?php

foreach ($this->BuildingList as $build) :
        $encBuldId = $this->encode($build['bld_id']);
        ?>
				<tr>
													<td class="center"><?=@++$offset;?></td>
													<td><?=$build['bld_name']?></td>
													<td><?=$build['comp_disp_name']?></td>
													<td><?=$build['bld_no']?></td>
													<td><?=$build['bld_area']?></td>
													<td><?=$build['bld_block_no']?></td>
													<td><?=$build['bld_plot_no']?></td>
													<td><?=$build['bld_way']?></td>
													<td><?=$build['bld_street']?></td>
													<td><?=$build['bld_block']?></td>

													<td class="center">
						<?=x(array('link'=>'erp_masters/building/edit','ref'=>array('ref'=>$encBuldId),'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>  
					</td>
													<td class="center">
						<?=x(array('link'=>'erp_masters/building/view','ref'=>array('ref'=>$encBuldId),'label'=>'<i class="fas fa-search"></i>',array("param"=>'class="facebox"')))?> 
					</td>
												</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
										</table>
		<?$this->buildingObj->pagination();?>
	</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>



