<div class="dynamic-popup" id="dynamic-popup">
	<!--  -->
	<form name="form" method="post" id="add"
		action='admin/users/add' style="margin-bottom: 0px;">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Add New User</h4>
				<button aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-3 form-label">First Name</label>
					<div class="col-sm-9">
                    <?=$this->form->fname->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">Last Name</label>
					<div class="col-sm-9">
                    <?=$this->form->lname->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">User Name</label>
					<div class="col-sm-9">
                    <?=$this->form->uname->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">Password </label>
					<div class="col-sm-9">
                    <?=$this->form->password->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">Role</label>
					<div class="col-sm-9">
                    <?=$this->form->desig->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">Status</label>
					<div class="col-sm-9">
                    <?=$this->form->status->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">Employee</label>
					<div class="col-sm-9">
                    <?=$this->form->employee->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">e-Mail</label>
					<div class="col-sm-4">
                     <?=$this->form->email->show()?></div>
					<div class="col-sm-4" style="margin-top: 10px;margin-left: -20px;">
                    <span>@astglobal.om</span></div>                     
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary submit-alias livepost">Add</button>
				<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
			</div>
		</div>
	</form>
</div>


<script type="text/javascript">           
$(document).ready(function() {

	typetoggle($('#type').val());

	$('#type').on('change',function() {
		typetoggle($(this).val());
	});
	function typetoggle(type){
		if(type==2)
			$('#login_det').show();
		else
			$('#login_det').hide();
	}
});
</script>
