<div class="dynamic-popup" id="dynamic-popup">
	<!--  -->
	<form name="form" method="post" id="edit" name="edit"
		action='admin/users/edit/ref/<?=$this->param['ref']?>'
		style="margin-bottom: 0px;">

		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Update user's details</h4>
				<button aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>



			<div class="modal-body">
				<div class="row mb-4">
					<label class="col-sm-3 form-label">First Name</label>
					<div class="col-sm-9">
                    <?=$this->form->fname->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">Last Name</label>
					<div class="col-sm-9">
                    <?=$this->form->lname->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">Role</label>
					<div class="col-sm-9">
                    <?=$this->form->desig->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">Employeee</label>
					<div class="col-sm-9">
                    <?=$this->form->status->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label">Status</label>
					<div class="col-sm-9">
                    <?=$this->form->employee->show()?>
                  </div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary submit-alias livepost">Update</button>
				<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
			</div>
	</div>
	</form>
</div>