<?$offset = $this->userObj->_voffset;?>
<form method="get" id="filter" name="filter" action="list">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<!-- CONTAINER -->
			<div class="main-container container">
				<!-- PAGE-HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">Users</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Users</li>
						</ol>
					</div>
					<div class="ms-auto pageheader-btn">
						<?=x(array('link'=>'admin/users/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')),'<br><br>')?>
					</div>
				</div>
				<!-- PAGE-HEADER END -->
				<!-- ROW -->
				<div class="row row-sm">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Filters</h3>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-3">
										<div class="form-group">
											<label for="file_no" class="form-label">Name</label>
                                            <?=$this->form->f_fname->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label for="name" class="form-label">User Name</label>
                                            <?=$this->form->f_uname->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Role</label>
                                            <?=$this->form->f_desig->show()?>
                                        </div>
									</div>
								</div>
								<button class="btn <?=$this->filter_class?> mt-4 mb-0"
									type="submit">Filter</button>
								<input class="btn btn-secondary mt-4 mb-0" name="clear"
									type="submit" value="All"></input>
							</div>
						</div>
					</div>
					<!-- ROW -->
					<div class="">
						<div class="">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Users</h3>
								</div>
								<div class="card-body">
									<div class="table-responsive export-table">
                                        <table aria-describedby="" class="table table-bordered text-nowrap no-footer">
                                                <thead class="border-top">
                                                  <tr role="row">
					<th width="5%" class="center">Sl No</th>
					<th width="15%" class="center">First Name</th>
					<th width="15%" class="center">Last Name</th>
					<th width="15%" class="center">User Name</th>
					<th width="8%" class="center">Role</th>
					<th width="6%" class="center">Edit</th>
					<th width="6%" class="center">Reset</th>
					<th width="5%" class="center">Status</th>
					<th width="6%" class="center">View</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->usersList)>0):?>
				<?foreach($this->usersList as $user):
				$encUserId = $this->encode($user['user_id']); ?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$user['user_fname']?></td>
					<td><?=$user['user_lname']?></td>
					<td><?=$user['user_uname']?></td>
					<td><?=$this->roll[$user['user_desig']]?></td>
					<td class="center">
					<?php if($user['user_id']!=$_SESSION ['user_id']):?>
						<?=x(array('link'=>'admin/users/edit','ref'=>array('ref'=>$encUserId),'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?></td>
					<?php endif?>
					<td class="center">
					<?php if($user['user_id']!=$_SESSION ['user_id']):?>
						<?=x(array('link'=>'admin/users/reset','ref'=>array('ref'=>$encUserId),'label'=>'<i class="glyphicon glyphicon-refresh text-success"></i>',array("param"=>'class="facebox"')))?></td>
					<?php endif?>
					<td class="center"><?if($user['user_status']==1):?><p class="text-success"> Enabled </p> <?else:?>
					<p class="text-danger"> Disabled </p> <?endif?></td>
					<td class="center">
						<?=x(array('link'=>'admin/users/view','ref'=>array('ref'=>$encUserId),'label'=>'<i class="fas fa-search"></i>',array("param"=>'class="facebox"')))?> 
					</td>
				</tr>
				<?endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?$this->userObj->pagination();?>
	</div>
</div></div></div></div></div></div></div></div>
</form>
