
<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="reset" name="reset" action='admin/users/reset/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button aria-label="Close" class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true">×</span></button>
		<h4 class="modal-title">Reset Password</h4>
	</div>
	<div class="modal-body">
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Name of user</label>
					<div class="col-sm-9">
					<?=$this->userDetail['user_fname']?>-<?=$this->userDetail['user_lname']?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Password</label>
					<div class="col-sm-9">
                    <?=$this->form->password->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Confirm Password</label>
					<div class="col-sm-9">
                    <?=$this->form->conPassword->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Reset</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>
