<div class="dynamic-popup" id="dynamic-popup">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">User details</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >First
						Name</label>
					<div class="col-sm-9">
                    <?=$this->userDetail['user_fname']?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Last
						Name</label>
					<div class="col-sm-9">
                    <?=$this->userDetail['user_lname']?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >User
						Name</label>
					<div class="col-sm-9">
                    <?=$this->userDetail['user_uname']?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >User Type</label>
					<div class="col-sm-9">
                    <?=$this->roll[$this->userDetail['user_type']]?>
                  </div>
				</div>

				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Status</label>
					<div class="col-sm-9">
                     <?=$this->status[$this->userDetail['user_status']]?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '500px');
})
</script>
