<?$offset = $this->empObj->_voffset;?>
<form method="get" id="filter" name="filter" action="">
<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 5px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">VAT : Statement of Expense</h5>
	</div>
	
<div class="row g-1">

    <div class="col-lg-3">
        <label class="form-label">Clients</label>
        <?=$this->form->f_client->show()?>
    </div>

    <div class="col-lg-3">
        <label class="form-label">Projects</label>
        <?=$this->form->f_project->show()?>
    </div>

    <div class="col-lg-3">
        <label class="form-label">Ref No.</label>
        <?=$this->form->f_refno->show()?>
    </div>

    <div class="col-lg-3">
        <label class="form-label">Vendor</label>
        <?=$this->form->f_selVendor->show()?>
    </div>

    <div class="col-lg-3">
        <label class="form-label">Main Head</label>
        <?=$this->form->f_mainhead->show()?>
    </div>

    <div class="col-lg-3">
        <label class="form-label">Main Cat.</label>
        <?=$this->form->f_pCatSelect->show()?>
    </div>
    
        <div class="col-lg-3">
        <label class="form-label">Sub Cat.</label>
        <?=$this->form->f_sCatSelect->show()?>
    </div>

    <div class="col-lg-3">
        <label class="form-label">Cat.</label>
        <?=$this->form->f_cCatSelect->show()?>
    </div>

</div>

<!-- TOGGLED -->
<div class="row g-1 mt-1">

    <div id="mh_emp" class="col-lg-6" style="display:none;">
        <label class="form-label"><small>Employee</small></label>
        <?=$this->form->f_employee->show()?>
    </div>

    <div id="mh_veh" class="col-lg-6" style="display:none;">
        <label class="form-label"><small>Vehicle</small></label>
        <?=$this->form->f_vehicle->show()?>
    </div>
    
        <div class="col-lg-3">
        <label class="form-label">Particulars</label>
        <?=$this->form->f_particulers->show()?>
    </div>

    <div class="col-lg-3">
        <label class="form-label">Mode</label>
        <?=$this->form->f_mode->show()?>
    </div>

</div>

<hr>

<div class="row g-1">

    <div class="col-lg-2">
        <label class="form-label">Amount</label>
        <?=$this->form->f_amount->show()?>
    </div>

    <div class="col-lg-2">
        <label class="form-label">Period</label>
        <?=$this->form->f_period->show()?>
    </div>

    <div class="col-lg-2 pr_month">
        <label class="form-label">Month</label>
        <?=$this->form->f_monthpick->show()?>
    </div>

    <div class="col-lg-2 pr_fdt">
        <label class="form-label">From</label>
        <?=$this->form->f_dtfrom->show()?>
    </div>

    <div class="col-lg-2 pr_tdt">
        <label class="form-label">To</label>
        <?=$this->form->f_dtto->show()?>
    </div>

    <div class="col-lg-2">
        <label class="form-label">Approval</label>
        <?=$this->form->f_status->show()?>
    </div>
    
        <div class="col-lg-2 ">
        <label class="form-label">Actions</label>
        <button class="btn  <?=$this->filter_class?>" type="submit">Filter</button>
        <input class="btn  btn-secondary" name="clear" type="submit" value="All">
        <button class="btn  btn-secondary-gradient" type="button" onclick="tableToExcelX();">
            Export Excel
        </button>
    </div>

</div>

<hr>


<div class="row mt-2">

</div>

<style>

.form-label {
    margin-bottom: 2px;
    font-size: 0.85rem;
}

.form-group,
.form-control,
.chosen-container {
    margin-bottom: 0 !important;
}

hr {
    margin: 6px 0;
}

</style>

</div>

		
		</form>
	</div>
	
	





<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
		<div style="margin-top: 3%;">
			<table class="rpt_tbl">
				<thead>
					<tr>
						<th width="1%" rowspan="3">
							<div class="title-margin">
								<img width="50" alt=""
									src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
									style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
							</div>
						</th>
					</tr>
					<tr>
						<th ><div class="center" style="width: 79%;">Abdullah
								Salem Trading Est</div></th>
					</tr>
					<tr>
						<th width=""><div class="center"
								style="margin-top: 0px; margin-bottom: 10px; width: 79%;">VAT : Statement of Expense </div></th>
					</tr>
				</thead>
			</table>
		</div>
		
		<table class="rpt_frame" style="table-layout: fixed; width: 100%;" id="report_table">
			<thead>
				<tr>
					<th class="empty" colspan="8"></th>
				</tr>
                <tr>
                	<th width="4%" class="center">Sl. No.</th>
                	<th width="10%" class="center">Bill No.</th>
                	<th width="8%" class="center">Date</th>
                	<th width="28%" class="center">Vendor</th>
                	<th width="12%" class="center">VAT No.</th>
                	<th width="12%" class="center">Amount</th>
                	<th width="12%" class="center">VAT Amount</th>
                	<th width="14%" class="center">Total Amount</th>
                </tr>

			</thead>
			<tbody>
			<?if(is_array($this->expenseList) && count($this->expenseList)>0):?>
				<?php foreach($this->expenseList as $expense):
				$encExpId = $this->encode($expense['exp_id']);
				$encFileId = $this->encode($expense['file_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td class="center">
						<?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>$expense['exp_refno'],array("param"=>'opener')))?>	
					</td>
					<td class="center"><?=$expense['exp_billdt']?></td>
					<td><?=$expense['ven_disp_name']?></td>
					<td class="center"><?=$expense['ven_vat_no']?></td>
					<td align="right"><?=$expense['exp_novat_amt']?></td>
					<td align="right"><?=$expense['exp_vat_amt']?></td>
					<td align="right"><?=$expense['exp_novat_amt']+$expense['exp_vat_amt']?></td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>

		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>Expense MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
</div>
</div>
</div>
</div>
</form>

<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
    fixmainhead();
	$('#f_mainhead').on('change',function() {
		fixmainhead();
		$("#f_employee").val([]);
		$("#f_property").val([]);
		$("#f_vehicle").val([]);
		$('.chosen-select').chosen('destroy'); 
		$(".chosen-select").chosen({
			no_results_text : "Oops, nothing found!",
		    search_contains: true,
		    enable_split_word_search: true
		});
	});
	toggledtoptions();
	/*$('#id_dtdys').hide();
	$('#id_days').hide();
	$('#id_date').hide();*/

	
	$('#f_period1').on('click',function() {
		toggledtoptions();
	});

	$('#f_period2').on('click',function() {
		toggledtoptions();
	});
});

function toggledtoptions(){
	//$('#f_monthpick').val('');
	//$('#pr_fdt').val('');
	//$('#pr_fdt').val('');
	if($('#f_period1').is(':checked')){
		$('.pr_month').show();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
	else if($('#f_period2').is(':checked')){
		$('.pr_month').hide();
		$('.pr_fdt').show();
		$('.pr_tdt').show();
	}
	else{
		$('.pr_month').hide();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
}
  
$(document).ready(function() {
	var source = '<?=APPURL?>'+ 'erp_expense/expense/getlive';
	$('#f_pCatSelect').on('change',function() {
		getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');
		$('#f_cCatSelect').empty();
	});
	getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');

	$('#f_sCatSelect').on('change',function() {
		getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
	});
	getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
});

function fixmainhead(){
	
	if($('#f_mainhead').val()==1){
		$('#mh_emp').show();
		$('#mh_prop').hide();
		$('#mh_veh').hide();
	}
	else if($('#f_mainhead').val()==2){
		$('#mh_prop').show();
		$('#mh_emp').hide();
		$('#mh_veh').hide();
	}
	else if($('#f_mainhead').val()==3){
		$('#mh_veh').show();
		$('#mh_emp').hide();
		$('#mh_prop').hide();
	}
	else{
		$('#mh_emp').hide();
		$('#mh_prop').hide();
		$('#mh_veh').hide();
	}
}


function tableToExcelX() {
	let table = document.getElementById("report_table");
	var dt = new Date();
	var time = (dt.getMonth() + 1) + '' + dt.getDate() + '' + dt.getFullYear() + '' + dt.getHours() + '' + dt.getMinutes() + dt.getSeconds();
	TableToExcel.convert(table, { // html code may contain multiple tables so here we are refering to 1st table tag
		name: `Export_Report_` + time + `.xlsx`, // fileName you could use any name
		sheet: {
			name: 'Sheet 1' // sheetName
		}
	});
}

</script>

