<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
				<h5 class="title-margin">Summary/Statement of Expense - Category Wise </h5>
	</div>
		<form method="get" id="filter" name="filter" action="">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="10%">Main Head</th>

				<th align="center" width="10%">Period(Month/Period)</th>
				<th class="pr_month" width="10%">Month</th>
				<th class="pr_fdt" width="10%">From</th>
				<th class="pr_tdt" width="10%">To</th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_mainhead->show()?>
              		</div>
				</td>
				<td align="center">
					<div class="form-group ">
                	<?=$this->form->f_period->show()?>
              		</div>
				</td>
				<td class="pr_month">
					<div class="form-group ">
                	<?=$this->form->f_monthpick->show()?>
              		</div>
				</td>
				<td class="pr_fdt">
					<div class="form-group ">
                	<?=$this->form->f_dtfrom->show()?>
              		</div>
				</td>
				<td class="pr_tdt">
					<div class="form-group ">
                	<?=$this->form->f_dtto->show()?>
              		</div>
				</td>
			</tr>
			<tr style="font-size: 0.8em;">
				<th width="10%">Main Cat.</th>
				<th width="10%">Sub Cat.</th>
				<th width="10%">Cat.</th>
				<th width="10%">Mode</th>
				<th width="10%"></th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_pCatSelect->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_sCatSelect->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_cCatSelect->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_mode->show()?>
              		</div>
				</td>
				
				<td align="center">
	              <div class="form-group ">
	              	<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
		</form>
	</div>



<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
		<div style="margin-top: 3%;">
			<table class="rpt_tbl">
				<thead>
					<tr>
						<th width="1%" rowspan="3">
							<div class="title-margin">
								<img width="50" alt=""
									src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
									style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
							</div>
						</th>
					</tr>
					<tr>
						<th ><div class="center" style="width: 79%;">Abdullah
								Salem Trading Est</div></th>
					</tr>
					<tr>
						<th width=""><div class="center"
								style="margin-top: 0px; margin-bottom: 10px; width: 79%;"><?=@$this->modeNo[$this->f_mode]?>Statement of Expense [<?=@$this->mode[$this->f_mode]?>] - Category Wise <?=$this->title;?></div></th>
					</tr>
				</thead>
			</table>
		</div>
		<table class="rpt_frame">
			<thead>
				<tr>
					<td class="empty" colspan="5" style="border: 1px solid white;">
					</td>
					<td class="empty" style="border: 1px solid white;">
					<?php $date = new DateTime();$date = $date->format('d/m/Y')?>
					Date : <?=$date;?></td>
				</tr>
				<tr>
					<th class="empty" colspan="5"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="12%"class="center">Main Head</th>
					<th width="9%" class="center">Main Category</th>
					<th width="9%" class="center">Sub Category</th>
					<th width="9%" class="center">Category</th>
					<th width="4%" class="center">Amount</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->expenseList)>0):?>
				<?php foreach($this->expenseList as $expense):
				//$encExpId = $this->encode($expense['exp_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$expense['main_head_txt']?></td>
					<td><?=$expense['pcat']?></td>
					<td><?=$expense['scat']?></td>
					<td><?=$expense['ccat']?></td>
					<td align="right"><?$sum+=$expense['sum'];?>
						<?=x(array('link'=>'erp_report/expense/expense','ref'=>array(
                            'f_mainhead'=>$expense['exp_mainh'],
						    'f_pCatSelect'=>$expense['pcat_id'],
						    'f_sCatSelect'=>$expense['scat_id'],
						    'f_cCatSelect'=>$expense['ccat_id'],
						    'f_mode'=>$this->f_mode),
						    'label'=>$expense['sum']))?>			
					</td>
				</tr>
				<?php endforeach?>
				<tr>
				<th colspan="5"> Total:</th>
				<th style="text-align: right;"> <?=number_format($sum,3)?></th>
				</tr>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>Expense MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</div>
</form>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
	toggledtoptions();
	/*$('#id_dtdys').hide();
	$('#id_days').hide();
	$('#id_date').hide();*/

	
	$('#f_period1').on('click',function() {
		toggledtoptions();
	});

	$('#f_period2').on('click',function() {
		toggledtoptions();
	});
});

function toggledtoptions(){
	//$('#f_monthpick').val('');
	//$('#pr_fdt').val('');
	//$('#pr_fdt').val('');
	if($('#f_period1').is(':checked')){
		$('.pr_month').show();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
	else if($('#f_period2').is(':checked')){
		$('.pr_month').hide();
		$('.pr_fdt').show();
		$('.pr_tdt').show();
	}
	else{
		$('.pr_month').hide();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
}
  
$(document).ready(function() {
	var source = '<?=APPURL?>'+ 'erp_expense/expense/getlive';
	$('#f_pCatSelect').on('change',function() {
		getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');
		$('#f_cCatSelect').empty();
	});
	getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');

	$('#f_sCatSelect').on('change',function() {
		getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
	});
	getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
});

</script>

