<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">Report: <?=$this->title?></h5>
	</div>
		<form method="get" id="filter" name="filter" action="">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="20%">Vendor</th>
				<th width="15%">Expiry Month</th>
				<th width="50%"></th>
			</tr>
			<tr>	
				<td>
					<div class="form-group ">
                	<?=$this->form->f_selVendor->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group">
                	<?=$this->form->f_monthpick->show()?>
              		</div>
				</td>
				<td align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
		</form>
	</div>

<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
								<tr>
									<th width="1%" rowspan="4">
										<div class="title-margin">
											<img width="50" alt=""
												src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
												style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
										</div>
									</th>
								</tr>
								<tr>
									<th><div class="center" style="width: 79%;">ABDULLAH BIN SALEM TRADING EST.</div></th>
								</tr>
								<tr>
									<th width="">
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%; font-family: f11; font-size:9pt;">
											<b> مؤسسة عبدالله بن سالم للتجارة </b>
										</div>

									</th>
								</tr>
								<tr>
									<th>
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%;"><?=$this->title?></div>
									</th>
								</tr>
							</thead>
						</table>
					</div>
					<table class="rpt_frame">
			<thead>
				<tr>
					<td class="empty" colspan="4" style="border: 1px solid white;">
					</td>
					<td class="empty" style="border: 1px solid white;">
					<?php $date = new DateTime();$date = $date->format('d/m/Y')?>
					Date : <?=$date;?></td>
				</tr>
				<tr>
					<th class="empty" colspan="5"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="20%" class="center">Vendor Name</th>
					<th width="8%" class="center">Date.</th>
					<th width="15%" class="center">Particulers</th>
					<th width="8%" class="center">Paid Amount</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->payList)>0):?>
				<?php foreach($this->payList as $pay):
				//$encCustId = $this->encode($pay['cust_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$pay['ven_name']?>
					</td>
					<td align="center"><?=$pay['pay_date']?></td>
					<td align="left"><?=$pay['bill_det']?></td>
					<td align="right"><?=number_format($pay['pay_amount'],3); $total+=$pay['pay_amount'];?></td>
				</tr>
				<?php endforeach?>
				<tr><td colspan="4" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($total,3)?></b></td>
				</tr>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</form>
</div>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
</script>


