<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" id="delete" action='erp_projects/rent/deletedemand/ref/<?=$this->param['ref'];?>' style="margin-bottom: 0px;">
	<input type="hidden" value="<?=$this->param['ref'];?>" name="hidden">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Delete cash demand</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div></div>
			<div class="modal-body">
		<b>Demand : <?=$this->casDmdDetDetail['cdmd_narration']?></b>
		</br>
			Are you sure to delete the demand from the system?
		</br>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Confirm</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>
