<div class="card-block" style="padding-top: 3%; padding-left: 14%; padding-right: 13%;">
    <button 
        name="cmdPrint" 
        value="Print" 
        onclick="$('#report').printElement();" 
        class="btn btn-primary pull-right" 
        style="padding: 2px 12px; margin-top: -4%;">
        Print
    </button>
    <h5 class="title-margin">
        Invoice No :
        <b>
            <?php
                echo $this->billInfo['bill_book_no'] <> ''
                    ? $this->billInfo['bill_book_no']
                    : $this->billInfo['comp_disp_name']."/" . sprintf("%04s", $this->billInfo['bill_id']);
            ?>
        </b>
    </h5>
</div>

<div class="col-md-12 card" style="height: auto; padding-right: 2%; margin-left: 14%; max-width: 800px; padding-left: 2%; border-color: lightskyblue;">

    <?php if (count($this->collection) > 0): ?>
        <div class="card-block" style="padding-top: 2%;">
            <h4>Collection Details</h4>
        </div>

        <div class="card">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th class="center" width="3%">Sl No</th>
                        <th class="center" width="5%">Payment Date</th>
                        <th class="center" width="5%">Amount Pending</th>
                        <th class="center" width="5%">Amount Collected</th>
                        <th class="center" width="5%">Balance Amount</th>
                        <th class="center" width="15%">Remarks</th>
                        <th class="center" width="5%">Coll. File No.</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->collection as $coll): ?>
                        <tr>
                            <td class="center"><?= ++$offset; ?></td>
                            <td class="center"><?= $coll['coll_date']; ?></td>
                            <td class="center"><?= $coll['cdet_amt_topay']; ?></td>
                            <td class="center"><?= $coll['cdet_amt_paid']; ?></td>
                            <td class="center"><?= $coll['cdet_amt_bal']; ?></td>
                            <td><?= $coll['coll_remarks']; ?></td>
                            <td class="center">
                                <?php if ($coll['file_id']):
                                    $encFileId = $this->encode($coll['file_id']);
                                endif; ?>

                                <?= x([
                                    'link' => 'default/default/download',
                                    'ref' => $encFileId,
                                    'label' => '<i class="glyphicon glyphicon-file text-info">' . $coll['coll_file_no'] . '</i>',
                                    'param' => 'opener'
                                ]); ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>

    <?php $encFileId = $this->encode($this->billInfo['file_id']); ?>

    <?php if ($this->billInfo['bill_cancellation_status'] == 1): ?>
        <div class="ribbon ribbon-top-left">
            <span style="background-color: #FF0000;">Cancelled</span>
        </div>
    <?php endif; ?>

    <?php if ($this->billInfo['bill_pstatus'] == 1): ?>
        <div class="ribbon ribbon-top-left">
            <span>Paid</span>
        </div>
    <?php endif; ?>

    <div id="report" class="ribbon-box">
        <?php include_once __DIR__ . '/../../../../public/css/printstyle.php.css'; ?>

        <div style="margin-left: 15px; margin-top: 30px; padding: 0 5px; border-radius: 0px;">
            <div style="margin-top: 4rem; margin-bottom: 1pt;">
                <table class="rpt_tbl">
                    <tr>
                        <th width="100%">
                            <table style="margin-bottom: 1px; padding-left: 20px;" width="100%">
                                <tbody>
                                    <tr>
                                        <!-- LEFT ENGLISH NAME -->
                                        <th width="44%" style="font-family: Tahoma;">
                                            <div style="font-size: 1.8rem; letter-spacing: -1px; transform: scale(1, 2); font-family: Times;">
                                                IBN ABDULLAH SALEM
                                            </div>
                                            <div style="font-size: 14px; float: left; margin-top: 2%; letter-spacing: -1px;">
                                                TRADING SPC. (Since 1976)
                                            </div>
                                        </th>

                                        <th width="12%">
                                            <div class="title-margin" style="margin-left: 6%;">
                                                <img alt="" src="http://<?= $_SERVER['HTTP_HOST'] ?>/css/images/ast.png"
                                                     style="padding-bottom: 7px; padding-left: 10pt;" width="44">
                                            </div>
                                        </th>

                                        <!-- RIGHT ARABIC NAME -->
                                        <th width="44%" align="right">
                                            <div style="font-size: 1.6rem; font-family: f11; float: right; transform: scale(1, 2); margin-top: -2.5rem;">
                                                <b>  ابن عبدالله سالم للتجارة ش.ش.و </b>
                                            </div>
                                        </th>
                                    </tr>

                                    <tr>
                                        <td colspan="3" align="center" style="color:blue">www.astglobal.om</td>
                                    </tr>
                                </tbody>
                            </table>
                        </th>
                    </tr>

                    <tr>
                        <th colspan="9" style="border-top: 1px solid black;">
                            <table class="rpt_tbl" style="margin-top: 13px;">
                                <tr>
                                    <th><div class="center" style="width: 96%;">I N V O I C E</div></th>
                                </tr>
                            </table>
                        </th>
                    </tr>

                    <tr>
                        <td width="95%">
                            <div>
                                <table width="95%" class="rpt_frame" style="margin-bottom: -5px;">
                                    <tr>
                                        <!-- UPDATED BUSINESS ADDRESS -->
                                        <td width="50%" style="border-color: #ababab;">
                                            <b>Ibn Abdullah Salem Trading SPC</b><br>
                                            [CR: 4000498,  VAT: OM1100371355]<br>
                                            Block No: 257, Way No: 5704, Bousher<br>
                                            PO Box: 967, Postal Code: 130, Al Azaiba<br>
                                            Sultanate of Oman<br>
                                            Phone: 99666760, 99557678,
                                            email: info@astglobal.om
                                        </td>

                                        <?php 
                                            if ($this->billInfo['bill_date']) {
                                                $billDt = DateTime::createFromFormat(DFS_DB, $this->billInfo['bill_date']);
                                                $billDt = $billDt->format(DF_DD);
                                            }
                                        ?>

                                        <td style="border-color: #ababab;">
                                            Invoice No: 
                                            <b>
                                                <?php
                                                    echo $this->billInfo['bill_book_no'] <> ''
                                                        ? $this->billInfo['bill_book_no']
                                                        : $this->billInfo['comp_disp_name']."/" . sprintf("%04s", $this->billInfo['bill_id']);
                                                ?>
                                            </b>
                                        </td>

                                        <td style="border-color: #ababab;" valign="top">
                                            Dated: <b><?= $billDt; ?></b><br>
                                            <?php 
                                                if ($this->billInfo['bill_month']) {
                                                    $billMth = DateTime::createFromFormat(DFS_DB, $this->billInfo['bill_month']);
                                                    $billMth = date_format($billMth, 'F-Y');
                                                    echo "Bill for the month: <b>" . $billMth . "</b>";
                                                }
                                            ?>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td style="border-color: #ababab;">
                                            Buyer<br>
                                            <b><?= $this->billInfo['cust_name']; ?></b><br>
                                            <?= $this->billInfo['con_house']; ?><br>
                                            <?= $this->billInfo['con_street1']; ?><br>
                                            <?= $this->billInfo['con_place']; ?>
                                        </td>

                                        <td style="border-color: #ababab;" valign="top">
                                            Buyer's Order No.: <?= $this->billInfo['bill_refno']; ?>
                                        </td>

                                        <td style="border-color: #ababab;" valign="top" width="25%">
                                            Note:
                                            <span><?= $this->billInfo['bill_remarks']; ?></span>
                                            <?php if ($this->billInfo['bill_cancellation_status']): ?>
                                                <span style="color:red;">CANCELLED</span>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="<?= !$this->billInfo['bill_cancellation_status'] ? 'watermark' : ''; ?>" style="margin-bottom: 1%;">
                <table class="rpt_frame">
                    <thead>
                        <tr>
                            <th colspan="6" class="empty"></th>
                        </tr>
                        <tr style="border-bottom: 2px solid;">
                            <th class="center" width="5%">Sl No</th>
                            <th class="center" width="58%">Description</th>
                            <th class="center" width="8%">Rate (OMR)</th>
                            <th class="center" width="3%">Quantity</th>
                            <th class="center" width="5%">Unit</th>
                            <th class="center" width="8%">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->billDetails as $det): ?>
                            <tr>
                                <td class="center"><?= ++$i; ?></td>
                                <td class="left"><?= $det['item_name']; ?> <?= $det['bdet_remarks'] <> '' ? '-' . $det['bdet_remarks'] : ''; ?></td>
                                <td align="right"><?= $det['bdet_amt']; ?></td>
                                <td align="right"><?= number_format($det['bdet_qty'], 2); ?></td>
                                <td class="left"><?= $det['item_unit']; ?></td>
                                <td align="right">
                                    <?= number_format($det['bdet_qty'] * $det['bdet_amt'], 3); ?>
                                    <?php $grandTotal += $det['bdet_qty'] * $det['bdet_amt']; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>

                        <?php if ($i < 13): for ($j = $i; $j < 13; $j++): ?>
                            <tr>
                                <td class="center">&nbsp;</td>
                                <td class="left">&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                        <?php endfor; endif; ?>

						<?php if(($this->billInfo['bill_vat_amt'])>0):?>
                        <tr>
                            <td></td>
                            <td colspan="4" style="text-align: right;"><b>VAT:</b></td>
                            <td style="text-align: right;"><b><?= number_format($this->billInfo['bill_vat_amt'], 3); ?></b></td>
                        </tr>
                        <?php endif;?>

                        <tr>
                            <td class="center" style="border-top: 2pt solid;"></td>
                            <td colspan="4" style="border-top: 2pt solid; text-align: right;"><b>Total:</b></td>
                            <td style="border-top: 2pt solid; text-align: right;"><b><?= number_format( $grandTotal + ($this->billInfo['bill_vat_amt'] ?? 0), 3); ?></b></td>
                        </tr>
                    </tbody>
                </table>
            </div>


				<div style="margin-top: 1%; margin-bottom: 1%;     bottom: 0;    left: 0;"> 
					<table class="rpt_tbl" style="font-size: 9pt;"> 
						<tr> 
							<td colspan="2" class="left">Amount Chargeable (in words) <br> <b><? 
							 
							$gTotal = explode ( '.', number_format($grandTotal,3));						 
							$gTotal [0]= str_replace( ',', '', $gTotal [0]); 
							$gTotal [1]= str_replace( ',', '', $gTotal [1]); 
							 
							 
							$rial = 'R.O '.translateToWords( (int)$gTotal [0] ) ; 
								 
							if ($gTotal [1] != '' && $gTotal [1] != 0) 
								$baisa = ' And Baisa ' . translateToWords( (int)$gTotal [1] ); 
							echo $rial . $baisa . ' Only'; 
							?></b> 							</td> 
						</tr> 
						 
						 
						<tr> 
							<td colspan="2" class="left" valign="top" style="float: right" align="right"> 
							<i>Declaration: </i><br> We declare that the invoice shows the 
								actual price of the goods/service <br>described and all particulars 
								are true and correct. 
							</td> 
						</tr> 
						 
						 
						<tr> 
						 
							<td valign="top" style="float: right" align="right"> 
							<br> 
							<br> 
							For Ibn Abdullah Salem Trading SPC. <br> 
								Authorised Signatory</td>	 
						 
							<td align="left" valign="top" style="float: left" align="left"> 
							<br> 
							<br>Receiver's signature 
							</td> 
								 
 
						</tr> 
						 
						<tr> 
							<td colspan="2" class="left"><i>Remarks:</i> <br>PAYMENT TERMS: With in 30 
								days Or as per the agreement from the date of invoice submission <br> Cheques should be in 
								favour of <b> IBN ABDULLAH SALEM TRADING SPC.</b> 
									</td> 
						</tr> 
						 
						 
					</table> 
					<table class="rpt_tbl" style="font-size: 9pt;margin-top: 2%; "> 
					<tr> 
							<td>&nbsp;</td> 
					</tr> 
						<tr 
							style="border-bottom: medium none; border-left: medium none; border-right: medium none;"> 
							<td style="border-bottom: medium none; border-left: medium none; border-right: medium none; border-top: 1px solid #ababab;"> 
							</td> 
						</tr>  
											<tr> 
							<td>&nbsp;</td> 
					</tr> 
										<tr> 
							<td>&nbsp;</td> 
					</tr> 
					</table> 
				</div> 

        </div>
    </div>
</div>


<div style="margin-left: 11%;margin-right: auto;width: 40%;"> <i> Time Sheet :</i><p><?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>'<i class="glyphicon glyphicon-file text-info">'.$this->billInfo['file_name'].'</i>',array("param"=>'opener')))?>
</div>
<div style="padding-left: 10%;padding-right: 8%;">
<?php 
    $UPDTYPE = UPD_TYP_INV; $UPDREFID = $this->decBillId;
    viewAction(array('module'=>'erp_manage', 'controller'=>'updates', 'action'=>'updates', 'param'=>array('type'=>$UPDTYPE,'ref'=>$UPDREFID)));
?>
</div>


<script>
function downloadInvoicePDF() {
    const element = document.getElementById("report");

    // Options for html2pdf
    const opt = {
        margin:       0.0,
        filename:     'invoice-' + new Date().toISOString().slice(0,10) + '.pdf',
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true },
        jsPDF:        { unit: 'in', format: 'a4', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save();
}
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>



<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
</script>

<?php function numtowords($num){ 
$decones = array( 
            '01' => "One", 
            '02' => "Two", 
            '03' => "Three", 
            '04' => "Four", 
            '05' => "Five", 
            '06' => "Six", 
            '07' => "Seven", 
            '08' => "Eight", 
            '09' => "Nine", 
            10 => "Ten", 
            11 => "Eleven", 
            12 => "Twelve", 
            13 => "Thirteen", 
            14 => "Fourteen", 
            15 => "Fifteen", 
            16 => "Sixteen", 
            17 => "Seventeen", 
            18 => "Eighteen", 
            19 => "Nineteen" 
            );
$ones = array( 
            0 => " ",
            1 => "One",     
            2 => "Two", 
            3 => "Three", 
            4 => "Four", 
            5 => "Five", 
            6 => "Six", 
            7 => "Seven", 
            8 => "Eight", 
            9 => "Nine", 
            10 => "Ten", 
            11 => "Eleven", 
            12 => "Twelve", 
            13 => "Thirteen", 
            14 => "Fourteen", 
            15 => "Fifteen", 
            16 => "Sixteen", 
            17 => "Seventeen", 
            18 => "Eighteen", 
            19 => "Nineteen" 
            ); 
$tens = array( 
            0 => "",
            2 => "Twenty", 
            3 => "Thirty", 
            4 => "Forty", 
            5 => "Fifty", 
            6 => "Sixty", 
            7 => "Seventy", 
            8 => "Eighty", 
            9 => "Ninety" 
            ); 
$hundreds = array( 
            "Hundred", 
            "Thousand", 
            "Million", 
            "Billion", 
            "Trillion", 
            "Quadrillion" 
            ); //limit t quadrillion 
$num = number_format($num,3,".",","); 
$num_arr = explode(".",$num); 
$wholenum = $num_arr[0]; 
$decnum = $num_arr[1]; 
$whole_arr = array_reverse(explode(",",$wholenum)); 
krsort($whole_arr); 
$rettxt = ""; 

foreach($whole_arr as $key => $i){ 
	
	//$i = (string) $i;
	
    if($i < 20){ 
        $rettxt .= $ones[$i]; 
    }
    elseif($i < 100){ 
    	    	
        $rettxt .= $tens[substr($i,0,2)]; 
        $rettxt .= " ".$ones[substr($i,1,1)]; 
    }
    else{ 
        $rettxt .= $ones[substr($i,0,1)]." ".$hundreds[0]; 
        $rettxt .= " ".$tens[substr($i,1,1)]; 
        $rettxt .= " ".$ones[substr($i,2,1)]; 
    } 
    if($key > 0){ 
        $rettxt .= " ".$hundreds[$key]." "; 
    } 

} 
$rettxt = $rettxt;

if($decnum > 0){ 
    $rettxt .= " and "; 
    if($decnum < 20){ 
        $rettxt .= $decones[$decnum]; 
    }
    elseif($decnum < 100){ 
        $rettxt .= $tens[substr($decnum,0,1)]; 
        $rettxt .= " ".$ones[substr($decnum,1,1)]; 
    }
    else{
    	$rettxt .= $ones[substr($decnum,0,1)]." ".$hundreds[0];
    	$rettxt .= " ".$tens[substr($decnum,1,1)];
    	$rettxt .= " ".$ones[substr($decnum,2,1)];
    }
    $rettxt = $rettxt; 
} 



return $rettxt;} 



    function number_to_word( $num = '' )
    {
        $num    = ( string ) ( ( int ) $num );
       
        if( ( int ) ( $num ) && ctype_digit( $num ) )
        {
            $words  = array( );
           
            $num    = str_replace( array( ',' , ' ' ) , '' , trim( $num ) );
           
            $list1  = array('','one','two','three','four','five','six','seven',
                'eight','nine','ten','eleven','twelve','thirteen','fourteen',
                'fifteen','sixteen','seventeen','eighteen','nineteen');
           
            $list2  = array('','ten','twenty','thirty','forty','fifty','sixty',
                'seventy','eighty','ninety','hundred');
           
            $list3  = array('','thousand','million','billion','trillion',
                'quadrillion','quintillion','sextillion','septillion',
                'octillion','nonillion','decillion','undecillion',
                'duodecillion','tredecillion','quattuordecillion',
                'quindecillion','sexdecillion','septendecillion',
                'octodecillion','novemdecillion','vigintillion');
           
            $num_length = strlen( $num );
            $levels = ( int ) ( ( $num_length + 2 ) / 3 );
            $max_length = $levels * 3;
            $num    = substr( '00'.$num , -$max_length );
            $num_levels = str_split( $num , 3 );
           
            foreach( $num_levels as $num_part )
            {
                $levels--;
                $hundreds   = ( int ) ( $num_part / 100 );
                $hundreds   = ( $hundreds ? ' ' . $list1[$hundreds] . ' Hundred' . ( $hundreds == 1 ? '' : 's' ) . ' ' : '' );
                $tens       = ( int ) ( $num_part % 100 );
                $singles    = '';
               
                if( $tens < 20 )
                {
                    $tens   = ( $tens ? ' ' . $list1[$tens] . ' ' : '' );
                }
                else
                {
                    $tens   = ( int ) ( $tens / 10 );
                    $tens   = ' ' . $list2[$tens] . ' ';
                    $singles    = ( int ) ( $num_part % 10 );
                    $singles    = ' ' . $list1[$singles] . ' ';
                }
                $words[]    = $hundreds . $tens . $singles . ( ( $levels && ( int ) ( $num_part ) ) ? ' ' . $list3[$levels] . ' ' : '' );
            }
           
            $commas = count( $words );
           
            if( $commas > 1 )
            {
                $commas = $commas - 1;
            }
           
            $words  = implode( ', ' , $words );
           
            //Some Finishing Touch
            //Replacing multiples of spaces with one space
            $words  = trim( str_replace( ' ,' , ',' , trim_all( ucwords( $words ) ) ) , ', ' );
            if( $commas )
            {
                $words  = str_replace_last( ',' , ' and' , $words );
            }
           
            return $words;
        }
        else if( ! ( ( int ) $num ) )
        {
            return 'Zero';
        }
        return '';
    }

    function translateToWords($number)
    {
    	/*****
    	 * A recursive function to turn digits into words
    	 * Numbers must be integers from -999,999,999,999 to 999,999,999,999 inclussive.
    	 *
    	 *  (C) 2010 Peter Ajtai
    	 *    This program is free software: you can redistribute it and/or modify
    	 *    it under the terms of the GNU General Public License as published by
    	 *    the Free Software Foundation, either version 3 of the License, or
    	 *    (at your option) any later version.
    	 *
    	 *    This program is distributed in the hope that it will be useful,
    	 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
    	 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    	 *    GNU General Public License for more details.
    	 *
    	 *    See the GNU General Public License: <http://www.gnu.org/licenses/>.
    	 *
    	 */
    	// zero is a special case, it cause problems even with typecasting if we don't deal with it here
    	$max_size = pow(10,18);
    	if (!$number) return "zero";
    	if (is_int($number) && $number < abs($max_size))
    	{
    		switch ($number)
    		{
    			// set up some rules for converting digits to words
    			case $number < 0:
    				$prefix = "negative";
    				$suffix = translateToWords(-1*$number);
    				$string = $prefix . " " . $suffix;
    				break;
    			case 1:
    				$string = "one";
    				break;
    			case 2:
    				$string = "two";
    				break;
    			case 3:
    				$string = "three";
    				break;
    			case 4:
    				$string = "four";
    				break;
    			case 5:
    				$string = "five";
    				break;
    			case 6:
    				$string = "six";
    				break;
    			case 7:
    				$string = "seven";
    				break;
    			case 8:
    				$string = "eight";
    				break;
    			case 9:
    				$string = "nine";
    				break;
    			case 10:
    				$string = "ten";
    				break;
    			case 11:
    				$string = "eleven";
    				break;
    			case 12:
    				$string = "twelve";
    				break;
    			case 13:
    				$string = "thirteen";
    				break;
    				// fourteen handled later
    			case 15:
    				$string = "fifteen";
    				break;
    			case $number < 20:
    				$string = translateToWords($number%10);
    				// eighteen only has one "t"
    				if ($number == 18)
    				{
    					$suffix = "een";
    				} else
    				{
    					$suffix = "teen";
    				}
    				$string .= $suffix;
    				break;
    			case 20:
    				$string = "twenty";
    				break;
    			case 30:
    				$string = "thirty";
    				break;
    			case 40:
    				$string = "forty";
    				break;
    			case 50:
    				$string = "fifty";
    				break;
    			case 60:
    				$string = "sixty";
    				break;
    			case 70:
    				$string = "seventy";
    				break;
    			case 80:
    				$string = "eighty";
    				break;
    			case 90:
    				$string = "ninety";
    				break;
    			case $number < 100:
    				$prefix = translateToWords($number-$number%10);
    				$suffix = translateToWords($number%10);
    				$string = $prefix . " " . $suffix;
    				break;
    				// handles all number 100 to 999
    			case $number < pow(10,3):
    				// floor return a float not an integer
    				$prefix = translateToWords(intval(floor($number/pow(10,2)))) . " hundred";
    				if ($number%pow(10,2)) $suffix = " and " . translateToWords($number%pow(10,2));
    				$string = $prefix . $suffix;
    				break;
    			case $number < pow(10,6):
    				// floor return a float not an integer
    				$prefix = translateToWords(intval(floor($number/pow(10,3)))) . " thousand";
    				if ($number%pow(10,3)) $suffix = translateToWords($number%pow(10,3));
    				$string = $prefix . " " . $suffix;
    				break;
    			case $number < pow(10,9):
    				// floor return a float not an integer
    				$prefix = translateToWords(intval(floor($number/pow(10,6)))) . " million";
    				if ($number%pow(10,6)) $suffix = translateToWords($number%pow(10,6));
    				$string = $prefix . " " . $suffix;
    				break;
    			case $number < pow(10,12):
    				// floor return a float not an integer
    				$prefix = translateToWords(intval(floor($number/pow(10,9)))) . " billion";
    				if ($number%pow(10,9)) $suffix = translateToWords($number%pow(10,9));
    				$string = $prefix . " " . $suffix;
    				break;
    			case $number < pow(10,15):
    				// floor return a float not an integer
    				$prefix = translateToWords(intval(floor($number/pow(10,12)))) . " trillion";
    				if ($number%pow(10,12)) $suffix = translateToWords($number%pow(10,12));
    				$string = $prefix . " " . $suffix;
    				break;
    				// Be careful not to pass default formatted numbers in the quadrillions+ into this function
    				// Default formatting is float and causes errors
    			case $number < pow(10,18):
    				// floor return a float not an integer
    				$prefix = translateToWords(intval(floor($number/pow(10,15)))) . " quadrillion";
    				if ($number%pow(10,15)) $suffix = translateToWords($number%pow(10,15));
    				$string = $prefix . " " . $suffix;
    				break;
    		}
    	} else
    	{
    		echo "ERROR with - $number<br/> Number must be an integer between -" . number_format($max_size, 0, ".", ",") . " and " . number_format($max_size, 0, ".", ",") . " exclussive.";
    	}
    	return ucwords($string);
    }

?>