<div class="dynamic-popup" id="dynamic-popup">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Make Collections</h4>
				<button aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>

		<form name="selectform" method="post" id="filter" action='erp_invoice/collection/add' style="margin-bottom: 0px;">
			<div class="row mb-4" style="padding-top:10px;">
					<div class="col-sm-1"></div>
					<label class="col-sm-2 form-label">Select Vender</label>
					<div class="col-sm-6">
                    <?=$this->form1->f_selCustomer->show()?>
                  </div>
                  <div class="col-sm-2"><button type="button" class="btn btn-primary submit-alias livepost no-confirm" >Show</button></div>
			</div>
		</form>	
			
		<form name="form" method="post" id="edit" action='erp_invoice/collection/add' style="margin-bottom: 0px;" enctype="multipart/form-data">
		<input type="hidden" name="f_selCustomer" value="<?//=$_POST['f_selCustomer'];?>">
		<?=$this->form2->f_selCustomer->show()?>
		<div class="col-md-12 card" style="padding-top: 15px; margin-bottom: 3px;"> 
		<div style="height: 250px;overflow-y: auto">
		<table class="table table-bordered">
			<thead>
				<tr>
				<tr>
					<th width="4%" class="center">Sl No</th>
					<th width="4%" class="center">Pay</th>
					<th width="4%" class="center">Bill No.</th>
					<th width="15%" class="center">Ref</th>
					<th width="5%" class="center">Bill Dt.</th>
					<th width="5%" class="center">Due Dt.</th>
					<th width="5%" class="center">Company</th>
					<th width="35%" class="center">Particulers</th>
					<th width="7%" class="center">Bill Amount</th>
					<th width="7%" class="center">Adjustment</th>
					<th width="7%" class="center">Collection</th>
					<th width="7%" class="center">Balance</th>

				</tr>
			</thead>
			<tbody>
			<?if(is_array($this->billList) && count($this->billList)>0):?>
				<?php foreach(@$this->billList as $i=>$bill):
				//$encExpId = $this->encode($bill['bill_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td align="center"><?=$this->form2->check[$bill['bill_id']]->show()?></td>
					<td><?=$bill['bill_book_no']<>''?$bill['bill_book_no']: "AST/".sprintf("%04s", $bill['bill_id']);?></td>
					<td><?=$bill['bill_refno']?></td>
					<td><?=$bill['bill_billdt']?></td>
					<td><?=$bill['bill_billdt']?></td>
					<td><?=$bill['comp_disp_name']?></td>
					<td><?=$bill['bill_remarks']?></td>
					<td><?=$bill['bill_credit_amt']?></td>
					<td><?=$this->form2->discount[$bill['bill_id']]->show()?></td>
					<td><?=$this->form2->mamount[$bill['bill_id']]->show()?></td>					
					<td>
					<?php if($_POST ['check'] [$bill['bill_id']]!=""):
					 $prdiscount = $_POST ['discount'] [$bill['bill_id']]==''? 0:$_POST ['discount'] [$bill['bill_id']];
                     $pramount = $_POST ['mamount'] [$bill['bill_id']]==''? 0:$_POST ['mamount'] [$bill['bill_id']];
                     ?>
					<?=number_format(($this->billAmount[$bill['bill_id']]-$prdiscount)-$pramount,3)?>	
					<?php endif;?>
					</td>

				</tr>
				<?php endforeach?>
			<?endif?>
			
			<?if(is_array($this->demandList) && count($this->demandList)>0):?>
				<?php foreach(@$this->demandList as $i=>$demand):
				//$encExpId = $this->encode($demand['cdmd_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td align="center"><?=$this->form2->check[$demand['cdmd_id']]->show()?></td>
					<td><?="AMP/".sprintf("%04s", $demand['cdmd_id']);?></td>
					<td><?=$demand['cdmd_note']?></td>
					<td><?=$demand['cdmd_date']?></td>
					<td><?=$demand['cdmd_date']?></td>
					<td><?=$demand['comp_disp_name']?></td>
					<td><?=$demand['cdmd_narration']?></td>
					<td><?=$demand['cdmd_credit_amt']?></td>
					<td><?=$this->form2->discount[$demand['cdmd_id']]->show()?></td>
					<td><?=$this->form2->mamount[$demand['cdmd_id']]->show()?></td>					
					<td>
					<?php if($_POST ['check'] [$demand['cdmd_id']]!=""):?>
					<?=number_format( (floatval($this->billAmount[$demand['cdmd_id']])-floatval($_POST ['discount'] [$demand['cdmd_id']]))-floatval($_POST ['mamount'] [$demand['cdmd_id']]),3)?>
					<?php endif?>
					</td>

				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		</div>
		</div>	
		
		<div class="row mb-4 mt-4" style="margin-right: 0.25rem;">
			<label class="col-sm-1 form-label" style="text-align: right;"> Date</label>
			<div class="col-sm-2">
               <?=$this->form2->payby->show()?>
           </div>
           	<label class="col-sm-1 form-label" style="text-align: right;" >Mode</label>
			<div class="col-sm-2 mt-2">
               <?=$this->form2->paymod->show()?>
           </div>
           
			<label class="col-sm-1 form-label" style="text-align: right;" >Amount</label>
			<div class="col-sm-2">
               <?=$this->form2->amount->show()?>
           </div>
           	<label class="col-sm-1 form-label" style="text-align: right;">Cheque No.</label>
			<div class="col-sm-2">
               <?=$this->form2->chqno->show()?>
           </div>
		</div>
		<div class="row mb-4">
			<label class="col-sm-1 form-label" style="text-align: right;" >Note</label>
			<div class="col-sm-6">
               <?=$this->form2->note->show()?>
           </div>
           
           	<label class="col-sm-1 form-label" style="text-align: right;">Document</label>
			<div class="col-sm-2"> 
               <?=$this->form2->my_files->show()?>
            </div>
           
		</div>
		
		
		<div class="modal-footer">
    		<div class="col-sm-12 row">
            		<div class="col-sm-10">
                		<?if($this->balanceConfirm):?>
                			<div class="form-group">
                			<label class="col-sm-10 form-label" style="text-align: right;">Note: if bill balance not zero, the bill still present in credit bill!!
                			<?=$this->form2->confirm->show()?></label>
                			</div>
                		<?php endif?>
            		</div>
            		<div class="col-sm-2">
            			<button type="button" class="btn btn-primary submit-alias livepost" >Add</button>
            			<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
            		</div>
    		</div>
		</div>
	</form>	
</div>
<script type="text/javascript">  
$(document).ready(function() {
	$('input:checkbox.bill-select').each(function() {
		toggleHeight(this)
	});
});
function toggleHeight(field){
    if($(field).is(":checked")){
		   $(field).closest('tr').addClass('pinkrow');
		   $(field).val("1");
    }
    else{
		  $(field).closest('tr').removeClass('pinkrow');
		  $(field).val("");
    }
}
$(document).on(function() {
	$('input:checkbox.bill-select').each(function() {
		toggleHeight(this)
	});
});
</script>