<?$offset = $this->collectionObj->_voffset;?>
<form method="get" id="filter" name="filter" action="list">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<!-- CONTAINER -->
			<div class="main-container container">
				<!-- PAGE-HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">Payment Collections</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Invoices</li>
						</ol>
					</div>
					<div class="ms-auto pageheader-btn">
						<?=x(array('link'=>'erp_invoice/collection/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')))?>
					</div>
				</div>
				<!-- PAGE-HEADER END -->
				<!-- ROW -->
				<div class="row row-sm">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Filters</h3>
							</div>
							
							
							<div class="card-body">
								<div class="row">
									<div class="col-lg-3">
										<div class="form-group">
											<label for="file_no" class="form-label">Customer</label>
                                            <?=$this->form->f_selCustomer->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label for="name" class="form-label">Type</label>
                                            <?=$this->form->f_type->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Building</label>
                                            <?=$this->form->customer->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label">Projects</label>
                                            <?=$this->form->f_property->show()?>
                                        </div>
									</div>
								</div>
								
								<button class="btn <?=$this->filter_class?> mt-4 mb-0"
									type="submit">Filter</button>
								<input class="btn btn-secondary mt-4 mb-0" name="clear"
									type="submit" value="All"></input>
							</div>
						</div>
					</div>
					<!-- ROW -->
					<div class="">
						<div class="">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Payment Collections</h3>
								</div>
								<div class="card-body">
									<div class="table-responsive export-table">
                                        <table aria-describedby="" class="table table-bordered no-footer">
                                                <thead class="border-top">
                                                  <tr role="row">
					<th width="3%" class="center">Sl No</th>
					<th width="14%" class="center">Customer Name</th>
					<th width="4%" class="center">Date</th>
					<th width="5%" class="center">Amount</th>
					<th width="20%" class="center">Particulares</th>
					<th width="3%" class="center">Edit</th>
					<?php if($_SESSION['user_acl']['erp_invoice/collection/approval']):?>
					<th width="3%" class="center">Approve</th>
					<?php endif;?>
					<th width="3%" class="center">View</th>
					<th width="6%" class="center">File No</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->collectionList)>0):?>
				<?php foreach($this->collectionList as $pay):
					$encPayId = $this->encode($pay['coll_id']);
				?>
				<tr>
					<td class="center"><?=@++$this->offset;?></td>
					<td><?=$pay['cust_name']?>  <?=$pay['cdmd_note'];?></td>
					<td align="center"><?=$pay['coll_date']?></td>
					<td align="right"><b><?=$pay['coll_amount']?></b></td>
					<td><?=$pay['bill_no']?> <?=$pay['cdmd_narr']?></td>
					<td class="center">
					<?php if(empty($pay['coll_app_status'])):?>
						<?=x(array('link'=>'erp_invoice/collection/edit','ref'=>$encPayId,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>  
					<?php endif?>					
					</td>
					<?php if($_SESSION['user_acl']['erp_invoice/collection/approval']):?>
					<td class="center">
<?php if($pay['coll_app_status']==0):?>
					
					<?php if($pay['coll_src_type']==1):?>
					
						<?php if($pay['coll_src_type']==1 && $pay['rev_count'] > 0):?>
							<?=x(array('link'=>'erp_invoice/collection/approval','ref'=>$encPayId,'label'=>'<span class="glyphicon glyphicon-ok-circle" style="color:#31708f;font-size: 1.2em;"> </span>',array("param"=>'class="facebox"')))?>
						<?php else:?>
							<?=x(array('link'=>'erp_invoice/collection/view','ref'=>$encPayId,'label'=>'<i class="fas fa-search"></i>',array("param"=>'class="facebox"')))?> 
						<?php endif?>	
					
					<?php else:?>
						<?=x(array('link'=>'erp_invoice/collection/approval','ref'=>$encPayId,'label'=>'<span class="glyphicon glyphicon-ok-circle" style="color:#31708f;font-size: 1.2em;"> </span>',array("param"=>'class="facebox"')))?>
						
					<?php endif;?>	
					
					
						  
					<?php endif?>
					</td>
					<?php endif;?>					
					<td class="center">
						<?=x(array('link'=>'erp_invoice/collection/view','ref'=>$encPayId,'label'=>'<i class="fas fa-search"></i>',array("param"=>'class="facebox"')))?> 
					</td>
					<td>
					<?php echo $pay['coll_file_no']?>
					</td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?$this->collectionObj->pagination();?>
	</div>
</div></div></div></div></div></div></div></div>
</form>
<?=x(array('link'=>'erp_report/property/paymentcollection','label'=>'
	<div class="col-md-3">
		<div class="card">
				<div class="card-block" style="background-color: ;">
				<div class="card-block">
					<h4 class="card-title center">Payment Collection</h4>
					<p class="card-text">
						<small class="text-muted"></small>
					</p>
				</div>
			</div>
		</div>
	</div>
', array("param"=>'wide_opener')),'<br><br>')?>

<style>
.modal-dialog{
	width: 95%;
}
.pinkrow{
	background-color: pink;
}
</style>

<script type="text/javascript">  
function toggleHeight(field){
    if($(field).is(":checked")){
		   $(field).closest('tr').addClass('pinkrow');
		   $(field).val("1");
    }
    else{
		  $(field).closest('tr').removeClass('pinkrow');
		  $(field).val("");
    }
}
$(document).on(function() {
	$('input:checkbox.bill-select').each(function() {
		toggleHeight(this)
	});
	
});
</script>