<?$offset = $this->updatesObj->_voffset;?>
<form method="get" id="filter" name="filter" action="list">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<!-- CONTAINER -->
			<div class="main-container container">
				<!-- PAGE-HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">Task/ Updates</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Manage
								Task/ Updates</li>
						</ol>
					</div>
				</div>
				<!-- PAGE-HEADER END -->
				<!-- ROW -->
				<div class="row row-sm">
					<div class="">
						<div class="">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Task/ Updates</h3>
								</div>
								<div class="card-body">
									<div class="table-responsive export-table">
                                        <table aria-describedby="" class="table table-bordered no-footer">
                                                <thead class="border-top">
                                                  <tr role="row">
					<th width="3%" class="center">Sl No</th>
					<th width="5%" class="center">Category</th>
					<th width="5%" class="center">Refrence</th>
					<th width="7%" class="center">Reported By</th>
					<th width="10%" class="center">Reported On</th>
					<th width="5%" class="center">Start Date</th>
					<th width="5%" class="center">End Date</th>
					<th width="20%" class="center">Description</th>
					<th width="3%" class="center">Priority</th>
					<th width="3%" class="center">Status</th>
					<th width="3%" class="center">Update</th>
				</tr>
			</thead>
			<tbody>
			<?if(count( $this->updateList)>0):?>
				<?php foreach( $this->updateList as $update):
					$encupdateId = $this->encode($update['upd_id']);
					$encRefId = $this->encode($update['upd_type_refid']);
					
					$link[1] = 'erp_employee/master/view';
					$link[2] = 'erp_projects/master/view';
					$link[3] = 'erp_vehicle/master/view';
					$link[4] = 'erp_invoice/bill/view';
					$link[5] = 'erp_manage/company/list';
					
				?>
				<tr>
					<td class="center"><?=@++ $this->offset;?></td>
					<td><?=$update['txt_type']?> </td>
					<td><?=x(array('link'=> $link[$update['upd_type']] .'','ref'=>$encRefId,'label'=>$update['ref_name']))?></td>
					
					<td><?=$update['user_name']?></td>
					<td align="center"><?=$update['dt_created']?></td>
					<td align="center"><?=$update['upd_dttime']?></td>
					<td align="center"><?=$update['upd_enddttime']?></td>
					<td><?=$update['upd_note']?></td>
					<td align="center"><?=$update['upd_priority']?></td>
					<td align="center"><?=$update['upd_status_label']?></td>
					<td class="center">
					<?php if($update['upd_status']==1):?>
						<?=x(array('link'=>'erp_manage/updates/status','ref'=>$encupdateId,'label'=>'<i class="glyphicon glyphicon-hand-right text-info"></i>',array("param"=>'class="facebox"')))?>
					<?php else:?>
						<i class="glyphicon glyphicon-ok"></i>
					<?php endif?>	 
					</td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<? $this->updatesObj->pagination();?>
	</div>
</div></div></div></div></div></div></div></div>
</form>