<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" id="edit" action='erp_expense/payments/approval/ref/<?=$this->param['ref'];?>' style="margin-bottom: 0px;">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Approve Payment</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			
		<div class="modal-body">	
	
		<div class="col-md-12 card" style="padding-top: 15px; margin-bottom: 3px;"> 
		<div style="height: 250px;overflow-y: auto">
		<table class="table table-bordered">
			<thead>
				<tr>
				<tr>
					<th width="4%" class="center">Sl No</th>
					<th width="12%" class="center">Ref No</th>
					<th width="5%" class="center">Bill Dt.</th>
					<th width="9%" class="center">File No.</th>
					<th width="5%" class="center">Company</th>
					<th width="6%" class="center">Main Head</th>
					<th width="32%" class="center">Particulers</th>
					<th width="7%" class="center">Bill Amount</th>
					<th width="7%" class="center">Discount</th>
					<th width="7%" class="center">Payment</th>
					<th width="7%" class="center">Balance</th>

				</tr>
			</thead>
			<tbody>
			<?if(count($this->paymentList)>0):?>
				<?php foreach(@$this->paymentList as $i=>$expense):
				$encFileId = $this->encode($expense['file_id']);
				//$encExpId = $this->encode($expense['exp_id']);
				//s($expense);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$expense['exp_refno']?></td>
					<td><?=$expense['exp_billdt']?></td>
					<td><?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>$expense['exp_file_no'],array("param"=>'opener')))?></td>
					<td><?=$expense['comp_disp_name']?></td>
					<td><?=$expense['main_head']?></td>
					<td><?=$expense['exp_details']?></td>
					<td><?=$expense['pdet_amt_topay']?></td>
					<td><?=$expense['pdet_amt_dis']?></td>
					<td><?=$expense['pdet_amt_paid']?></td>	
					<td><?=number_format($expense['pdet_amt_topay'] - ($expense['pdet_amt_dis']+$expense['pdet_amt_paid']),3)?></td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		</div>
		</div>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th width="20%" class="center">Payment Date</th>
					<th width="20%" class="center">Mode</th>
					<th width="20%" class="center">Cheque Details</th>
					<th width="20%" class="center">Note</th>
					<th width="20%" class="center">Total Amount</th>
				</tr>
			</thead>
			<thead>
				<tr>
					<th width="20%" class="center"><?=$this->payDet['pay_paydate_dd']?></th>
					<th width="20%" class="center"><?=$this->payDet['pay_pay_mode']?></th>
					<th width="20%" class="center"><?=$this->payDet['pay_chqno']?></th>
					<th width="20%" class="center"><?=$this->payDet['pay_remarks']?></th>
					<th width="20%" class="center"><?=$this->payDet['pay_amount']?></th>
				</tr>
			</thead>
			</table>
		
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-3 form-label" >Status</label>
					<div class="col-sm-9">
                    <?=$this->form->status->show()?>
                  </div>
				</div>
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-3 form-label" >Note</label>
					<div class="col-sm-9">
                    <?=$this->form->note->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Approve</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>