<?$offset = $this->buildingObj->_voffset;?>
<form method="get" id="filter" name="filter" action="list">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<!-- CONTAINER -->
			<div class="main-container container">
				<!-- PAGE-HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">List of Payments</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Manage
								Payments</li>
						</ol>
					</div>
					<div class="ms-auto pageheader-btn">
		<?=x(array('link'=>'erp_expense/payments/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')))?>
					</div>
				</div>
				<!-- PAGE-HEADER END -->
				<!-- ROW -->
				<div class="row row-sm">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Filters</h3>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-6">
										<div class="form-group">
											<label for="file_no" class="form-label">Vendor</label>
                                            <?=$this->form->f_selVendor->show()?>
                                        </div>
									</div>
								</div>
								<button class="btn <?=$this->filter_class?> mt-4 mb-0"
									type="submit">Filter</button>
								<input class="btn btn-secondary mt-4 mb-0" name="clear"
									type="submit" value="All"></input>
							</div>
						</div>
					</div>
					<div class="">
						<div class="">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Properties</h3>
								</div>
								<div class="card-body">
									<div class="table-responsive export-table">
                                        <table aria-describedby="" class="table table-bordered no-footer">
                                                <thead class="border-top">
                                                  <tr role="row">
					<th width="5%" class="center">Sl No</th>
					<th width="20%" class="center">Vendor Name</th>
					<th width="6%" class="center">Date</th>
					<th width="8%" class="center">Amount</th>
					<th width="6%" class="center">Edit</th>
					<?php if($_SESSION['user_acl']['erp_expense/payments/approval']):?>
					<th width="6%" class="center">Approve</th>
					<?php endif;?>
					<th width="6%" class="center">Voucher</th>
					<th width="6%" class="center">View</th>
					<th width="6%" class="center">File No</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->paymentList)>0):?>
				<?php foreach($this->paymentList as $pay):
					$encPayId = $this->encode($pay['pay_id']);
				?>
				<tr>
					<td class="center"><?=@++$this->offset;?></td>
					<td><?=$pay['ven_name']?></td>
					<td align="center"><?=$pay['pay_date']?></td>
					<td align="right" onclick="togglenext(this);" style="cursor: pointer;"><b><?=$pay['pay_amount']?></b></td>
					<td class="center">
					
					
					<?php if(empty($pay['pay_app_status'])):?>
						<?=x(array('link'=>'erp_expense/payments/edit','ref'=>$encPayId,'label'=>'<i class="fas fa-edit" title="Edit"></i>',array("param"=>'class="facebox"')))?>
						<?=x(array('link'=>'erp_expense/payments/remittance','ref'=>$encPayId,'label'=>'<i class="glyphicon glyphicon glyphicon-print text-info" style="margin-left: 15px;" title="Remittance Advice"></i>',array("param"=>'opener')))?>  
					<?php endif?>					
					
					</td>
					<?php if($_SESSION['user_acl']['erp_expense/payments/approval']):?>
					<td class="center">
					<?php if($pay['pay_app_status']==0):?>
						<?=x(array('link'=>'erp_expense/payments/approval','ref'=>$encPayId,'label'=>'<span class="glyphicon glyphicon-ok-circle" style="color:#31708f;font-size: 1.2em;" title="Approve"> </span>',array("param"=>'class="facebox"')))?>  
					<?php endif?>
					</td>
					<?php endif;?>
					
					<td class="center">
					<?php if($pay['pay_pay_status']==2):?>
						<i class="glyphicon glyphicon-check text-info"></i>
					<?php elseif($pay['pay_pay_status']==1):?>
						<?=x(array('link'=>'erp_expense/payments/close','ref'=>$encPayId,'label'=>'<i class="glyphicon glyphicon-info-sign text-info" title="File and Close Payment Transaction"></i>',array("param"=>'class="facebox"')))?>
					
					<?php elseif($pay['pay_app_status']==1):?>
						<?=x(array('link'=>'erp_expense/payments/voucher','ref'=>$encPayId,'label'=>'<i class="glyphicon glyphicon-info-sign" style="color: red;" title="Upload Voucher" ></i>',array("param"=>'class="facebox"')))?>
					<?php endif?>
					</td>
					
					<td class="center">
						<?=x(array('link'=>'erp_expense/payments/view','ref'=>$encPayId,'label'=>'<i class="fas fa-search"></i>',array("param"=>'class="facebox"')))?> 
					</td>
					<td>
						<?=x(array('link'=>'erp_expense/payments/editoption','ref'=>$encPayId,'label'=>$pay['pay_file_no'] ,array("param"=>'class="facebox"')))?>  
					</td>
				</tr>
				<tr style="display:none;">
				<td></td>
				<td colspan="8" style="padding: 16px !important;"><b class=""><?=$pay['bill_det']?></b></td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?$this->paymentObj->pagination();?>
	</div>
</div></div></div></div></div></div></div></div>
</form>
<style>
.modal-dialog{
	width: 95%;
}
.pinkrow{
	background-color: pink;
}
</style>

<script type="text/javascript">  
function toggleHeight(field){
    if($(field).is(":checked")){
		   $(field).closest('tr').addClass('pinkrow');
		   $(field).val("1");
    }
    else{
		  $(field).closest('tr').removeClass('pinkrow');
		  $(field).val("");
    }
}
$(document).on(function() {
	$('input:checkbox.bill-select').each(function() {
		toggleHeight(this)
	});
	
});

function togglenext(el){
	if($(el).closest('tr').next('tr').css('display') == 'table-row')
		$(el).closest('tr').next('tr').css('display','none');
	else
		$(el).closest('tr').next('tr').css('display','table-row');
}


</script>