<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
				<h5 class="title-margin">Remittance Voucher</h5>
	</div>
	</div>
<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
								<tr>
									<th width="1%" rowspan="4">
										<div class="title-margin">
											<img width="50" alt=""
												src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
												style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
										</div>
									</th>
								</tr>
								<tr>
									<th><div class="center" style="width: 79%;">ABDULLAH BIN SALEM TRADING EST.</div></th>
								</tr>
								<tr>
									<th width="">
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%; font-family: f11; font-size:9pt;">
											<b> مؤسسة عبدالله بن سالم للتجارة </b>
										</div>

									</th>
								</tr>
								<tr>
									<th>
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%;">Remittance Advice</div>
									</th>
								</tr>
							</thead>
						</table>
					</div>
					<table class="rpt_frame">
			<thead>
				<tr>
					<td class="empty" colspan="7" style="border: 1px solid white;">
					VENDOR NAME: <b><?=$this->payDet['ven_name']?> </b>
					</td>
					<td class="empty" colspan="2" style="border: 1px solid white;">
					<?php $date = new DateTime();$date = $date->format('d/m/Y')?>
					Date : <b><?=$date;?></b></td>
				</tr>
				<tr>
					<th class="empty" colspan="9"></th>
				</tr>
				<tr>
					<th width="4%" class="center">Sl No</th>
					<th width="15%" class="center">Our Ref.</th>
					<th width="15%" class="center">Your Ref.</th>
					<th width="5%" class="center">Bill Dt.</th>
					<th width="35%" class="center">Particulers</th>
					<th width="7%" class="center">To Pay</th>
					<th width="7%" class="center">Discount</th>
					<th width="7%" class="center">Payment</th>
					<th width="7%" class="center">Balance</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->paymentList )>0):?>
				<?php foreach($this->paymentList as $pay):
				$topay  = $pay['exp_credit_amt'];
				$balance = $topay-($pay['pdet_amt_paid']+$pay['pdet_amt_dis']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$pay['exp_file_no']?></td>
					<td><?=$pay['exp_refno']?></td>
					<td><?=$pay['exp_billdt']?></td>
					<td><?=$pay['exp_details']?></td>
					<td align="right"><?=number_format($topay,3);?> <?php $totalTopay+=$topay;?></td>
					<td align="right"><?=$pay['pdet_amt_dis']?>   <?php $discount+=$pay['pdet_amt_dis'];?></td>
					<td align="right"><?=$pay['pdet_amt_paid']?>  <?php $paid+=$pay['pdet_amt_paid'];?></td>	
					<td align="right"><?=number_format($balance,3);?> <?php $totBalance+=$balance;?></td>	
				</tr>
				<?php endforeach?>
				<tr><td colspan="5" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($totalTopay,3)?></b></td>
					<td align="right"> <b><?=number_format($discount,3)?></b></td>
					<td align="right"> <b><?=number_format($paid,3)?></b></td>
					<td align="right"> <b><?=number_format($totBalance,3)?></b></td>
				</tr>
			<?endif?>
			
				<tr>
					<td class="empty" colspan="9" style="border: 1px solid white;"></td>
				</tr>
				<tr>
					<td class="empty" colspan="9" style="border: 1px solid white;"></td>
				</tr>
				
				<tr>
					<td class="empty" colspan="9" style="border: 1px solid white;"></td>
				</tr>
				<tr>
					<td class="empty" colspan="9" style="border: 1px solid white;"></td>
				</tr>
			
			<tr>
					<td class="empty" style="border: 1px solid white;">
					</td>
					<td class="empty" colspan="4" style="border: 1px solid white;">
					Verified By: 
					</td>
					<td class="empty" colspan="4" style="border: 1px solid white;">
					
					Approved By : </td>
			</tr>
			
				<tr>
					<td class="empty" colspan="9" style="border: 1px solid white;"></td>
				</tr>
				<tr>
					<td class="empty" colspan="9" style="border: 1px solid white;"></td>
				</tr>
				
								<tr>
					<td class="empty" colspan="9" style="border: 1px solid white;"></td>
				</tr>
				<tr>
					<td class="empty" colspan="9" style="border: 1px solid white;"></td>
				</tr>
			
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>CreativeSol MIS - Remittance Advice (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</form>
</div>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
</script>


