<div class="dynamic-popup" id="dynamic-popup">
	<form name="docform" method="post" id="docform" action="erp_expense/payments/voucher/ref/<?=$this->param['ref'];?>"style="margin-bottom: 0px;" enctype="multipart/form-data">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Payment Details : Voucher Update</h4>
				<button aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
	<div class="modal-body">
		<div class="col-md-12 card" style="padding-top: 15px; margin-bottom: 3px;"> 
		<div style="height: 250px;overflow-y: auto">
		<table class="table table-bordered">
			<thead>
				<tr>
				<tr>
					<th width="4%" class="center">Sl No</th>
					<th width="15%" class="center">Ref No</th>
					<th width="5%" class="center">Bill Dt.</th>
					<th width="5%" class="center">Due Dt.</th>
					<th width="5%" class="center">Company</th>
					<th width="6%" class="center">Main Head</th>
					<th width="35%" class="center">Particulers</th>
					<th width="7%" class="center">Bill Amount</th>
					<th width="7%" class="center">Discount</th>
					<th width="7%" class="center">Payment</th>
					<th width="7%" class="center">Balance</th>

				</tr>
			</thead>
			<tbody>
			<?if(count($this->paymentList)>0):?>
				<?php foreach(@$this->paymentList as $i=>$expense):
				//$encExpId = $this->encode($expense['exp_id']);
				//s($expense);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$expense['exp_refno']?></td>
					<td><?=$expense['exp_billdt']?></td>
					<td><?=$expense['exp_billdt']?></td>
					<td><?=$expense['comp_disp_name']?></td>
					<td><?=$expense['main_head']?></td>
					<td><?=$expense['exp_details']?></td>
					<td><?=$expense['pdet_amt_topay']?></td>
					<td><?=$expense['pdet_amt_dis']?></td>
					<td><?=$expense['pdet_amt_paid']?></td>	
					<td><?=$expense['pdet_amt_bal']?></td>	
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		</div>
		</div>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th width="20%" class="center">Payment Date</th>
					<th width="20%" class="center">Mode</th>
					<th width="20%" class="center">Cheque Details</th>
					<th width="20%" class="center">Note</th>
					<th width="20%" class="center">Total Amount</th>
				</tr>
			</thead>
			<thead>
				<tr>
					<th width="20%" class="center"><?=$this->payDet['pay_paydate_dd']?></th>
					<th width="20%" class="center"><?=$this->payDet['pay_pay_mode']==1?'Cash':'Credit';?></th>
					<th width="20%" class="center"><?=$this->payDet['pay_chqno']?></th>
					<th width="20%" class="center"><?=$this->payDet['pay_remarks']?></th>
					<th width="20%" class="center"><?=$this->payDet['pay_amount']?></th>
				</tr>
			</thead>
			</table>
		
		<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-3 form-label" >Date</label>
					<div class="col-sm-2">
                    <?=$this->form->paydate->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Note</label>
					<div class="col-sm-9">
                    <?=$this->form->note->show()?>
                  </div>
                 </div>
            
                 <?php if($this->payDet['file_id']):
				$encFileId = $this->encode($this->payDet['file_id']);
				?>
				<div class="row mb-4">
				<label class="col-sm-3 form-label" >Uploaded Document</label>    
					<div class="col-sm-3">
				<?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>'<i class="glyphicon glyphicon-file text-info">'.$this->payDet['file_name'].'</i>',array("exten"=>$this->payDet['file_exten'])))?>
                   </div>
                 </div>
				<?php endif?>

                 
                  <div class="row mb-4">
					<label class="col-sm-3 form-label" >Document</label>
					<div class="col-sm-9"> 
                    <?=$this->form->my_files->show()?>
                  </div>
				</div>
				
	</div>
	<div class="modal-footer">
		<div class="row mb-4">
			<div class="col-md-12">
			<button type="button" class="btn btn-primary submit-alias livepost" >Update</button>
			<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
		</div>
		</div>
	</div>
</form>	
</div>
