<form method="get" id="filter" name="filter" action="list">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<div class="main-container container">

				<!-- PAGE HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">Projects</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active">Manage Projects</li>
						</ol>
					</div>
					<div class="ms-auto pageheader-btn">
                    <?=x(['link' => 'erp_projects/master/add','label' => '<button class="btn btn-success btn-icon text-white me-2">
                                            Add Project <i class="fe fe-plus"></i>
                                        </button>',['param' => 'class="facebox"']], '<br><br>')?>
                </div>
				</div>
				<!-- PAGE HEADER END -->

				<!-- FILTERS -->
				<div class="row row-sm">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Filters</h3>
							</div>
							<div class="card-body">
								<div class="row">

									<div class="col-lg-3">
										<label class="form-label">File No</label>
            <?= $this->form->f_fileno->show() ?>
        </div>

									<div class="col-lg-3">
										<label class="form-label">Project Code</label>
            <?= $this->form->f_propno->show() ?>
        </div>

									<div class="col-lg-3">
										<label class="form-label">Customer</label>
            <?= $this->form->f_customer->show() ?>
        </div>

									<div class="col-lg-3">
										<label class="form-label">Category</label>
            <?= $this->form->f_prop_cat->show() ?>
        </div>

									<div class="col-lg-3 mt-3">
										<label class="form-label">Status</label>
            <?= $this->form->f_prop_status->show() ?>
        </div>

									<div class="col-lg-3 mt-3">
										<label class="form-label">Filter</label>

										<button class="btn <?= $this->filter_class ?> " type="submit">
											Filter</button>
										<input class="btn btn-secondary " name="clear" type="submit"
											value="All">
									</div>
								</div>


							</div>

						</div>
					</div>

					<!-- LIST -->
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Projects</h3>
							</div>
							<div class="card-body">
								<div class="table-responsive">

									<table class="table table-bordered text-nowrap">
										<thead>
											<tr>
												<th width="5%">Sl</th>
												<th width="10%">File No</th>
												<th width="10%">Project Code</th>
												<th width="20%">Project Name</th>
												<th width="15%">Customer</th>
												<th width="10%">Category</th>
												<th width="10%">Status</th>
												<th width="5%">Edit</th>
												<th width="5%">View</th>
											</tr>
										</thead>
										<tbody>

                                    <?php if (count($this->projectList) > 0): ?>
                                        <?php

foreach ($this->projectList as $project) :
                                            $encId = $this->encode($project['project_id']);
                                            ?>
                                        <tr>
												<td><?=++$this->offset?></td>

												<td><?=$project['project_fileno']?></td>

												<td><?=$project['project_code']?></td>

												<td><?=$project['project_name']?></td>

												<td><?=$project['cust_name']?></td>

												<td class="center">
                                                <?php
                                            echo match ($project['project_category']) {
                                                1 => 'Road',
                                                2 => 'Bridge',
                                                3 => 'Drainage',
                                                4 => 'Utilities',
                                                default => 'Other'
                                            };
                                            ?>
                                            </td>

												<td class="center">
                                                <?=$project['project_status_label']?>
                                            </td>

												<td class="center">
                                                <?=x(['link' => 'erp_projects/master/edit','ref' => $encId,'label' => '<i class="fas fa-edit"></i>',['param' => 'class="facebox"']])?>
                                            </td>

												<td class="center">
                                                <?=x(['link' => 'erp_projects/master/view','ref' => $encId,'label' => '<i class="fas fa-search"></i>'])?>
                                            </td>
											</tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>

                                    </tbody>
									</table>

                                <?php $this->projectObj->pagination(); ?>

                            </div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</form>
