<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" id="edit"
		  action="<?=APPURL?>users/edit/ref/<?=$ref?>"
		  style="margin-bottom: 0px;">

		<div class="modal-header">
			<h4 class="card-title">Project Contract / Document Details</h4>
			<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
				<span aria-hidden="true">×</span>
			</button>
		</div>

		<div class="modal-body">

			<div class="row mb-4">
				<label class="col-sm-3 form-label">Document Type</label>
				<div class="col-sm-3">
					<?=$this->docMst[$this->documatesDetail['doc_type']]?>
				</div>

				<label class="col-sm-3 form-label">Contract / Document No</label>
				<div class="col-sm-3">
					<?=$this->documatesDetail['doc_no']?>
				</div>
			</div>

			<div class="row mb-4">
				<label class="col-sm-3 form-label">Document Description</label>
				<div class="col-sm-3">
					<?=$this->documatesDetail['doc_desc']?>
				</div>

				<label class="col-sm-3 form-label">Contract Value</label>
				<div class="col-sm-3">
					<?=$this->documatesDetail['agr_amount']?>
				</div>
			</div>

			<div class="row mb-4">
				<label class="col-sm-3 form-label">Advance / Stage Amount</label>
				<div class="col-sm-3">
					<?=$this->documatesDetail['agr_rent']?>
				</div>

				<label class="col-sm-3 form-label">Remarks</label>
				<div class="col-sm-3">
					<?=$this->documatesDetail['doc_remarks']?>
				</div>
			</div>

			<div class="row mb-4">
				<label class="col-sm-3 form-label">Contracted / Issued By</label>
				<div class="col-sm-3">
					<?=$this->documatesDetail['doc_issue_auth']?>
				</div>

				<label class="col-sm-3 form-label">Contract Date</label>
				<div class="col-sm-3">
					<?=$this->doa?>
				</div>
			</div>

			<div class="row mb-4">
				<label class="col-sm-3 form-label">Contract Start Date</label>
				<div class="col-sm-3">
					<?=$this->doi?>
				</div>

				<label class="col-sm-3 form-label">Contract End Date</label>
				<div class="col-sm-3">
					<?=$this->doe?>
				</div>
			</div>

			<div class="row mb-4">
				<label class="col-sm-3 form-label">Alert / Reminder Days</label>
				<div class="col-sm-3">
					<?=$this->documatesDetail['doc_alert_days']?>
				</div>

				<label class="col-sm-3 form-label">Download Document</label>
				<div class="col-sm-3">
					<?=x([
						'link'=>'default/default/download',
						'ref'=>$this->encFileId,
						'label'=>'<i class="glyphicon glyphicon-download-alt text-info"></i>',
						['param'=>'opener']
					])?>
				</div>
			</div>

		</div>

		<div class="modal-footer">
			<button type="button" class="btn btn-light" data-bs-dismiss="modal">
				Close
			</button>
		</div>

	</form>
</div>

<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '60%');
});
</script>
