<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_fund/cashbook/add' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true">×</span></button>
		<h4 class="modal-title">Personnel Cash Book Debit Details</h4>
	</div>
	<div class="modal-body">
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-2 form-label" >Date</label>
					<div class="col-sm-4">
                    <?=$this->form->debitdt->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Debit Amount</label>
					<div class="col-sm-4">
                    <?=$this->form->amount->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Note</label>
					<div class="col-sm-10">
                    <?=$this->form->note->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Add</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<style>
.modal-dialog{
	width: 60%;
}
</style>
