<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">Report: Outstanding Statement</h5>
	</div>
		<!--  <table class="">
			<tr style="font-size: 0.8em;">
				<th width="15%">Company</th>
				<th width="15%">Department</th>
				<th width="15%">Designation</th>
				<th width="15%">Nationality</th>
				<th width="15%"></th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?//=$form->f_company->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?//=$form->f_dept->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?//=$form->f_desig->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?//=$form->f_natonality->show()?>
              		</div>
				</td>
				<td width="15%" align="center">
	              <div class="form-group ">
					<button class="btn <?//=$filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>-->
	</div>

<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">

<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
								<tr>
									<th width="1%" rowspan="4">
										<div class="title-margin">
											<img width="50" alt=""
												src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
												style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
										</div>
									</th>
								</tr>
								<tr>
									<th><div class="center" style="width: 79%;">ABDULLAH BIN SALEM TRADING EST.</div></th>
								</tr>
								<tr>
									<th width="">
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%; font-family: f11; font-size:9pt;">
											<b> مؤسسة عبدالله بن سالم للتجارة </b>
										</div>

									</th>
								</tr>
								<tr>
									<th>
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%;">Outstanding
											Statement</div>
									</th>
								</tr>
							</thead>
						</table>
					</div>
		<?php $date = new DateTime();
		$date = $date->format('d/m/Y')?>				
		<table class="rpt_frame">
			<thead>
				<tr>
					<td class="empty" colspan="9" style="border: 1px solid white;">
					Customer Name &nbsp;&nbsp;:&nbsp;<?=$this->billList[0]['cust_name']?> <br>
					Phone No.&nbsp;:&nbsp;<?=$this->billList[0]['con_phone']?><br>
					Mobile No.&nbsp;:&nbsp;<?=$this->billList[0]['con_mobile']?></td>
					<td class="empty" style="border: 1px solid white;">Date : <?=$date;?></td>
				</tr>
				<tr>
					<th class="empty" colspan="10"></th>
				</tr>
				<tr>
					<th width="2%" class="center">Sl No</th>
					<th width="3%" class="center">Bill No</th>
					<th width="4%" class="center">Ref No</th>
					<th width="3%" class="center">Bill Date</th>
					<th width="3%" class="center">Bill Submission</th>
					<th width="3%" class="center">Due Date</th>
					<th width="8%" class="center">Notes</th>
					<th width="5%" class="center">Work Period</th>
					<th width="3%" class="center">Bill Amount</th>
					<th width="3%" class="center">Credit Amount</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->billList)>0):?>
			
				<?php 
				foreach($this->billList as $bill):
				$encBillId= $this->encode($bill['bill_id']);?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=x(array('link'=>'erp_invoice/bill/miniview','ref'=>$encBillId,'label'=>$bill['bill_book_no']<>''?$bill['bill_book_no']." (".$bill['comp_disp_name']."/".sprintf("%04s", $bill['bill_id']).")": $bill['comp_disp_name']."/".sprintf("%04s", $bill['bill_id']),array("param"=>'class="facebox"')))?> </td>
					<td><?=$bill['bill_refno']?></td>
					<td class="center"><?=$bill['bill_disp_date']?></td>
					<td class="center"><?=$bill['rev_date']?></td>
					<td class="center"><?=$bill['bill_due_date']?></td>
					<td class="center"><?=$bill['bill_remarks']?></td>
					<td><?=$bill['bill_month']?></td>
					<td align="right"><?=number_format($bill['bill_total'],3)?></td>	
					<td align="right"><?=number_format($bill['bill_credit_amt'],3)?></td>													
				</tr>
				<?php $grndTotal+=$bill['bill_credit_amt'];
				$due += $bill['due_amount'];
				$due15 += $bill['due_amount_15'];
				$due30 += $bill['due_amount_30'];
				$due45 += $bill['due_amount_45'];
				$due60 += $bill['due_amount_60'];
				$due90 += $bill['due_amount_90'];
				$due120 += $bill['due_amount_120'];
				endforeach?>
				<tr>
					<th class="empty" colspan="10"></th>
				</tr>
				<tr>
					<th style="text-align: right;" colspan="9"> Total :</th>		
					<th style="text-align: right;" ><?=number_format(@$grndTotal,3);?></th>													
				</tr>
							</tbody>
		</table>
		<?php if($due):?>
		<table class="rpt_frame">
			<thead>
				<tr>
					<th width="15%"class="center">Aging:</th>	
					<th width="12%"> <?= $due>0? 'Due:'.number_format($due,3):'';?></th>
					<th width="12%"> <?= $due15>0? 'More 15 days:'.number_format($due15,3):'';?></th>
					<th width="13%"> <?= $due30>0? 'More 30 days:'.number_format($due30,3):'';?></th>
					<th width="12%"><?php if($due45>0):?>
					<div style="background:#7FFFD4"><?= 'More 45 days:'.number_format($due45,3);?> </div>
					<?php endif?></th>	
					<th width="12%"><?php if($due60>0):?>
					<div style="background:#FFFF00"><?= 'More 60 days:'.number_format($due60,3);?> </div>
					<?php endif?></th>	
					<th width="12%"><?php if($due90>0):?>
					<div style="background:#FFA07A"><?= 'More 90 days:'.number_format($due90,3);?> </div>
					<?php endif?></th>	
					<th width="12%"><?php if($due120>0):?>
					<div style="background:#FF6347"><?= 'More 120 days:'.number_format($due120,3);?> </div>
					<?php endif?></th>				
				</tr>
			<?endif?>
			</tbody>
		</table>
		<?php endif?>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr>
						<td><div class="title-margin rpt_footer"> </small></div></td>
					</tr>
					<tr><?php $date = new DateTime();
										$date = $date->format('d/m/Y H:i:s')?> 
						<td><div class="title-margin rpt_footer"> <small> <br> Report Generated On : <?=$date?> </small></div></td>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</form>
</div>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
$(document).ready(function() {
	var source = '<?=APPURL?>'+ 'erp_expense/expense/getlive';
	$('#f_pCatSelect').on('change',function() {
		getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');
		$('#f_cCatSelect').empty();
	});
	getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');

	$('#f_sCatSelect').on('change',function() {
		getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
	});
	getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
});
</script>

