<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">Report: Outstanding Statement</h5>
	</div>
		<!--  <table class="">
			<tr style="font-size: 0.8em;">
				<th width="15%">Company</th>
				<th width="15%">Department</th>
				<th width="15%">Designation</th>
				<th width="15%">Nationality</th>
				<th width="15%"></th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?//=$form->f_company->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?//=$form->f_dept->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?//=$form->f_desig->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?//=$form->f_natonality->show()?>
              		</div>
				</td>
				<td width="15%" align="center">
	              <div class="form-group ">
					<button class="btn <?//=$filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>-->
	</div>

<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
								<tr>
									<th width="1%" rowspan="4">
										<div class="title-margin">
											<img width="50" alt=""
												src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
												style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
										</div>
									</th>
								</tr>
								<tr>
									<th><div class="center" style="width: 79%;">ABDULLAH BIN SALEM TRADING EST.</div></th>
								</tr>
								<tr>
									<th width="">
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%; font-family: f11; font-size:9pt;">
											<b> مؤسسة عبدالله بن سالم للتجارة </b>
										</div>

									</th>
								</tr>
								<tr>
									<th>
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%;">Outstanding
											Statement</div>
									</th>
								</tr>
							</thead>
						</table>
					</div>
					<table class="rpt_frame">
			<thead>
				<tr>
					<th class="empty" colspan="10"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="25%" class="center">Customer Name</th>
					<th width="8%" class="center">Phone No.</th>
					<th width="8%" class="center">Mobile No.</th>
					<th width="22%" class="center">Invoice Period</th>
					<th width="12%" class="center">Amount Outstanding</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->billList)>0):?>
				<?php foreach($this->billList as $bill):
				$encCustId = $this->encode($bill['cust_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=x(array('link'=>'erp_report/invoice/billcustoutstanding','ref'=>$encCustId,'label'=>$bill['cust_name'],array("param"=>'')))?>
					</td>
					<td align="center"><?=$bill['con_phone']?></td>
					<td align="center"><?=$bill['con_mobile']?></td>
					<td align="center"><?=$bill['dmin']?> -- <?=$bill['dmax']?> </td>
					<td align="right"><?=number_format($bill['credit_amt'],3); $total+=$bill['credit_amt'];?></td>

				</tr>
				<?php endforeach?>
				<tr><td colspan="5" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($total,3)?></b></td>
				</tr>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</form>
</div>



