<div class="main-content mt-0 hor-content">
	<div class="side-app">
		<!-- CONTAINER -->
		<div class="main-container container">
			<!-- PAGE-HEADER -->
			<div class="page-header">
				<div>
					<h1 class="page-title">Employee Salary</h1>
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
						</li>
						<li class="breadcrumb-item active" aria-current="page">Manage Employee Salary</li>
					</ol>
				</div>
			</div>

<form method="get" id="filter" name="filter" action="list">
				<div class="row row-sm">
					<div class="">
						<div class="">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Employee Salary</h3>
								</div>
								<div class="card-body">
									<div class="table-responsive export-table">
										<table id="file-datatable"
											class="table table-bordered text-nowrap key-buttons border-bottom w-100">
											<thead>
												<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="9%" class="center">Year</th>
					<th width="15%" class="center">Month</th>
					<th width="8%" class="center">No of Emp</th>
					<th width="10%" class="center">Additional Pay</th>
					<th width="10%" class="center">Deductions</th>
					<th width="10%" class="center">Total Salary</th>
					<th width="10%" class="center">Update</th>
					<th width="6%" class="center">View</th>
				</tr>
			</thead>
			<tbody>
			<?if(count(  $this->salarysList)>0):?>
				<?php foreach(  $this->salarysList as $salary):
					$encsalaryId = $this->encode($salary['sal_id']);
				?>
				<tr>
					<td class="center"><?=@++  $this->offset;?></td>
					<td><?=$salary['sal_year']?> </td>
					<td><?=$salary['sal_month']?></td>
					<td><?=$salary['sal_empcount']?></td>
					<td><?=$salary['sal_addition']?></td>
					<td><?=$salary['sal_deduction']?></td>
					<td><?=$salary['sal_net']?></td>
					<td class="center">
					<?php if($salary['sal_status']==1):?>
						<?=x(array('link'=>'erp_employee/salary/salary','ref'=>$encsalaryId,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'wide_opener')))?>  
					<?php endif?>
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_employee/salary/report','ref'=>$encsalaryId,'label'=>'<i class="fas fa-search"></i>',array("param"=>'wide_opener')))?>
					</td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?  $this->salaryObj->pagination();?>
	</div>
</div>
</form>
</div>
</div>
</div>
