<div style="padding-left: 10px; padding-right: 10px;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button>
		</div>
<form method="get" id="filter" name="filter" action="billbycustomer.php">
<div class="col-md-12 card filter-card">
	<div class="card-block" style="padding-top: 4%;">

		<h5 class="title-margin">Report:Consolidated Customer wise Outstanding Statement</h5>
	</div>
	</div>

<div class="col-md-12 card" style="height: 100%; padding-left: 5px; padding-right: 5px;">
<div id="report">
<?php include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
<?php //include_once __DIR__ . '/../../../../public_html/asfruits/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
						<tr>
							<th width="100%">
								<table style="margin-bottom: 1px;" width="100%">
									<tbody>
										<tr>
											<th width="12%">
												<div class="title-margin" style="">
												<img alt="" src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/babana1.png" style="margin-top: 2px;margin-left: 1px;width: 80%;padding-left: 2%;">
												</div>
											</th> 
										
											<th colspan="2" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="60%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">A.S.  	 BANANA MERCHANT
													</div>
											</th>
											<th colspan="" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="10%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">
													</div>
											</th>
										</tr>
									</tbody>
								</table>
							</th>
						</tr>
						<tr>
							<td width="22%" colspan="4" align="center">
								<div style="font-size: 15px; transform: scale(1, 2); font-family: f1; font-family: Times;"><?=@$_SESSION ['COMP_LABL2']?>
									</div>
							</td>
						</tr>
						<tr>
							<th class="empty" colspan="10"
								style="border-top: 1px solid black;">
								<table class="rpt_tbl" style="margin-top: 13px;">
									<tr style="border: medium none;">
										<th style="border: medium none;"><div class="center"
												style="width: 96%;">Consolidated Customer wise Outstanding Statement</div></th>
									</tr>
								</table>

							</th>
						</tr>
							</thead>
						</table>
					</div>
					<table class="rpt_frame">
			<thead>
				<tr>
					<th class="empty" colspan="8"></th>
				</tr>
				<tr>
					<th width="3%" class="center">Sl No</th>
					<th width="10%" class="center">Bill No</th>
					<th width="14%" class="center">Ref No</th>
					<th width="14%" class="center">Date</th>
					<th width="14%" class="center">Due Date</th>
					<th width="8%" class="center">Remarks</th>
					<th width="14%" class="center">Bill Amount</th>
					<th width="14%" class="center">Credit Amount</th>
				</tr>
			</thead>
			<tbody>
			<?php $headder = 0;?>
			<?if(count($this->billList)>0):?>
			
				<?php 
				$pvhl= '';
				foreach($this->billList as $bill):
					$encBillId = $this->encode($bill['bill_id']);
				?>
				<?php if($pvhl!= $bill['bill_customer_id'] && $pvhl!=''):?> 
				
				<tr>
					<th colspan="7" style="text-align: right;"> TOTAL FOR :<?=$custName?>  </th>		
					<th ><?=number_format(@$vhlTotal,3);?></th>														
				</tr>
				<?php if($due):?>
				<tr>
					<th class="center">Aging:</th>	
					<th> <?= $due>0? 'Due:'.number_format($due,3):'';?></th>
					<th> <?= $due15>0? 'More 15 days:'.number_format($due15,3):'';?></th>
					<th> <?= $due30>0? 'More 30 days:'.number_format($due30,3):'';?></th>
					<th><?php if($due45>0):?>
					<div style="background:#7FFFD4"><?= 'More 45 days:'.number_format($due45,3);?> </div>
					<?php endif?></th>	
					<th><?php if($due60>0):?>
					<div style="background:#FFFF00"><?= 'More 60 days:'.number_format($due60,3);?> </div>
					<?php endif?></th>	
					<th><?php if($due90>0):?>
					<div style="background:#FFA07A"><?= 'More 90 days:'.number_format($due90,3);?> </div>
					<?php endif?></th>	
					<th><?php if($due120>0):?>
					<div style="background:#FF6347"><?= 'More 120 days:'.number_format($due120,3);?> </div>
					<?php endif?></th>	
						
				</tr>
				<?php endif?>
				
				<?php $vhlTotal = 0; 
				$due = 0; $due15 = 0;  $due30 = 0; $due45 = 0;  $due60 = 0;  $due90 = 0;  $due120 = 0; ?>
				<tr style="border: 1px solid white;">
					<td class="empty" style="border: 1px solid white; float:right" colspan="8"></td>
				</tr>
				<?
				
				endif?>
				
				<?php if($pvhl!= $bill['bill_customer_id']):?> 
				<tr>
					<th colspan="8" class="center"><?=$bill['cust_name']?><?//=$bill['con_phone']?><?//=$bill['con_mobile']?></th>														
				</tr>
				<?php if($headder):?>
				<tr>
					<th width="3%" class="center">Sl No</th>
					<th width="10%" class="center">Bill No</th>
					<th width="14%" class="center">Ref No</th>
					<th width="14%" class="center">Date</th>
					<th width="14%" class="center">Due Date</th>
					<th width="8%" class="center">Remarks</th>
					<th width="14%" class="center">Bill Amount</th>
					<th width="14%" class="center">Credit Amount</th>
				</tr>
				<?php $headder=1; endif; $headder=1;?>
				<?php $vhlTotal = 0; endif?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=x(array('link'=>'accounts/sales/miniview','ref'=>array('ref'=>$encBillId),'label'=>"AS/".sprintf("%04s", $bill['bill_id']),array("param"=>'class="facebox"')))?> </td>
					<td><?=$bill['bill_refno']?></td>
					<td><?=$bill['bill_disp_date']?></td>
					<td><?=$bill['bill_due_date']?></td>
					<td><?=$bill['bill_month']?></td>
					<td><?=number_format($bill['bill_total'],3)?></td>	
					<td><?=number_format($bill['bill_total'],3)?></td>													
				</tr>
				<?php  $pvhl = $bill['bill_customer_id'];
						$custName = $bill['cust_name'];
						$vhlTotal+=	$bill['bill_total'];
						$grndTotal+=$bill['bill_total'];
						
						$due += $bill['due_amount'];
						$due15 += $bill['due_amount_15'];
						$due30 += $bill['due_amount_30'];
						$due45 += $bill['due_amount_45'];
						$due60 += $bill['due_amount_60'];
						$due90 += $bill['due_amount_90'];
						$due120 += $bill['due_amount_120'];
				?>
				<?php endforeach?>
				<tr>
					<th colspan="7" style="text-align: right;"> TOTAL FOR :<?=$custName?>  </th>		
					<th ><?=number_format(@$vhlTotal,3);?></th>													
				</tr>
				<?php if($due):?>
				<tr>
					<th class="center">Aging:</th>	
					<th> <?= $due>0? 'Due:'.number_format($due,3):'';?></th>
					<th> <?= $due15>0? 'More 15 days:'.number_format($due15,3):'';?></th>
					<th> <?= $due30>0? 'More 30 days:'.number_format($due30,3):'';?></th>
					<th><?php if($due45>0):?>
					<div style="background:#7FFFD4"><?= 'More 45 days:'.number_format($due45,3);?> </div>
					<?php endif?></th>	
					<th><?php if($due60>0):?>
					<div style="background:#FFFF00"><?= 'More 60 days:'.number_format($due60,3);?> </div>
					<?php endif?></th>	
					<th><?php if($due90>0):?>
					<div style="background:#FFA07A"><?= 'More 90 days:'.number_format($due90,3);?> </div>
					<?php endif?></th>	
					<th><?php if($due120>0):?>
					<div style="background:#FF6347"><?= 'More 120 days:'.number_format($due120,3);?> </div>
					<?php endif?></th>				
				</tr>
				<?php endif?>
				<tr>
					<th class="empty" colspan="8"></th>
				</tr>
				<tr>
					<th style="text-align: right;" colspan="7"> Grand Total </th>		
					<th ><?=number_format(@$grndTotal,3);?></th>													
				</tr>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();	$date = $date->format('d/m/Y H:i:s')?> 
						<th><div class="title-margin rpt_footer"><h5>Vehicle MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</form>
</div>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
$(document).ready(function() {
	var source = '<?=APPURL?>'+ 'expense/getlive';
	$('#f_pCatSelect').on('change',function() {
		getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');
		$('#f_cCatSelect').empty();
	});
	getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');

	$('#f_sCatSelect').on('change',function() {
		getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
	});
	getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
});
</script>

