<div style="padding-left: 10px; padding-right: 10px;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button>
		</div>
<form method="get" id="filter" name="filter" action="">
	<div class="col-md-12 card" style="margin-bottom: 0px; margin-bottom: 0px;background-color: oldlace;">
	<div class="card-block" style="padding-top: 4%;">

		<h5 class="title-margin">Daily Report: <?=$this->reportDate;?></h5>
	</div>
	</div>

<div class="col-md-12 card" style="height: 100%; padding-left: 5px; padding-right: 5px;">
<div id="report">
<?php include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
<?php //include __DIR__ . '/../../../../public_html/asfruits/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
						<tr>
							<th width="100%">
								<table style="margin-bottom: 1px;" width="100%">
									<tbody>
										<tr>
											<th width="12%">
												<div class="title-margin" style="">
												<img alt="" src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/babana1.png" style="margin-top: 2px;margin-left: 1px;width: 80%;padding-left: 2%;">
												</div>
											</th> 
										
											<th colspan="2" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="60%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">A.S.  	 BANANA MERCHANT
													</div>
											</th>
											<th colspan="" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="10%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">
													</div>
											</th>
										</tr>
									</tbody>
								</table>
							</th>
						</tr>
						<tr>
							<td width="22%" colspan="4" align="center">
								<div style="font-size: 15px; transform: scale(1, 2); font-family: f1; font-family: Times;"><?=@$_SESSION ['COMP_LABL2']?>
									</div>
							</td>
						</tr>
						<tr>
							<th class="empty" colspan="10"
								style="border-top: 1px solid black;">
								<table class="rpt_tbl" style="margin-top: 13px;">
									<tr style="border: medium none;">
										<th style="border: medium none;"><div class="center"
												style="width: 96%;">Daily Summary Report Date : <?=$this->reportDate?></div></th>
									</tr>
								</table>

							</th>
						</tr>
							</thead>
						</table>
					</div>

			<?//if(count($this->collList)>0):?>
			<table class="rpt_frame" style="width: 95%;margin-left: 2%;">
			<thead>
				<tr>
					<th class="empty" colspan="4">Payment Collections</th>
				</tr>
				<tr>
					<th width="2%" class="center">Sl No</th>
					<th width="2%" class="center">File No</th>
					<th width="16%" class="center">Customer Name</th>
					<th width="3%" class="center">Amount Received</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->collList as $coll):
				$encPayId = $this->encode($coll['coll_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td>																				
					<?=x(array('link'=>'accounts/receivable/view','ref'=>array('ref'=>$encPayId),'label'=>"AS/REC/".sprintf("%04s", $coll['coll_id']),array("param"=>'class="facebox"')))?></td>
					<td><?=$coll['cust_name']?></td>
					<td align="right">
					<?=number_format($coll['coll_amount'],2);?>
					<? $colltotal+=$coll['coll_amount'];?></td>
				</tr>
				<?php endforeach?>
				<tr><td colspan="3" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($colltotal,2)?></b></td>
				</tr>

			</tbody>
		</table>
		<?//endif?>
	
		<?//if(count($this->billList)>0):?>
		<table class="rpt_frame" style="width: 95%;margin-left: 2%;">
			<thead>
				<tr>
					<th class="empty" colspan="4">Sales Invoices</th>
				</tr>
				<tr>
					<th width="2%" class="center">Sl No</th>
					<th width="2%" class="center">Bill No</th>
					<th width="16%" class="center">Customer</th>
					<th width="3%" class="center">Invoice Amount</th>
				</tr>
			</thead>
			<tbody>

			
				<?php 
				$offset = 0;
				$btotal = 0;
				foreach($this->billList as $bill):
				$encBillId= $this->encode($bill['bill_id']);?>
				<tr<?=$trclass;?>>			
					<td class="center"><?=@++$offset;?></td>
					<td><?=x(array('link'=>'accounts/sales/miniview','ref'=>array('ref'=>$encBillId),'label'=>"AS/".sprintf("%04s", $bill['bill_id']),array("param"=>'class="facebox"')))?> </td>
					<td><?=$bill['cust_name']?></td>
					<td align="right"><?=number_format($bill['bill_total'],2)?>
					<? $btotal+=$bill['bill_total'];?>
					</td>		
				</tr>
				<?php //$grndTotal+=$bill['bill_total'];
				endforeach?>
				
				<tr><td colspan="3" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($btotal,2)?></b></td>
				</tr>

				</tbody>
		</table>
		<?//endif?>
		
			<table class="rpt_frame" style="width: 95%;margin-left: 2%;">
			<thead>
				<tr>
					<th class="empty" colspan="4">Customer Outstanding Report</th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="25%" class="center">Customer Name</th>
					<th width="12%" class="center">Amount Outstanding</th>
					<th width="12%" class="center">Advance Amount</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->customerDue)>0):?>
				<?php foreach($this->customerDue as $due):
				$encCustId = $this->encode($due['cust_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$due['cust_name'];?>
					</td>
					<td align="right"><?=number_format($due['due_amount'],3); $dueTotal+=$due['due_amount'];?></td>
					<td align="right"><?=number_format($due['adv_amount'],3); $advtotal+=$due['adv_amount'];?></td>
				</tr>
				<?php endforeach?>
				<tr><td colspan="2" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($dueTotal,3)?></b></td>
					<td align="right"> <b><?=number_format($advtotal,3)?></b></td>
				</tr>
			<?endif?>
			</tbody>
		</table>


			<table class="rpt_frame" style="width: 95%;margin-left: 2%;">
			<thead>
				<tr>
					<th class="empty" colspan="4">Daily Item Sales Summary Report </th>
				</tr>
				<tr>
					<th width="10%" class="center">Sl No</th>
					<th width="65%" class="center">Item Name</th>
					<th width="10%" class="center">Count</th>
					<th width="10%" class="center">Weight (Kg.)</th>
				</tr>
			</thead>
			<tbody>
			<?//if(count($this->billItemList)>0):?>
				<?php foreach($this->billItemList as $bill):?>
				<tr>
					<td class="center"><?=@++$ioffset;?></td>
					<td align="left"><span style="font-size: large;" > <?=$bill['item_name']?></span></td>
					<td align="center"><?=$bill['item_count']; $cnttotal+=$bill['item_count'];?></td>
					<td align="right"><?=number_format($bill['item_qnty'],2); $qtotal+=$bill['item_qnty'];?></td>

				</tr>
				<?php endforeach?>
				<tr><td colspan="2" align="right"><b> Total:</b> </td>
					<td align="center"> <b><?=$cnttotal;?></b></td>
					<td align="right"> <b><?=number_format($qtotal,2)?></b></td>
				</tr>
			<?//endif?>
			</tbody>
		</table>		
	</div>			
						
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/Y H:i:s')?>
						<th><div class="title-margin rpt_footer"><h5>MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</form>
</div>

<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
</script>
<style>
.modal-dialog{
	width: 95%;
}

.row {
  display: flex;
}

.column {
  flex: 50%;
  padding: 5px;
}
</style>

