
<div class="card-block">
	<div class="full-width">
	</div>
	<h5 class="title-margin">Item report</h5>
</div>
<form method="get" id="filter" name="filter" action="">
<div class="col-md-12" style="margin-top:1px;">
	<div class="card">
            <div class=" form-group col-md-3">
              <div class="form-group ">
                <label for="inputSuccess1">Code</label>
                <?=$this->form->f_code->show()?>
              </div>
             </div>
          <div class="col-md-3">
              <div class="form-group ">
                <label for="inputSuccess1">Name</label>
                <?=$this->form->f_name->show()?>
              </div>
             </div>
             </div>
              <div class="col-md-3">
              <div class="form-group ">
					<button class="btn <?=$filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
              </div>
             </div>
</div>

<div class="col-md-12">
	<div class="card">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="9%" class="center">Code</th>
					<th width="15%" class="center">Name</th>
					<th width="5%" class="center">Quantity</th>
					<th width="12%" class="center">Main Category</th>
					<th width="8%" class="center">Sub Category</th>
					<th width="10%" class="center">Edit</th>
					<th width="6%" class="center">View</th>
				</tr>
			</thead>
			<tbody>
			<?
			if(count($this->itemsList)>0):?>
				<?php foreach($this->itemsList as $item):
					$encItemId = $this->encode($item['item_id']);
				?>
				<tr>
					<td class="center"><?=++$this->itemObj->_voffset;?></td>
					<td><?=$item['item_code']?></td>
					<td><?=$item['item_name']?></td>
					<td align="center"><?=$item['stock_qty']?></td>
					<td align="center"><?=$item['category']?></td>
					<td align="center"><?=$item['parent_cat']?></td>
					<td class="center">
						<?=x(array('link'=>'manage/item/edit','ref'=>array('ref'=>$encItemId),'label'=>'<i class="fas fa-edit"></i>'))?></td>
					<td class="center">
						<?=x(array('link'=>'manage/item/view','ref'=>array('ref'=>$encItemId),'label'=>'<i class="fas fa-search"></i>',array("param"=>'class="facebox"')))?></td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
	</div>
</div>
</form>

