<div style="padding-left: 10px; padding-right: 10px;">
	<div class="col-md-12 card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin"><?=$this->title;?></h5>
</div>
<form method="get" id="filter" name="filter" action="">
<div class="col-md-12 card filter-card">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="15%">Vendor</th>
				<th width="8%">GRN No.</th>
				<th width="10%">Ref No</th>
				<th width="10%">Payment Type</th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_customer->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_purchaseno->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_refno->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_paymode->show()?>
              		</div>
				</td>
			</tr>
			</table>
			<table class="" width="100%" style="margin-left: 2%;">
				<tr>	
					<td align="left">
						<div class="form-group">
	                	<?=$this->form->f_period->show()?>
	              		</div>
					</td>
					<td class="pr_month">
						<div class=" form-group" style="width: 50%;">
	                	<?=$this->form->f_monthpick->show()?>
	              		</div>
					</td>
					<td class="pr_fdt">
						<div class="form-group">
	                	<?=$this->form->f_dtfrom->show()?>
	              		</div>
					</td>
					<td class="pr_tdt">
						<div class="form-group">
	                	<?=$this->form->f_dtto->show()?>
	              		</div>
					</td>
					<td align="center">
		              <div class="form-group ">
						<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
						<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
		              </div>
					</td>
				</tr>
			</table>
	</div>
<div class="col-md-12 card" style="height: 100%; padding-left: 5px; padding-right: 5px;">
<div id="report">
<?php include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
<?php // include_once __DIR__ . '/../../../../public_html/asfruits/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
						<tr>
							<th width="100%">
								<table style="margin-bottom: 1px;" width="100%">
									<tbody>
										<tr>
											<th width="12%">
												<div class="title-margin" style="">
												<img alt="" src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/babana1.png" style="margin-top: 2px;margin-left: 1px;width: 80%;padding-left: 2%;">
												</div>
											</th> 
										
											<th colspan="2" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="60%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">A.S.  	 BANANA MERCHANT
													</div>
											</th>
											<th colspan="" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="10%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">
													</div>
											</th>
										</tr>
									</tbody>
								</table>
							</th>
						</tr>
						<tr>
							<td width="22%" colspan="4" align="center">
								<div style="font-size: 15px; transform: scale(1, 2); font-family: f1; font-family: Times;"><?=@$_SESSION ['COMP_LABL2']?>
									</div>
							</td>
						</tr>
						<tr>
							<th class="empty" colspan="10"
								style="border-top: 1px solid black;">
								<table class="rpt_tbl" style="margin-top: 13px;">
									<tr style="border: medium none;">
										<th style="border: medium none;"><div class="center"
												style="width: 96%;"><?=$this->title?></div></th>
									</tr>
								</table>

							</th>
						</tr>
							</thead>
						</table>
					</div>
					<table class="rpt_frame">
			<thead>
				<tr>
					<th class="empty" colspan="10"></th>
				</tr>
				<tr>
					<th width="2%" class="center">Sl No</th>
					<th width="2%" class="center">Bill No</th>
					<th width="16%" class="center">Supplier</th>
					<th width="3%" class="center">Ref No</th>
					<th width="3%" class="center">Bill Date</th>
					<th width="22%" class="center">Bill Details</th>
					<th width="3%" class="center">Invoice Amount</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->purchaseList)>0):?>
			
				<?php 
				foreach($this->purchaseList as $purchase):
				$encBillId= $this->encode($purchase['prch_id']);?>
				<tr<?=$trclass;?>>			
					<td class="center"><?=@++$offset;?></td>
					<td><?=x(array('link'=>'accounts/purchase/miniview','ref'=>array('ref'=>$encBillId),'label'=>"AS/GRN/".sprintf("%04s", $purchase['prch_id']),array("param"=>'class="facebox"')))?> </td>
					<td><?=$purchase['ven_name']?></td>
					<td><?=$purchase['prch_refno']?> <br> <?php if($purchase['prch_location']<>''):?>(<?=$purchase['prch_location']?>) <?php endif;?></td>
					<td><?=$purchase['prch_disp_date']?></td>
					<td><?=$purchase['itm_name']?></td>
					<td align="right"><?=number_format($purchase['prch_total'],3)?>
					<? $total+=$purchase['prch_total'];?></td>		
				</tr>
				<?php //$grndTotal+=$purchase['prch_total'];
				endforeach?>
				<tr><td colspan="6" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($total,3)?></b></td>
				</tr>
				</tbody>
		</table>
		<?php endif?>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
										$date = $date->format('d/m/Y H:i:s')?>
						<td><div class="title-margin rpt_footer"><small><?=$date?></small></div></td>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</form>
</div>
</div>


<script type="text/javascript"> 
function doSearch(text, backgroundColor) {
    if (window.find && window.getSelection) {
        document.designMode = "on";
        var sel = window.getSelection();
        sel.collapse(document.body, 0);

        while (window.find(text)) {
            document.execCommand("HiliteColor", false, backgroundColor);
            sel.collapseToEnd();
        }
        document.designMode = "off";
    }
}
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });

	toggledtoptions();
	
	$('#f_period1').on('click',function() {
		toggledtoptions();
	});

	$('#f_period2').on('click',function() {
		toggledtoptions();
	});

doSearch('<?= @$this->refno; ?>','yellow');

});
function toggledtoptions(){
	if($('#f_period1').is(':checked')){
		$('#f_dtfrom').val('');
		$('#f_dtto').val('');
		$('.pr_month').show();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
	else if($('#f_period2').is(':checked')){
		$('#f_monthpick').val('');
		$('.pr_month').hide();
		$('.pr_fdt').show();
		$('.pr_tdt').show();
	}
	else{
		$('.pr_month').hide();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
}
</script>
