<div style="padding-left: 10px; padding-right: 10px;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button>
		</div>
<form method="get" id="filter" name="filter" action="billbycustomer.php">
<div class="col-md-12 card filter-card">
	<div class="card-block" style="padding-top: 4%;">

		<h5 class="title-margin">Report: Paymant Pending for Supplier</h5>
	</div>
	</div>

<div class="col-md-12 card" style="height: 100%; padding-left: 5px; padding-right: 5px;">
<div id="report">
<?php include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
<?php // include_once __DIR__ . '/../../../../public_html/asfruits/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
						<tr>
							<th width="100%">
								<table style="margin-bottom: 1px;" width="100%">
									<tbody>
										<tr>
											<th width="12%">
												<div class="title-margin" style="">
												<img alt="" src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/babana1.png" style="margin-top: 2px;margin-left: 1px;width: 80%;padding-left: 2%;">
												</div>
											</th> 
										
											<th colspan="2" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="60%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">A.S.  	 BANANA MERCHANT
													</div>
											</th>
											<th colspan="" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="10%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">
													</div>
											</th>
										</tr>
									</tbody>
								</table>
							</th>
						</tr>
						<tr>
							<td width="22%" colspan="4" align="center">
								<div style="font-size: 15px; transform: scale(1, 2); font-family: f1; font-family: Times;"><?=@$_SESSION ['COMP_LABL2']?>
									</div>
							</td>
						</tr>
						<tr>
							<th class="empty" colspan="9"
								style="border-top: 1px solid black;">
								<table class="rpt_tbl" style="margin-top: 13px;">
									<tr style="border: medium none;">
										<th style="border: medium none;"><div class="center"
												style="width: 96%;">Paymant Pending for Supplier</div></th>
									</tr>
								</table>

							</th>
						</tr>
							</thead>
						</table>
					</div>
		<table class="rpt_frame">
			<thead>
				<tr>
					<th class="empty" colspan="4"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="25%" class="center">Supplier Name</th>
					<th width="12%" class="center">Paymant Pending</th>
					<th width="12%" class="center">Advance Amount Paid</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->purchaseList)>0):?>
				<?php foreach($this->purchaseList as $purch):
				$encCustId = $this->encode($purch['ven_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$purch['ven_name'];?>
					</td>
					<td align="right"><?=number_format($purch['due_amount'],3); $total+=$purch['due_amount'];?></td>
					<td align="right"><?=number_format($purch['adv_amount'],3); $advtotal+=$purch['adv_amount'];?></td>
				</tr>
				<?php endforeach?>
				<tr><td colspan="2" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($total,3)?></b></td>
					<td align="right"> <b><?=number_format($advtotal,3)?></b></td>
				</tr>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();	$date = $date->format('d/m/Y H:i:s')?> 
						<th><div class="title-margin rpt_footer"><h5>MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</form>
</div>
