<div style="padding-left: 10px; padding-right: 10px;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button>
		</div>
<form method="get" id="filter" name="filter" action="">
<div class="col-md-12 card filter-card">
	<div class="card-block" style="padding-top: 4%;">

		<h5 class="title-margin">Report: <?=$this->title?> </h5>

	</div>
		<table class="" width="100%" style="margin-left: 2%;" 	>
			<tr style="font-size: 0.8em;">
				<th colspan="5">Customer</th>
			</tr>
			<tr>	
				<td colspan="5">
					<div class="form-group" style="width: 30%;">
                	<?=$this->form->f_selCustomer->show()?>
              		</div>
				</td>
			</tr>
			<tr style="font-size: 0.8em;">
				<th align="right" width="20%">Choose Date Range - Month/ Period</th>
				<th class="pr_month" width="30%"><div class="">Month</div></th>
				<th class="pr_fdt" width="15%"><div class="">From</div></th>
				<th class="pr_tdt" width="15%"><div class="">To</div></th>
				<th width="20%"></th>
			</tr>
			<tr>	
				<td align="left">
					<div class="form-group">
                	<?=$this->form->f_period->show()?>
              		</div>
				</td>
				<td class="pr_month">
					<div class=" form-group" style="width: 50%;">
                	<?=$this->form->f_monthpick->show()?>
              		</div>
				</td>
				<td class="pr_fdt">
					<div class="form-group">
                	<?=$this->form->f_dtfrom->show()?>
              		</div>
				</td>
				<td class="pr_tdt">
					<div class="form-group">
                	<?=$this->form->f_dtto->show()?>
              		</div>
				</td>
				<td align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
	</div>

<div class="col-md-12 card" style="height: 100%; padding-left: 5px; padding-right: 5px;">
<div id="report">
<?php include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
<?php //include_once __DIR__ . '/../../../../public_html/asfruits/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
						<tr>
							<th width="100%">
								<table style="margin-bottom: 1px;" width="100%">
									<tbody>
										<tr>
											<th width="12%">
												<div class="title-margin" style="">
												<img alt="" src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/babana1.png" style="margin-top: 2px;margin-left: 1px;width: 80%;padding-left: 2%;">
												</div>
											</th> 
										
											<th colspan="2" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="60%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">A.S.  	 BANANA MERCHANT
													</div>
											</th>
											<th colspan="" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="10%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">
													</div>
											</th>
										</tr>
									</tbody>
								</table>
							</th>
						</tr>
						<tr>
							<td width="22%" colspan="4" align="center">
								<div style="font-size: 15px; transform: scale(1, 2); font-family: f1; font-family: Times;"><?=@$_SESSION ['COMP_LABL2']?>
									</div>
							</td>
						</tr>
						<tr>
							<th class="empty" colspan="10"
								style="border-top: 1px solid black;">
								<table class="rpt_tbl" style="margin-top: 13px;">
									<tr style="border: medium none;">
										<th style="border: medium none;"><div class="center"
												style="width: 96%;"><?=$this->title;?></div></th>
									</tr>
								</table>

							</th>
						</tr>
							</thead>
						</table>
					</div>
					<table class="rpt_frame">
			<thead>
				<tr>
					<td class="empty" colspan="5" style="border: 1px solid white;">
					</td>
				</tr>
				<tr>
					<th class="empty" colspan="5"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="18%" class="center">Supplier Name</th>
					<th width="5%" class="center">Date.</th>
					<th width="12%" class="center">Amount Received</th>
					<th width="12%" class="center">Discount</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->paymentList)>0):?>
				<?php foreach($this->paymentList as $pay):
				$encPayId = $this->encode($pay['pay_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$pay['ven_name']?> <?=$pay['cdmd_note'];?>
					</td>
					<td align="center"><?=$pay['pay_date']?></td>
					<td align="right">
					<?=x(array('link'=>'accounts/receivable/view','ref'=>array('ref'=>$encPayId),'label'=>number_format($pay['pay_amount'],3),array("param"=>'class="facebox"')))?>
					
					<? $total+=$pay['pay_amount'];?></td>
					<td align="right"><?=number_format($pay['pay_adjustment'],3); $disTotal+=$pay['pay_adjustment'];?></td>
				</tr>
				<?php endforeach?>
				<tr><td colspan="3" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($total,3)?></b></td>
					<td align="right"> <b><?=number_format($disTotal,3)?></b></td>
				</tr>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/Y H:i:s')?>
						<th><div class="title-margin rpt_footer"><h5>MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</form>
</div>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });

	toggledtoptions();
	
	$('#f_period1').on('click',function() {
		toggledtoptions();
	});

	$('#f_period2').on('click',function() {
		toggledtoptions();
	});
});
function toggledtoptions(){
	if($('#f_period1').is(':checked')){
		$('#f_dtfrom').val('');
		$('#f_dtto').val('');
		$('.pr_month').show();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
	else if($('#f_period2').is(':checked')){
		$('#f_monthpick').val('');
		$('.pr_month').hide();
		$('.pr_fdt').show();
		$('.pr_tdt').show();
	}
	else{
		$('.pr_month').hide();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
}
</script>
<style>
.modal-dialog{
	width: 95%;
}
</style>

