<div class="dynamic-popup" id="dynamic-popup">
    <form name="form" method="post" action="erp_manage/legalcase/fupedit/ref/<?=$this->param['ref']?>"style="margin-bottom: 0px;" autocomplete="off" enctype="multipart/form-data">
        <div class="modal-content modal-content-demo">
            <div class="modal-header">
                <h4 class="card-title">Update Follow-Up/ Updates</h4>
                <button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" style="margin-top: 0px;">
                <div class="row g-3 mb-2">
                    <div class="col-sm-12">
                        <label class="form-label">Summary</label>
                        <?=$this->form->lcflo_update->show()?>
                    </div>
                    </div>
                    <div class="row g-3 mb-2">
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-4">
                                <label class="form-label">Date</label>
                                <?=$this->form->lcflo_date->show()?>
                            </div>
                             <div class="col-sm-4">
                                <label class="form-label">Current Status</label>
                                <?=$this->form->lcflo_sts->show()?>
                            </div>
                            
                            <div class="col-sm-4">
        						<label class="form-label">File Upload <?=x(array('link'=>'default/default/download','ref'=>$this->encFileId,'label'=>'<i class="glyphicon glyphicon-download-alt text-info"></i>',array("param"=>'opener')))?></label>
        						<?=$this->form->my_files->show()?>
        					</div>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary submit-alias livepost">Save changes</button>
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </form>
</div>

<style>
.modal-dialog {
    width: 65%;
}
.modal-body .col-12 textarea {
    width: 100% !important;
    min-height: 120px;
}
</style>

<script>
$(document).ready(function($) {
    $('body').on('change', 'input.time', function() {
        const timePattern = /^([01]?[0-9]|2[0-3]):[0-5][0-9]$/; // Regex for valid HH:mm format
        const value = $(this).val().trim();

        if (!timePattern.test(value)) {
            // Clear the input if it doesn't match the time format
            $(this).val("");
        }
    });
});</script>
