<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_manage/documents/add/ref/<?=$this->param['ref']?>/type/<?=$this->param['type']?>' style="margin-bottom: 0px;" enctype="multipart/form-data">
	<div class="modal-header">
		<button aria-label="Close" class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true">×</span></button>
		<h4 class="modal-title">Documents
		</h4>
	</div>
	<div class="modal-body">

				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-2 form-label" >Title</label>
					<div class="col-sm-4">
                    <?=$this->form->title->show()?>
                  </div>

					<label class="col-sm-2 form-label" >Ref No</label>
					<div class="col-sm-4">
                    <?=$this->form->refno->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Description</label>
					<div class="col-sm-4">
                    <?=$this->form->desc->show()?>
                  </div>

					<label class="col-sm-2 form-label" >Start Date</label>
					<div class="col-sm-4">
                    <?=$this->form->startDt->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >End Date</label>
					<div class="col-sm-4">
                    <?=$this->form->endDt->show()?>
                  </div>
                  <label class="col-sm-2 form-label" >File No.</label>
					<div class="col-sm-4">
                    <?=$this->form->fileno->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Document</label>
					<div class="col-sm-4">
                    <?=$this->form->my_files->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Add</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '70%');
})
</script>
