<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" action="erp_expense/expense/add" style="margin-bottom: 0px;" enctype="multipart/form-data">		
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Add Expense Details</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row mb-4" style="">
					<label class="col-sm-2 form-label" >Vendor</label>
					<div class="col-sm-4">
                    <?=$this->form->selVendor->show()?>
                  </div>
                  <div id="div_vendor" class="col-sm-6">
                    <?=$this->form->vendor->show()?>
                  </div>
				</div>
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-2 form-label" >Ref No:
						</label>
					<div class="col-sm-3">
                    <?=$this->form->refno->show()?>
                  </div>
                  	<label class="col-sm-1 form-label" style="width: 8%;">Date:
						</label>
					<div class="col-sm-2">
                    <?=$this->form->billdt->show()?>
                  </div>
					<label class="col-sm-1 form-label" style="width: 8%;">Company
						</label>
					<div class="col-sm-2">
                    <?=$this->form->company->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Main Head Type
					</label>
				  <div class="col-sm-4">
                    <?=$this->form->mainhead->show()?>
                  </div>
                  <div id="mh_varis" class="col-sm-6">
                    <table width="100%" id="multi_table">
					<tr style="font-size: 0.8em;">
						<th width="45%" style="padding-bottom: 5px;">Main Head Particulers</th>
						<th width="20%"style="padding-bottom: 5px;">(Riyal)</th>
						<th width="5%" style="padding-bottom: 5px;"></th>
					</tr>
					<?php foreach($this->mfields as $i):?>
					<tbody id="dup_body">
					<tr class="dup_row" index="<?=$i?>">
						<td class="mh_emp" valign="top">
		                	<?=$this->form->employee[$i]->show()?>
						</td>
						<td class="mh_prop" valign="top">
		                	<?=$this->form->property[$i]->show()?>
						</td>
						<td class="mh_veh" valign="top">
		                	<?=$this->form->vehicle[$i]->show()?>
						</td>
						<td valign="top">
		                	<?=$this->form->mamount[$i]->show()?>
						</td>
						<td valign="middle">
			              <div>
							<a style="color: blue; margin: 1px;" title="Remove" href="#" onclick="delRow(this);return false;" class="glyphicon glyphicon-remove"></a>
			              </div>
						</td>
					</tr>
					<?php endforeach;?>
					</tbody>
					</table>
                    <div style="display: flex; justify-content: space-between; align-items: center; width: 91%;">
                        <a style="background-color: yellowgreen; margin: 1px;"
                           id="myLink"
                           title="Add more"
                           href="#"
                           onclick="addRow('multi_table'); return false;"
                           class="btn">
                           More
                        </a>
                        <span style="background-color: lightgray; margin: 1px;width: 20%;"
                              id="parTotal"
                              title="Total"
                              class="btn">
                              --
                        </span>
                    </div>
                  </div>
				</div>	
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Parent Category
						</label>
					<div class="col-sm-4">
                    <?=$this->form->pCatSelect->show()?>
                  </div>
                  <div id="div_pcat" class="col-sm-6">
                    <?=$this->form->pCategory->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Sub Category
						</label>
					<div class="col-sm-4">
                    <?=$this->form->sCatSelect->show()?>
                  </div>
                  	<div  id="div_scat" class="col-sm-6">
                    <?=$this->form->sCategory->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Child Category
						</label>
					<div class="col-sm-4">
                    <?=$this->form->cCatSelect->show()?>
                  </div>
                  	<div id="div_ccat" class="col-sm-6">
                    <?=$this->form->cCategory->show()?>
                  </div>
				</div>
				
				<div class="row mb-4">
				<label class="col-sm-2 form-label" >Cash Flow Entry</label>
					<div class="col-sm-10">
                     <?=$this->form->cashFlow->show()?>
                  </div>
			  	</div>
				
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Bill Details
						</label>
					<div class="col-sm-4">
                    <?=$this->form->particulers->show()?>
                  </div>
                  	<div class="col-sm-3">
                    <?=$this->form->amount->show()?>
                  </div>
                   <div class="col-sm-1">
                    <?=$this->form->vatoption->show()?>
                  </div>
                  
                  <div class="col-sm-2" id="vatgroup">
                    <?=$this->form->vatamount->show()?>
                  </div>
				</div>	
				
				<div class="row mb-4 col-sm-12">
				       <div class="col-sm-2" style="margin-top: 0.9em;">
        					<label class="form-label" >Payment Mode</label>
                      </div>
    				  <div class="col-sm-2" style="margin-top: 1.7em;">
                        	<?=$this->form->paymod->show()?>
                      </div>
                      <div id="id_dtdys" class="col-sm-2" style="margin-top: 1.7em;">
    	                 	<?=$this->form->paydtption->show()?>
                      </div>
                      <div id="id_days" class="col-sm-4" style="margin-top: 0.9em;">
    	                     <?=$this->form->paydays->show()?>
                      </div>
                      <div id="id_date" class="col-sm-4" style="margin-top: 0.9em;">
    	                     <?=$this->form->payby->show()?>
    				  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Upload Document</label>
					<div class="col-sm-4">
                    <?=$this->form->my_files->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Add</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<script type="text/javascript">           
$(document).ready(function() {

    expAmountInput = document.getElementById('amount');
    vatAmountInput = document.getElementById('vatamount');
    expAmount = parseFloat(expAmountInput.value) || 0;
    vatAmount = expAmount * 0.05;
    vatAmountInput.value = vatAmount.toFixed(3);
    function calculateVAT() {
        const expAmount = parseFloat(expAmountInput.value) || 0;
        const vatAmount = expAmount * 0.05;
        vatAmountInput.value = vatAmount.toFixed(3); // Set VAT amount in the input field
    }
    expAmountInput.addEventListener('keyup', calculateVAT);
    
	
	var source = '<?=APPURL?>'+ 'erp_expense/expense/getlive';
	$('#pCatSelect').on('change',function() {
		getJaxData($('#pCatSelect').val(),'sCatSelect',source,'parent',true);
		$('#cCatSelect').empty();
	});
	getJaxData($('#pCatSelect').val(),'sCatSelect',source,'parent',true);

	$('#sCatSelect').on('change',function() {
		getJaxData($('#sCatSelect').val(),'cCatSelect',source,'sub',true);
	});
	getJaxData($('#sCatSelect').val(),'cCatSelect',source,'sub',true);

	$('.mh_emp').hide();
	$('.mh_prop').hide();
	$('.mh_veh').hide();
	$('#mh_varis').hide();

	$('#mainhead').on('change',function() {
		$("#multi_table").find("tr:gt(1)").remove();
		fixmainhead();
	});


	fixmainhead();
	
	$('#selVendor').on('change',function() {
		fixvendor();
	});
	$('#pCatSelect').on('change',function() {
		fixPcat();
	});
	$('#sCatSelect').on('change',function() {
		fixScat();
	});
	$('#cCatSelect').on('change',function() {
		fixCcat();
	});
	fixvendor();
	fixPcat();
	fixScat();
	fixCcat();
	$('#vatgroup').hide();
	
	function fixvendor(){
		if($('#selVendor').val()==-1){
			$('#div_vendor').show();
		}
		else{
			$('#div_vendor').hide();
		}
	}
	function fixPcat(){
		if($('#pCatSelect').val()==-1){
			$('#div_pcat').show();
		}
		else{
			$('#div_pcat').hide();
		}
	}
	function fixScat(){
		if($('#sCatSelect').val()==-1){
			$('#div_scat').show();
		}
		else{
			$('#div_scat').hide();
		}
	}
	function fixCcat(){
		if($('#cCatSelect').val()==-1){
			$('#div_ccat').show();
		}
		else{
			$('#div_ccat').hide();
		}
	}

	$('#id_dtdys').hide();
	$('#id_days').hide();
	$('#id_date').hide();

	
	$('#paymod2').on('click',function() {
		fixcreditoptions();
	});

	$('#paymod1').on('click',function() {
		fixcreditoptions();
	});

	$('#paydtption1').on('click',function() {
		fixcreditdays();
	});

	$('#paydtption2').on('click',function() {
		fixcreditdays();
	});

	function fixcreditoptions(){

		if($('#paymod1').is(':checked')){
			$('#paydtption1').prop('checked', false);
			$('#paydtption2').prop('checked', false);
			$('#id_dtdys').hide();
			$('#id_days').hide();
			$('#id_date').hide();
		}
		
		if($('#paymod2').is(':checked'))
			{
			$('#id_dtdys').show();
			$('#id_days').hide();
			$('#id_date').hide();
		}

	}

	function fixcreditdays(){

		if($('#paydtption2').is(':checked'))
		{
			$('#id_days').show();
			$('#id_date').hide();
		}
				
		if($('#paydtption1').is(':checked'))
			{
			$('#id_days').hide();
			$('#id_date').show();
		}

	}

	fixcreditoptions();
	fixcreditdays();
	enableVat();
	
});



function enableVat(){
	if($('#vatoption1').is(':checked'))
	{
		$('#vatgroup').show();
	}	
	else
	{
		$('#vatgroup').hide();
	}
}


function fixmainhead(){
	if($('#mainhead').val()==1){
		$('.mh_emp').show();
		$('.mh_prop').hide();
		$('.mh_veh').hide();
		$('#mh_varis').show();
	}
	else if($('#mainhead').val()==2){
		$('.mh_prop').show();
		$('.mh_emp').hide();
		$('.mh_veh').hide();
		$('#mh_varis').show();
	}
	else if($('#mainhead').val()==3){
		$('.mh_veh').show();
		$('.mh_emp').hide();
		$('.mh_prop').hide();
		$('#mh_varis').show();
	}
	else{
		$('.mh_emp').hide();
		$('.mh_prop').hide();
		$('.mh_veh').hide();
		$('#mh_varis').hide();
	}
}
var duprow = '';
duprow = '<tr class="dup_row">' + $('#dup_body >tr:first').html() + '</tr>';
function delRow(row){
	if($('.dup_row').length>1){
		$(row).parents('tr').remove();
	}
	calculateTotal();
}
function addRow(elemId) {
	
	var index = $('#' + elemId + ' tbody>tr:last').attr('index');
	var index = parseInt(index)+1;
	
	$(duprow).insertAfter($('#' + elemId + ' tbody>tr:last'));
	fixmainhead();
	$('#' + elemId + ' tbody>tr:last').find('.input_error').removeClass(
			'input_error');
	$('#' + elemId + ' tbody>tr:last').find('.select_error').removeClass(
			'select_error');
	$('#' + elemId + ' tbody>tr:last').find('.error_text').remove();
	$('#' + elemId + ' tbody>tr:last').attr('index',index);

	$.each($('#' + elemId + ' tr:last').find(':input'), function() {
		$(this).val('');

		var name = $(this).attr('name');
		if (name !== undefined) {
			var arr = name.split('[');
			$(this).attr('id', arr[0] + '[' + index+ ']').attr(
					'name', arr[0] + '[' + index + ']');
		}
		$(".chosen-select").chosen({
			no_results_text : "Oops, nothing found!",
		    search_contains: true,
		    enable_split_word_search: true
		});
	});
}

function calculateTotal() {
    let sum = 0;

    $('input[name^="mamount"]').each(function () {
        let val = parseFloat($(this).val()) || 0;
        sum += val;
    });

    $('#parTotal').text(sum.toFixed(3));
}

$(document).on('keyup', 'input[name^="mamount"]', function () {
    //console.log("keyup triggered"); // debug
    calculateTotal();
});

</script>

<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '80%');
})
</script>

<style>
label {
  margin-top: 6px;
}
</style>
