<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" action='erp_expense/expense/catedit/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;" enctype="multipart/form-data">		
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Update Expense Category</h4>
				<button aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-4 form-label" >Parent Category
						</label>
					<div class="col-sm-6">
                    <?=$this->form->pCatSelect->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-4 form-label" >Sub Category
						</label>
					<div class="col-sm-6">
                    <?=$this->form->sCatSelect->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-4 form-label" >Child Category
						</label>
					<div class="col-sm-6">
                    <?=$this->form->cCatSelect->show()?>
                  </div>
				</div>
				<div class="row mb-4">
				<label class="col-sm-4 form-label" >Particulers</label>
					<div class="col-sm-6">
					<?=$this->form->particulers->show()?>
                  </div>
			  	</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Update</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<script type="text/javascript">           
$(document).ready(function() {
	var source = '<?=APPURL?>'+ 'erp_expense/expense/getlive';
	$('#pCatSelect').on('change',function() {
		getJaxData($('#pCatSelect').val(),'sCatSelect',source,'parent');
		$('#cCatSelect').empty();
	});
	getJaxData($('#pCatSelect').val(),'sCatSelect',source,'parent');

	$('#sCatSelect').on('change',function() {
		getJaxData($('#sCatSelect').val(),'cCatSelect',source,'sub');
	});
	getJaxData($('#sCatSelect').val(),'cCatSelect',source,'sub');


});
</script>

<style>
.modal-dialog{
	width: 50%;
}
</style>
