<?php if($this->expenseDet['exp_app_status']==1):?>

<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" action="erp_expense/expense/update/ref/<?=$this->param['ref'];?>" style="margin-bottom: 0px;" enctype="multipart/form-data">		
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Expense Transaction</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">

		<table class="table table-bordered">
			<tr>
				<th>Mode</th>
				<th>Ref No</th>
				<th width ="45%" colspan="2">Vender</th>
			</tr>
			<tr>
				<td><?=$this->expenseDet['pay_mod']?></td>
				<td><?=$this->expenseDet['exp_refno']?></td>
				<td colspan="2"><?=$this->expenseDet['ven_name']?></td>
			</tr>
			<tr>
				<th>Comapny</th>
				<th>Child Category</th>
				<th>Parent Category</th>
				<th>Sub Category</th>
			</tr>
			<tr>
				<td><?=$this->expenseDet['comp_disp_name']?></td>
				<td><?=$this->expenseDet['ccat']?></td>
				<td><?=$this->expenseDet['pcat']?></td>
				<td><?=$this->expenseDet['scat']?></td>
			</tr>
			<tr>
				<th>Head</th>
				<th>Details </th>
				<th>Bill Amount</th>
				<th>Credit Amount</th>
			</tr>
			<tr>
				<td><?=$this->expenseDet['main_head']?></td>
				<td><?=$this->expenseDet['exp_details']?></td>
				<td><?=$this->expenseDet['exp_amount']?></td>
				<td><?=$this->expenseDet['exp_credit_amt']?></td>
			</tr>
		</table>
		<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-2 form-label style="width:12%"" >Transaction Type</label>
					<div class="col-sm-2">
                    <?=$this->form->type->show()?>
                  </div>
					<label class="col-sm-1 form-label" style="width:6%">Date</label>
					<div class="col-sm-2">
                    <?=$this->form->billdt->show()?>
                  </div>
					<label class="col-sm-2 form-label" style="width:12%" >Cash Return</label>
					<div class="col-sm-3">
                    <?=$this->form->adjust->show()?>
          			</div>          
                    <div class="row mb-4">
                     <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                    <table width="80%" id="multi_table"  style="margin-top: 5px;margin-left: 10px;">
					<tr style="font-size: 0.8em;">
						<th width="45%" style="padding-bottom: 5px;">Main Head Particulers</th>
						<th width="12%"style="padding-bottom: 5px;">(Riyal)</th>
					</tr>
					</
					<?php $j=0; foreach($this->mfields as $i):?>
					<tbody id="">
					<tr class="" index="<?=$i?>">
						<td>
						<?php if($this->expenseDet['exp_mainh']==1):?>
						<?=$this->expRefDetails[$j]['ref_name1']?>
						<?php endif?>
						<?php if($this->expenseDet['exp_mainh']==2):?>
						<?=$this->expRefDetails[$j]['ref_name2']?>
						<?php endif?>
						<?php if($this->expenseDet['exp_mainh']==3):?>
						<?=$this->expRefDetails[$j]['ref_name3']?>
						<?php endif?>
						</td>
						<td valign="top">
		                	<?=$this->form->mamount[$i]->show()?>
						</td>
					</tr>
					<?php $j++; endforeach;?>
					</tbody>
					</table>
					</div>
                    
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Note</label>
					<div class="col-sm-10">
                    <?=$this->form->note->show()?>
                  </div>
                 </div>
                  <div class="row mb-4">
					<label class="col-sm-2 form-label" >Note</label>
					<div class="col-sm-4">
                    <?=$this->form->my_files->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Update</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<?endif?>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '80%');
})
</script>