<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" action="erp_masters/vman/add" style="margin-bottom: 0px;">		
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Add Vehicle Manufacturer </h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-3 form-label" >Vehicle Manufacturer  Code</label>
					<div class="col-sm-9">
                    <?=$this->form->vman_code->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Vehicle Manufacturer  Name</label>
					<div class="col-sm-9">
                    <?=$this->form->vman_name->show()?>
                  </div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary submit-alias livepost">Save
					changes</button>
				<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
			</div>
		</div>
	</form>
</div>
