<form method="get" id="filter" name="filter" action="list">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<!-- CONTAINER -->
			<div class="main-container container">
				<!-- PAGE-HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">Vehicles</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Vehicles</li>
						</ol>
					</div>
					<div class="ms-auto pageheader-btn">					
                        <?=x(array('link' => 'erp_vehicle/master/add','label' => '<button class="btn btn-primary btn-icon text-white me-2" > <i
							class="fe fe-plus"></i>
					</span> Add Vehicle</button>',array("param" => 'class="facebox"')), '<br><br>')?>					
							
					</div>
				</div>
				<!-- PAGE-HEADER END -->
				<!-- ROW -->
				<div class="row row-sm">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Filters</h3>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-3">
										<div class="form-group">
											<label for="file_no" class="form-label">Vehicle No</label>
                                            <?=$this->form->f_vhlno->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label for="name" class="form-label">Type</label>
                                            <?=$this->form->f_type->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Model</label>
                                            <?=$this->form->f_model->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Company</label>
                                            <?=$this->form->f_company->show()?>
                                        </div>
									</div>
								</div>
								<button class="btn <?=$this->filter_class?> mt-4 mb-0"
									type="submit">Filter</button>
								<input class="btn btn-secondary mt-4 mb-0" name="clear"
									type="submit" value="All"></input>
							</div>
						</div>
					</div>
					<!-- ROW -->
					<div class="">
						<div class="">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Vehicles</h3>
								</div>
								<div class="card-body">
									<div class="table-responsive export-table">
                                        <table aria-describedby="" class="table table-bordered text-nowrap no-footer">
                                                <thead class="border-top">
                                                  <tr role="row">
					<th width="5%" class="center">Sl No</th>
					<th width="9%" class="center">Vehicle No</th>
					<th width="15%" class="center">Category</th>
					<th width="15%" class="center">Type</th>
					<th width="15%" class="center">Model</th>
					<th width="15%" class="center">Company</th>
					<th width="15%" class="center">Man.</th>
					<th width="15%" class="center">Rate</th>
					<th width="10%" class="center">Edit</th>
					<th width="6%" class="center">View</th>
					<!--  <th width="6%" class="center">Delete</th>-->
				</tr>
			</thead>
			<tbody>
			<?if(count($this->vehicleList)>0):?>
				<?php foreach($this->vehicleList as $vehivle):
					$encVhlId = $this->encode($vehivle['vhl_id']);
				?>
				<tr>
					<td class="center"><?=@++$this->offset;?></td>
					<td><?=$vehivle['vhl_no']?></td>
					<td><?=$vehivle['vhl_comm_status']==1?'Non Commercial':"Commercial"?></td>
					<td><?=$vehivle['type_name']?></td>
					<td><?=$vehivle['vhl_model']?></td>
					<td><?=$vehivle['comp_disp_name']?></td>
					<td><?=$vehivle['vman_name']?></td>
					<td>
					<?php if($vehivle['vhl_rate_hour']):?>
					Hour: <?=$vehivle['vhl_rate_hour']?><br>
					<?php endif?>
					<?php if($vehivle['vhl_rate_day']):?>
					Day: <?=$vehivle['vhl_rate_day']?><br>
					<?php endif?>
					<?php if($vehivle['vhl_rate_month']):?>
					Month: <?=$vehivle['vhl_rate_month']?>
					<?php endif?>
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_vehicle/master/edit','ref'=>$encVhlId,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>  
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_vehicle/master/view','ref'=>$encVhlId,'label'=>'<i class="fas fa-search"></i>'))?> 
					</td>
					<!--
					<td class="center">
						<?//=x(array('link'=>'erp_vehicle/master/delete','ref'=>$encVhlId,'label'=>'<i class="glyphicon glyphicon-trash text-danger"></i>',array("param"=>'class="facebox"')))?> 
					</td>
					-->
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?$this->vehicleObj->pagination();?>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</form>	
<div>
</div>

<?php 
$this->vehicleObj = new vehicle();
//$this->vehicleList = $this->vehicleObj->getVehicleExpReport(@$where);
$commVhlExpSumm = $this->vehicleObj->getVehicleExpSummary(array('comm_status'=>2));
$nonVhlExpSumm = $this->vehicleObj->getVehicleExpSummary(array('comm_status'=>1));
?>

<script type="text/javascript">
baseurl = '<?=APPURL?>';

<?php /*
Highcharts.chart('container-comm', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Maintenence expenses - Commercial'
    },
    xAxis: {
        type: 'category',
        labels: {
            rotation: -45,
            style: {
                fontSize: '13px',
                fontFamily: 'Verdana, sans-serif'
            }
        }
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Expense'
        }
    },
    legend: {
        enabled: false
    },
    tooltip: {
        pointFormat: 'RO : <b>{point.y:.1f} Rial</b>'
    },

    plotOptions: {
    	column: {
            allowPointSelect: true,
            cursor: 'pointer',
            events:{
                click: function (event) {
                	getOpener ('wide',baseurl+'erp_report/expense/expense/f_mainhead/3/f_vehicle/'+event.point.ownURL);
                }
            },  
        }
    },

    
    series: [{
        name: 'Expense',
        data: 
            [<?foreach ($commVhlExpSumm as $summ):?>       
   	            {
   	                name: '<?=$summ['vhl_no']?>',
   	                y: <?=$summ['v_sum']?>,
   	 	            ownURL:'<?=$summ['vhl_id']?>',
   	            },
   	            <?php endforeach;?>
        	],
        dataLabels: {
            enabled: true,
            rotation: -90,
            color: '#FFFFFF',
            align: 'right',
            format: '{point.y:.1f}', // one decimal
            y: 10, // 10 pixels down from the top
            style: {
                fontSize: '13px',
                fontFamily: 'Verdana, sans-serif'
            }
        }
    }]
});

Highcharts.chart('container-ncomm', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Maintenence expenses - Non Commercial'
    },
    xAxis: {
        type: 'category',
        labels: {
            rotation: -45,
            style: {
                fontSize: '13px',
                fontFamily: 'Verdana, sans-serif'
            }
        }
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Expense'
        }
    },
    legend: {
        enabled: false
    },
    tooltip: {
        pointFormat: 'RO : <b>{point.y:.1f} Rial</b>'
    },

    plotOptions: {
    	column: {
            allowPointSelect: true,
            cursor: 'pointer',
            events:{
                click: function (event) {
                	getOpener ('wide',baseurl+'erp_report/expense/expense/f_mainhead/3/f_vehicle/'+event.point.ownURL);
                }
            },  
        }
    },

    
    series: [{
        name: 'Expense',
        data: 
            [<?foreach ($nonVhlExpSumm as $summ):?>       
   	            {
   	                name: '<?=$summ['vhl_no']?>',
   	                y: <?=$summ['v_sum']?>,
   	 	            ownURL:'<?=$summ['vhl_id']?>',
   	            },
   	            <?php endforeach;?>
        	],
        dataLabels: {
            enabled: true,
            rotation: -90,
            color: '#FFFFFF',
            align: 'right',
            format: '{point.y:.1f}', // one decimal
            y: 10, // 10 pixels down from the top
            style: {
                fontSize: '13px',
                fontFamily: 'Verdana, sans-serif'
            }
        }
    }]
});

*/ ?>
</script>

