<div class="dynamic-popup" id="dynamic-popup">
	<!--  -->
	<form name="form" method="post" id="edit"
		action='erp_vehicle/master/status/ref/<?=$this->param['ref']?>'
		style="margin-bottom: 0px;">
		<div class="modal-header">
			<h4 class="card-title">Vehicle Status</h4>
			<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		<div class="modal-body">
		<?php if($this->propertyDet['psts_prop_id']):?>
			<table class="table table-bordered">
				<tr>
					<th>Reg No. </th>
					<th>Property No</th>
					<th>File No</th>
				</tr>
				<tr>
					<th><?=$this->propertyDet['bld_name']?></th>
					<th><?=$this->propertyDet['prop_no']?></th>
					<th><?=$this->propertyDet['prop_fileno']?></th>
				</tr>
			</table>
		<?php endif?>
			<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-3 form-label" >Status</label>
					<div class="col-sm-9">
                    <?=$this->form->status->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Update</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '40%');
})
</script>
