<div class="dynamic-popup" id="dynamic-popup">
		<form name="form" method="post" id="edit" name="edit" action='erp_vehicle/master/vhldocsdelete/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
		<div class="modal-header">
			<h4 class="card-title">Delete document form the system</h4>
			<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		<div class="modal-body">
	<div class="modal-body">
		<b>Document : <?=$this->documentDetail['doc_no']?></b>
		</br>
		The delete action cannot be revert !!,
			Are you sure to delete the document permanently from the system?
		</br>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Confirm</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>
