<div class="main-container container">
	<div class="page-header"
		style="margin-bottom: 0.5rem; margin-top: 0.5rem;">
		<div>
			<h1 class="page-title">
                <?=$this->vehicleDetail['vhl_no']?>&nbsp;/
                <?=$this->vehicleDetail['type_name']?>&nbsp;/
                <?=$this->vehicleDetail['vhl_model']?>
            </h1>
		</div>
		<div class="ms-auto pageheader-btn">
            <?=x(array('link'=>'erp_vehicle/master/list','label'=>'<button class="btn btn-info pull-right" style="margin-bottom: 10px;    margin-right: 1em; ">Back</button>'))?>
            <?=x(array('link'=>'erp_masters/item/srvadd','label'=>'<button class="btn btn-success pull-right" style="margin-right: 5px;">+Item</button>',array("param"=>'class="facebox"')))?>
        </div>
	</div>
	<div class="row row-sm">
		<div class="row row-sm">
			<div class="col-xxl-4 col-xl-12">
				<div class="card custom-card">
					<div class="card-body">
                        <?php if(count($this->contractList)>0):?>
                        <div class="col-md-12 card">
							<div
								style="display: inline-block; width: 100%; overflow-y: auto;">
								<ul class="timeline timeline-horizontal"
									style="padding-top: 0px; margin-bottom: -26px;">
                                    <?php foreach ($this->contractList as $contr):?>
                                    <li class="timeline-item">
                                        <?php if($contr['emc_status']==1):?>
                                        <div
											class="timeline-badge danger ">
											<i class="glyphicon glyphicon-road"></i>
										</div>
                                        <?php endif?>
                                        <?php if($contr['emc_status']==2):?>
                                        <div
											class="timeline-badge primary ">
											<i class="glyphicon glyphicon-check"></i>
										</div>
                                        <?php endif?>
                                        <div class="timeline-panel">
											<div class="timeline-heading">
												<h5 class="timeline-title">
                                                    <?=$contr['cust_name']?>
                                                </h5>
												<p>
													<i class="glyphicon glyphicon-time"></i>
                                                    <?=$contr['sts_start_date']?> -
                                                    <?=$contr['sts_end_date']?>
                                                </p>
											</div>
											<div class="timeline-body">
												<p>Employee:&nbsp;
                                                    <?=ucwords(strtolower($contr['emp_name']))?>
                                                </p>
												<p>
                                                    <?if($contr['emc_note']):?>
                                                    <?=ucfirst(strtolower($contr['emc_note']))?>
                                                    <?php endif;?>
                                                </p>
												<p>Work:&nbsp;
                                                    <?=ucfirst(strtolower($contr['emc_location']))?> -
                                                    <?=ucfirst(strtolower($contr['emc_project']))?>
                                                </p>
												<p>
                                                    <?if($contr['emc_note2']):?>
                                                    <?=ucfirst(strtolower($contr['emc_note2']))?>
                                                    <?php endif;?>
                                                </p>
											</div>
										</div>
									</li>
                                    <?php endforeach;?>
                                </ul>
							</div>
						</div>
                        <?php endif?>
                        <div class="col-12">
							<ul class="nav nav-tabs tab-style-1 d-sm-flex d-block"
								role="tablist">
								<li class="nav-item" role="presentation"><a
									class="nav-link active" data-bs-toggle="tab"
									data-bs-target="#Summary" aria-current="page" href="#Summary"
									aria-selected="true" role="tab">Summary</a></li>
								<li class="nav-item" role="presentation">
                                    <?=accx('erp_vehicle/master/vhldocs', '<a class="nav-link ' . @$this->profile_class . ' "
                                  data-bs-toggle="tab" href="#menu2" data-bs-target="#menu2" onclick= "getContent(\'' . APPURL . 'erp_vehicle/master/vhldocs\',\'' . $this->param['ref'] . '\',\'menu2\')" aria-selected="false" role="tab" tabindex="-1">Documents</a>');?>
                                </li>
							</ul>
						</div>
						<div class="tab-content mb-3">
							<div class="tab-pane active show" id="Summary" role="tabpanel">
								<div class="panel-group1" id="accordion1">
									<div class="panel panel-default mb-4">
										<div class="panel-heading1">
											<h4 class="panel-title1">
												<a class="accordion-toggle collapsed"
													data-bs-toggle="collapse" data-bs-parent="#accordion"
													href="#collapseFive" aria-expanded="false">Vehicle
													Information</a>
											</h4>
										</div>
										<div id="collapse1" class="panel-collapse">
											<div class="panel-body">
												<table class="table table-bordered"
													style="max-width: 60%; float: left;">
													<thead>
														<tr>
															<th>Vehicle No</th>
															<th>
                                                                <?=$this->vehicleDetail['vhl_no']?>
                                                            </th>
														</tr>
														<tr>
															<th>Type</th>
															<th>
                                                                <?=$this->vehicleDetail['type_name']?>
                                                            </th>
														</tr>
														<tr>
															<th>Model</th>
															<th>
                                                                <?=$this->vehicleDetail['vhl_model']?>
                                                            </th>
														</tr>
														<tr>
															<th>Company</th>
															<th>
                                                                <?=$this->vehicleDetail['comp_name']?>
                                                            </th>
														</tr>
														<tr>
															<th>Manufacturer</th>
															<th>
                                                                <?=$this->man[$this->vehicleDetail['vhl_man']]?>
                                                            </th>
														</tr>
														<tr>
															<th>Remarks</th>
															<th>
                                                                <?=$this->vehicleDetail['vhl_remarks']?>
                                                            </th>
														</tr>
														<tr>
															<th>File No.</th>
															<th>
                                                                <?=$this->vehicleDetail['vhl_fileno']?>
                                                            </th>
														</tr>
														<tr>
															<th>Rate - Hourly</th>
															<th>
                                                                <?=$this->vehicleDetail['vhl_rate_hour']?>
                                                            </th>
														</tr>
														<tr>
															<th>Rate - Day</th>
															<th>
                                                                <?=$this->vehicleDetail['vhl_rate_date']?>
                                                            </th>
														</tr>
														<tr>
															<th>Rate - Monthly</th>
															<th>
                                                                <?=$this->vehicleDetail['vhl_rate_month']?>
                                                            </th>
														</tr>
														<tr>
															<th>Employee</th>
															<th>
                                                                <?=$this->vehicleDetail['emp_name']?>
                                                            </th>
														</tr>
														<tr>
															<th>Customer</th>
															<th>
                                                                <?=$this->vehicleDetail['cust_name']?>
                                                            </th>
														</tr>
														<tr>
															<th>Site</th>
															<th>
                                                                <?=$this->vehicleDetail['vhl_site']?>
                                                            </th>
														</tr>
													</thead>
												</table>
												
												<div>
                                                    <?=x(array('link'=>'erp_vehicle/services/vhlservice','ref'=>$this->param['ref'],'label'=>'<button class="btn btn-success pull-right"> Vehicle Service</button>',array("param"=>'class="facebox"')))?>
                                                    <table class=""
														style="max-width: 40%; display: table;">
														<thead>
															<tr>
																<th class="center">
																	<div>
																		<img alt=""
																			src="<?=IMAGEURL?><?=$this->encode($this->vhlImage['file_id']);?>"
																			width="300">
																	</div>
																</th>
															</tr>
														</thead>
													</table>
												</div>
												<div style="display: table; width: 100%;">
													<label>Documets Details</label>
													<table class="table table-bordered">
														<thead>
															<tr>
																<th width="8%" class="center">Document Type.</th>
																<th width="5%" class="center">Doc No.</th>
																<th width="15%" class="center">Desc</th>
																<th width="7%" class="center">Issue Date</th>
																<th width="7%" class="center">Expiry Date</th>
																<th width="5%" class="center">View</th>
																<th width="5%" class="center">Edit</th>
																<th width="5%" class="center">Download</th>
															</tr>
														</thead>
														<tbody>
                                                            <?php

                                                            foreach ($this->vhlDocs as $doc) :
                                                                $doi = DateTime::createFromFormat(DFS_DB, $doc['doc_issue_date']);
                                                                $doi = $doi->format(DF_DD);
                                                                $doe = DateTime::createFromFormat(DFS_DB, $doc['doc_expiry_date']);
                                                                $doe = $doe->format(DF_DD);
                                                                $encFileId = $this->encode($doc['file_id']);
                                                                $encDocId = $this->encode($doc['doc_id']);
                                                                ?>
                                                            <tr>
																<td>
                                                                    <?=x(array('link'=>'erp_vehicle/master/vhldocsview','ref'=>$encDocId,'label'=>$this->docMst[$doc['doc_type']],array("param"=>'class="facebox"')))?>
                                                                </td>
																<td>
                                                                    <?=$doc['doc_no']?>
                                                                </td>
																<td>
                                                                    <?=$doc['doc_desc']?>
                                                                </td>
																<td class="center">
                                                                    <?=$doi?>
                                                                </td>
																<td class="center">
                                                                    <?=$doe?>
                                                                </td>
																<td class="center">
                                                                    <?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>'<i class="fas fa-search"></i>',array("exten"=>$doc['file_exten'])))?>
                                                                </td>
																<td class="center">
                                                                    <?=x(array('link'=>'erp_vehicle/master/vhldocsedit','ref'=>$encDocId,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>
                                                                </td>
																<td class="center">
                                                                    <?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>'<i class="glyphicon glyphicon-download-alt text-info"></i>',array("param"=>'opener')))?>
                                                                </td>
															</tr>
                                                            <?php endforeach;?>
                                                        </tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
                                    <?php if (count($this->vhlService)>0):?>
                                    <div class="panel panel-default mb-4">
									<div class="panel-heading1">
										<h4 class="panel-title1">
											<a class="accordion-toggle collapsed"
												data-bs-toggle="collapse" data-bs-parent="#accordion"
												href="#collapseTwo" aria-expanded="false">Service Details</a>
										</h4>
									</div>
									<div id="collapseTwo" class="panel-collapse collapse"
										role="tabpanel" aria-expanded="false">
										<div class="panel-body">
                                                <?php foreach ($this->vhlService as $status):?>
                                                <div class="card"
													style="padding: 10px;">
													<table class="table table-bordered table-service">
														<thead>
														</thead>
														<tbody>
                                                            <?php $encVhlSerId = $this->encode($status['srv_id']);?>
                                                            <tr
																style="border-bottom-style: double; border-bottom-width: 4px;">
																<td colspan="4" align=""><b>Date of Service:
                                                                        <?=$status['srv_date_start']?></b></td>
																<td colspan="4" align=""><b>Service Type:
                                                                        <?=$status['srv_type']?></b></td>
															</tr>
															<tr>
																<th class="center" width="5%">Reading</th>
																<th class="center" width="8%">Location</th>
																<th class="center" width="8%">By</th>
																<th class="center" width="4%">Wash</th>
																<th class="center" width="4%">Greese</th>
																<th class="center" width="15%">Note</th>
																<th class="center" width="12%">Next Service</th>
																<th class="center" width="3%">Edit</th>
															</tr>
															<tr>
																<td align="center">
                                                                    <?=$status['srv_reading']?>
                                                                </td>
																<td align="center">
                                                                    <?=$status['srv_location']?>
                                                                </td>
																<td align="center">
                                                                    <?=$status['done_by']?>
                                                                </td>
																<td align="center">
                                                                    <?=$status['srv_wash']?>
                                                                </td>
																<td align="center">
                                                                    <?=$status['srv_greese']?>
                                                                </td>
																<td align="center">
                                                                    <?=$status['srv_note']?>
                                                                </td>
																<td align="center">
                                                                    <?=$status['srv_nxt_type']?> -
                                                                    <?=$status['srv_reading_next']?> -
                                                                    <?=$status['srv_date_next']?>
                                                                </td>
																<td align="center">
                                                                    <?=x(array('link'=>'erp_vehicle/services/vhlserviceedit','ref'=>$encVhlSerId,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>
                                                                </td>
															</tr>
															<tr>
																<td colspan="8">
                                                                    <?php $serDet = $this->serviceDetObj->getDetByServiceId(array('sdt_srv_id'=>$status['srv_id']));?>
                                                                    <table
																		class="table table-bordered table-service">
                                                                        <?php if (count($serDet)>0):?>
                                                                        <tr>
																			<td colspan="2" align="center"><b>Item</b></td>
																			<td colspan="2" align="center"><b>Quantity</b></td>
																			<td colspan="2" align="center"><b>Done by</b></td>
																			<td colspan="2" align="center"><b>Note</b></td>
																		</tr>
                                                                        <?php foreach ($serDet as $ser):?>
                                                                        <tr>
																			<td colspan="2" align="left">
                                                                                <?=$ser['srv_item']?>
                                                                            </td>
																			<td colspan="2" align="center">
                                                                                <?=$ser['sdt_qty']?>
                                                                            </td>
																			<td colspan="2" align="center">
                                                                                <?=$ser['done_by']?>
                                                                            </td>
																			<td colspan="2" align="left">
                                                                                <?=$ser['sdt_note']?>
                                                                            </td>
																		</tr>
                                                                        <?php endforeach;?>
                                                                        <?php endif;?>
                                                                    </table>
																</td>
															</tr>
														</tbody>
													</table>
												</div>
                                                <?php endforeach;?>
                                            </div>
										</div>
									</div>
                                    <?php endif;?>
                                </div>
							</div>
							<div class="tab-pane" id="menu2" role="tabpanel"></div>
						</div>
                        <?php
                        $UPDTYPE = UPD_TYP_VHL;
                        $UPDREFID = $this->decVhlId;
                        viewAction(array(
                            'module' => 'erp_manage',
                            'controller' => 'updates',
                            'action' => 'updates',
                            'param' => array(
                                'type' => $UPDTYPE,
                                'ref' => $UPDREFID
                            )
                        ));
                        ?>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    function togglePhoto() {
        if ($('#photo_target').is(":visible"))
            $('#photo_target').hide();
        else{
        	$('#action_target').hide();
            $('#photo_target').show();
        }
    }

    function toggleAction() {
        if ($('#action_target').is(":visible"))
            $('#action_target').hide();
        else{
        	 $('#photo_target').hide();
            $('#action_target').show();
        }
    }
    </script>
<style type="text/css">
/* Timeline */
.timeline, .timeline-horizontal {
	list-style: none;
	padding: 20px;
	position: relative;
}

.timeline:before {
	top: 40px;
	bottom: 0;
	position: absolute;
	content: " ";
	width: 3px;
	background-color: #eeeeee;
	left: 50%;
	margin-left: -1.5px;
}

.timeline .timeline-item {
	margin-bottom: 20px;
	position: relative;
}

.timeline .timeline-item:before, .timeline .timeline-item:after {
	content: "";
	display: table;
}

.timeline .timeline-item:after {
	clear: both;
}

.timeline .timeline-item .timeline-badge {
	color: #fff;
	width: 54px;
	height: 54px;
	line-height: 52px;
	font-size: 22px;
	text-align: center;
	position: absolute;
	top: 18px;
	left: 50%;
	margin-left: -25px;
	background-color: #7c7c7c;
	border: 3px solid #ffffff;
	z-index: 100;
	border-top-right-radius: 50%;
	border-top-left-radius: 50%;
	border-bottom-right-radius: 50%;
	border-bottom-left-radius: 50%;
}

.timeline .timeline-item .timeline-badge i, .timeline .timeline-item .timeline-badge .fa,
	.timeline .timeline-item .timeline-badge .glyphicon {
	top: 2px;
	left: 0px;
}

.timeline .timeline-item .timeline-badge.primary {
	background-color: #1f9eba;
}

.timeline .timeline-item .timeline-badge.info {
	background-color: #5bc0de;
}

.timeline .timeline-item .timeline-badge.success {
	background-color: #59ba1f;
}

.timeline .timeline-item .timeline-badge.warning {
	background-color: #d1bd10;
}

.timeline .timeline-item .timeline-badge.danger {
	background-color: #ba1f1f;
}

.timeline .timeline-item .timeline-panel {
	position: relative;
	width: 46%;
	float: left;
	right: 16px;
	border: 1px solid #c0c0c0;
	background: #ffffff;
	border-radius: 2px;
	padding: 14px;
	-webkit-box-shadow: 0 1px 6px rgba(0, 0, 0, 0.175);
	box-shadow: 0 1px 6px rgba(0, 0, 0, 0.175);
}

.timeline .timeline-item .timeline-panel:before {
	position: absolute;
	top: 26px;
	right: -16px;
	display: inline-block;
	border-top: 16px solid transparent;
	border-left: 16px solid #c0c0c0;
	border-right: 0 solid #c0c0c0;
	border-bottom: 16px solid transparent;
	content: " ";
}

.timeline .timeline-item .timeline-panel .timeline-title {
	margin-top: 0;
	color: inherit;
}

.timeline .timeline-item .timeline-panel .timeline-body>p, .timeline .timeline-item .timeline-panel .timeline-body>ul
	{
	margin-bottom: 0;
}

.timeline .timeline-item .timeline-panel .timeline-body>p+p {
	margin-top: 5px;
}

.timeline .timeline-item:last-child:nth-child(even) {
	float: right;
}

.timeline .timeline-item:nth-child(even) .timeline-panel {
	float: right;
	left: 16px;
}

.timeline .timeline-item:nth-child(even) .timeline-panel:before {
	border-left-width: 0;
	border-right-width: 14px;
	left: -14px;
	right: auto;
}

.timeline-horizontal {
	list-style: none;
	position: relative;
	padding: 20px 0px 20px 0px;
	display: inline-block;
}

.timeline-horizontal:before {
	height: 3px;
	top: auto;
	bottom: 26px;
	left: 56px;
	right: 0;
	width: 100%;
	margin-bottom: 20px;
}

.timeline-horizontal .timeline-item {
	display: table-cell;
	height: 280px;
	width: 20%;
	min-width: 320px;
	float: none !important;
	padding-left: 0px;
	padding-right: 20px;
	margin: 0 auto;
	vertical-align: bottom;
}

.timeline-horizontal .timeline-item .timeline-panel {
	top: auto;
	bottom: 64px;
	display: inline-block;
	float: none !important;
	left: 0 !important;
	right: 0 !important;
	width: 100%;
	margin-bottom: 20px;
}

.timeline-horizontal .timeline-item .timeline-panel:before {
	top: auto;
	bottom: -16px;
	left: 28px !important;
	right: auto;
	border-right: 16px solid transparent !important;
	border-top: 16px solid #c0c0c0 !important;
	border-bottom: 0 solid #c0c0c0 !important;
	border-left: 16px solid transparent !important;
}

.timeline-horizontal .timeline-item:before, .timeline-horizontal .timeline-item:after
	{
	display: none;
}

.timeline-horizontal .timeline-item .timeline-badge {
	top: auto;
	bottom: 0px;
	left: 43px;
}

 
.table-service td, .table-service th{
border:1px solid #a8c4ea
}

.table-service > tbody > tr > th {
  border: 1px solid #a8c4ea;
}

</style>