<div class="dynamic-popup" id="dynamic-popup">
	<!--  -->
	<form name="form" method="post" id="edit" action='erp_employee/master/empcontactedit/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Update Contact details</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-2 form-label" >Type of Contact</label>
					<div class="col-sm-4">
                    <?=$this->form->contype->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Name (C/o)</label>
					<div class="col-sm-4">
                    <?=$this->form->name->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >House Name/No.</label>
					<div class="col-sm-4">
                    <?=$this->form->house->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Street</label>
					<div class="col-sm-4">
                    <?=$this->form->street1->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Street</label>
					<div class="col-sm-4">
                    <?=$this->form->street2->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Place Name</label>
					<div class="col-sm-4">
                    <?=$this->form->place->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Locality</label>
					<div class="col-sm-4">
                    <?=$this->form->locality->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Region</label>
					<div class="col-sm-4">
                    <?=$this->form->region->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Country</label>
					<div class="col-sm-4">
                    <?=$this->form->country->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Zip Code</label>
					<div class="col-sm-4">
                    <?=$this->form->zip->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Phone No</label>
					<div class="col-sm-4">
                    <?=$this->form->phone->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Mobile No</label>
					<div class="col-sm-4">
                    <?=$this->form->mobile->show()?>
                  </div>
				</div>
				</div>
		<div class="modal-footer">
				<button type="button" class="btn btn-primary submit-alias livepost">Save
					changes</button>
				<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
		</div>
</div>
</form>	
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '60%');
})
</script>
