<div style="padding-top: 3px;">
	<a onclick="toggleAction();" href="javascript: void(0)"><button class="btn btn-success pull-right" style="margin-left: 5px;">Add Documents</button></a>
	<a onclick="togglePhoto();" href="javascript: void(0)"><button class="btn btn-success pull-right">Upload Photo</button></a>	
</div>

<div id="photo_target" class="card" style="top: 38px; margin-bottom: 40px; <?=$this->imgDisplay?>">
		<div class="card-block">
			<h5>Add Photo</h5>
			<form name="imgform" method="post" id="imgform" action='erp_employee/master/empdocs/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;" enctype="multipart/form-data">
			<div class="panel-body">
				<table style="max-width: 60%; float: left;" class="table">
					<thead>
						<tr>
							<td><?=$this->imgform->photo->show()?></td>
						</tr>
						<tr>
							<td>
								<input type="hidden" name="image" value="image">
								<button type="button" onclick="formSubmit(this,'menu2');return false;" class="btn  btn-primary" style="" 	>Upload</button>
							</td>
							</tr>
					</thead>
				</table>
				<div>
					<table class="" style="max-width: 40%; display: table;">
						<thead>
							<tr>
								<th class="center"><div>
										<img width="244" alt="" src="<?=IMAGEURL?><?=$this->encode($this->empImage['file_id']);?>">
									</div></th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
				<input type="hidden" name="tab" value="doc">
			</form>
		</div>
</div>	
<div id="action_target" class="card" style="top: 38px; margin-bottom: 40px; <?=$this->docDisplay?>">
		<div class="card-block">
			<h5>Add Documents</h5>
			<form name="docform" method="post" id="docform" action='erp_employee/master/empdocs/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;" enctype="multipart/form-data">
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-2 form-label" >Document Type</label>
					<div class="col-sm-4">
                    <?=$this->form->doctype->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Document No.</label>
					<div class="col-sm-4">
                    <?=$this->form->docno->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Description</label>
					<div class="col-sm-4">
                    <?=$this->form->docdesc->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Remarks</label>
					<div class="col-sm-4">
                    <?=$this->form->docremark->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Issue Authority</label>
					<div class="col-sm-4">
                    <?=$this->form->auth->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Date of apply</label>
					<div class="col-sm-4">
                    <?=$this->form->doa->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Date of Issue</label>
					<div class="col-sm-4">
                    <?=$this->form->doi->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Date of expiry</label>
					<div class="col-sm-4">
                    <?=$this->form->doe->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Upload Document</label>
					<div class="col-sm-4">
                    <?=$this->form->my_files->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Alert days</label>
					<div class="col-sm-4">
                    <?=$this->form->alert->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<div class="col-md-9"></div>
					<div class="col-md-3">	
						<button type="button" onclick="formSubmit(this,'menu2');return false;" style="padding-left: 15px;" class="btn btn-primary pull-right">Add Document</button>
					</div>
				</div>
				<input type="hidden" name="tab" value="doc">
			</form>
		</div>
	</div>
	<div class="full-width" style="padding-top: 2px; border-bottom-width: 0px; padding-bottom: 2px;">
		<div class="col-md-13">
			<div id="accordion" class="panel-group">

					
			<?php foreach($this->docList as $docId=>$docl):?>
					
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title1">
							<a href="#collapse2" data-parent="#" data-toggle="collapse"><?=$this->doctype[$docId]?></a>
						</h4>
					</div>
					
					
    					<div class="panel-collapse" id="collapse2">
    						<div class="panel-body">
    	
    							<table class="table table-bordered">
    								<thead>
    									<tr>
    										<th width="5%"class="center"><?=$this->doctype[$docId]?> No.</th>
    										<th width="15%"class="center">Desc</th>
    										<th width="10%"class="center">Issue Date </th>
    										<th width="10%"class="center">Expiry Date</th>
    										<th width="5%"class="center">View</th>
    										<th width="5%"class="center">Delete</th>
    										<th width="5%"class="center">Download</th>
    									</tr>
    								</thead>
    								<tbody>
    								<?php foreach ($docl as $doc):
    								if($doc['doc_issue_date']){
    								    $doi = DateTime::createFromFormat(DFS_DB,$doc['doc_issue_date']);
    								$doi = $doi->format(DF_DD);}
    								$doe = DateTime::createFromFormat(DFS_DB,$doc['doc_expiry_date']);
    								$doe = $doe->format(DF_DD);
    								$encFileId1 = $this->encode($doc['file_id']);
    								$encDocId1 = $this->encode($doc['doc_id']);
    								?>
    									<tr>
    										<td><?=x(array('link'=>'erp_employee/master/empdocview','ref'=>$encDocId1,'label'=>$doc['doc_no'],array("param"=>'class="facebox"')))?></td>
    										<td><?=$doc['doc_desc']?></td>
    										<td class="center"><?=$doi?></td>
    										<td class="center"><?=$doe?></td>
    										<td class="center"> <?=x(array('link'=>'default/default/download','ref'=>$encFileId1,'label'=>'<i class="fas fa-search"></i>',array("exten"=>$doc['file_exten'])))?></td>
    										<td class="center">
    										<?if(!$delete1Off):?>
    											<?=x(array('link'=>'erp_employee/master/empdocdelete','ref'=>$encDocId1,'label'=>'<i class="glyphicon glyphicon-trash text-danger"></i>',array("param"=>'class="facebox"')))?>
    										<?endif?></td>
    										<td class="center"> <?=x(array('link'=>'default/default/download','ref'=>$encFileId1,'label'=>'<i class="glyphicon glyphicon-download-alt text-info"></i>'))?></td>
    									</tr>
    								<?php 
    								$delete1Off = true;
    								endforeach;?>
    								</tbody>
    							</table>
    	
    						</div>
    					</div>
					</div>
					<?php endforeach;?>
			</div>
		</div>
	</div>
<script type="text/javascript">           
</script>



