<div class="dynamic-popup" id="dynamic-popup">
	<!--  -->
	<form name="form" method="post" id="edit"
		action='erp_employee/master/status/ref/<?=$this->param['ref']?>'
		style="margin-bottom: 0px;">
	
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Employee Status</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
		
		
			<div class="row mb-4" style="margin-top: 15px;">
				<label class="col-sm-3 form-label">Status</label>
				<div class="col-sm-9">
                    <?=$this->form->statusType->show()?>
                  </div>
			</div>
			<div class="row mb-4" style="margin-top: 15px;">
				<label class="col-sm-3 form-label">Description</label>
				<div class="col-sm-9">
                    <?=$this->form->desc->show()?>
                  </div>
			</div>
			<div class="row mb-4" id="dt_request" class="toggler form-group row">
				<label class="col-sm-3 form-label">Date of Request</label>
				<div class="col-sm-9">
                    <?=$this->form->dtRequest->show()?>
                  </div>
			</div>
			<div class="row mb-4" id="dt_approval" class="toggler form-group row">
				<label class="col-sm-3 form-label">Date of Approval</label>
				<div class="col-sm-9">
                    <?=$this->form->dtApproval->show()?>
                  </div>
			</div>
			<div class="row mb-4" id="dt_from" class="toggler form-group row">
				<label class="col-sm-3 form-label">With effect from </label>
				<div class="col-sm-9">
                    <?=$this->form->dtWif->show()?>
                  </div>
			</div>
			<div class="row mb-4" id="dt_end" class="toggler form-group row">
				<label class="col-sm-3 form-label">End Date </label>
				<div class="col-sm-9">
                    <?=$this->form->dtEnd->show()?>
                  </div>
			</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary submit-alias livepost">Save
					changes</button>
				<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
			</div>
	</form>
</div>

<script type="text/javascript">           
$(document).ready(function() {
	initDatePicker();
	var source = '<?=APPURL?>'+ 'erp_employee/master/getlive';
	$('#company').on('change',function() {
		getJaxData($('#company').val(),'dept',source);
		$("#doi").attr("mindate",$('#doa').val());
		setDatePicker($('#doi'));
		
	});
	getJaxData($('#company').val(),'dept',source);
	toggle_field($('#statusType'));
});

function toggle_field(el){
	console.log(el);
	var type= $(el).val();
	$('.toggler').show();
	if(type == 1)
	{

	}
	else if(type==2)
	{
		$('#dt_request').hide();
		$('#dt_approval').hide();
		$('#dt_end').hide();
	}
	else if(type==3)
	{
		$('#dt_end').hide();
	
	}
	else if(type==4)
	{
		$('#dt_request').hide();
		$('#dt_approval').hide();
		$('#dt_end').hide();
	}
}
$(document).ready(function($) {
	$('.modal-dialog').css('width', '50%');
})
</script>
