<div class="dynamic-popup" id="dynamic-popup"><!--  -->
<form name="docform" method="post" id="docform" action="erp_employee/master/vehiclereg/ref/<?=$this->param['ref']?>"	style="margin-bottom: 0px;" enctype="multipart/form-data">
	<div class="modal-header">
		<button aria-label="Close" class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true">×</span></button>
		<h4 class="modal-title">Vehicle Registration Details</h4>
	</div>
	<div class="modal-body">
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-2 form-label" >Mulkia No
						</label>
					<div class="col-sm-4">
                    <?=$this->form->mulkia->show()?>
                  </div>
				<label class="col-sm-2 form-label" >Chassis No
						</label>
					<div class="col-sm-4">
                    <?=$this->form->chasis->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Reference No
						</label>
					<div class="col-sm-4">
                    <?=$this->form->refno->show()?>
                  </div>

					<label class="col-sm-2 form-label" >Remarks
						</label>
					<div class="col-sm-4">
                    <?=$this->form->remarks->show()?>
                  </div>
				</div>				
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Update</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>