<div class="card-block"
	style="padding-top: 3%; padding-left: 3%; padding-bottom: 5px; margin-top: 3%;">

	<h5 class="title-margin">
		DAY BOOK <b> </b>
		<button name="cmdPrint" value="  Print  "
			onclick="$('#report').printElement();"
			class="btn btn btn-primary pull-right"
			style="padding: 2px 12px; padding-top: 2px;">Print</button>
	</h5>

</div>
<form method="get" id="filter" name="filter"
	action='reports/rptexpense/balancesheet'>
	<div
		style="display: flex; flex-direction: row; flex-wrap: wrap; justify-content: center; align-items: center;">
		<div class="col-md-12 card"
			style="height: 100%; width: 95%; padding-left: 5px; padding-right: 5px; padding-bottom: 3%; padding-top: 6px;">
			<div class="col-md-12 card filter-card">
				<table class="" width="100%" style="margin-left: 2%;">
					<tr style="font-size: 0.8em;">
						<th class="pr_fdt" width="16%"><div class="">Date</div></th>
						<th class="pr_tdt" width="8%"><div class=""></div></th>
						<th width="20%"></th>
					</tr>
					<tr>
						<td class="pr_fdt">
							<div class="form-group">
                	<?=$this->form->f_dtfrom->show()?>
              		</div>
						</td>
						<td class="pr_tdt"></td>
						<td align="center">
							<div class="form-group ">
								<button class="btn <?=$this->filter_class?>" type="submit">View</button>
							</div>
						</td>
					</tr>
				</table>
			</div>
<?php if(count($this->trialList)>0):?>

			<div id="report">
<?php //include_once __DIR__ . '/../../../public/css/printstyle.php.css';?>
<?php include_once __DIR__ . '/../../../../public_html/asfruits/css/printstyle_rpt.php.css';?>



				
			<div  class="card" style="margin-top: 2%; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
			
				<div class="col-md-12 card">
				<div class="card-block" style="padding-top: 8%;">
					<h4 class="title-margin"><u> DAY BOOK - SUMMARY : <?=$this->title?> </u></h4>
				</div>
				</div>
			
			
				<div class="card-block" style="padding-top: 8%; padding-left: 3%;">
					<h5 class="title-margin">
						<b> Cash </b>
					</h5>
				</div>
				
								
						<?php /* v($this->trialList['sum']['0']['total_trh_coll'],
								$this->purchHistList['sum']['0']['total_payment_amt']
								,$this->expenseList['sum']['0']['total_expense_amt']) */ ?>


				<div class="" style="margin-left: 3%;">
					<b style="color: darkblue;"> Opening Balance  <i class="doubleUnderline"> <?=number_format($this->trialList['sum']['0']['total_trh_coll']- 
					($this->purchHistList['sum']['0']['total_payment_amt']+ $this->expenseList['sum']['0']['total_expense_amt']),2);?></i></b>
				</div>
				
				
				
			<div class="card-block" style="padding-top: 8%; padding-left: 3%;">
				<h5 class="title-margin">
					<b> Sales </b>
				</h5>
			</div>
				


			<?php 
			$pSalesTotal = 	$this->trialList['sum']['0'];
			$cSalesTotal= $this->trialList['upto']['0'];
			$this->trialList = $this->trialList['list'];
			$trialTotal = ($pSalesTotal['total_trh_bill'] -$pSalesTotal['total_trh_adj']) - $pSalesTotal['total_trh_coll'] ;
			?>
		
			<?php if($trialTotal<>''):?>			
			<div  class="" style="margin-left: 3%;">
				Previous Sales Outstanding : <b>  (<?=number_format($trialTotal,2);?>)</b>
			</div>
			<?php endif;?>
			
				<table class="table table-bordered  tbl_reorder rpt_frame"
					style="width: 98%; margin-bottom: 5px; margin-left: 2%; margin-right: 2%;">
					<thead>
						<tr>
							<th width="4%" class="center">Sl.</th>
							<th width="35%" class="center">Customer</th>
							<th width="15%" class="center"> Invoice Amt. </th>
							<th width="15%" class="center"> Adj Amt.</th>
							<th width="15%" class="center"> Amt Received</th>							
						</tr>
					</thead>
				<tbody>
			<?
			if (count ( $this->trialList) > 0) :
				foreach ( $this->trialList as $coll ) :?> 
						<tr>
							<td width="4%" class="center"><?=@++$offset;?></td>
							<td width="35%" align="left"><?=$coll['cust_name']?></td>
							<td width="15%" align="right"><b><?=$coll['trh_bill_total']?></b> </td>
							<td width="15%" align="right"><b><?=$coll['trh_coll_adjustment']?></b></td>
							<td width="15%" align="right"><b><?=$coll['trh_coll_amount']?></b> <?$receivedTotal+=$coll['trh_coll_amount'];?> </td>
						</tr>
				<?php endforeach ?>
			<?endif?>
			<tr>
				<td align="right" colspan="4"><b style="color: darkblue;">Total Cash Received (+) </b></td>
				<td width="15%" align="right"><b class="doubleUnderline" style="color: darkblue;"><?=number_format($receivedTotal,2)?></b> </td>
			</tr>
			
			</tbody>
		</table>
				<div class="" style="margin-left: 3%;">
					Balance Outstanding for the day: <b> (<?=number_format(($cSalesTotal['total_trh_bill'] -$cSalesTotal['total_trh_adj']) - $cSalesTotal['total_trh_coll'],2)?>)</b>
				</div>
				
				<div class="card-block" style="padding-top: 8%; padding-left: 3%;">
					<h5 class="title-margin">
						<b> Purchase </b>
					</h5>
				</div>
				


			<?php 
			$pPurchaseTotal = 	$this->purchHistList['sum']['0'];
			$cPurchaseTotal = $this->purchHistList['upto']['0'];
			$this->purchHistList = $this->purchHistList['list'];
			$trialTotal = ($pPurchaseTotal['total_prh_amt'] -$pPurchaseTotal['total_adjamt']) - $pPurchaseTotal['total_payment_amt'] ;
			?>
		
			<?php if($trialTotal<>''):?>			
			<div  class="" style="margin-left: 3%;">
				Previous Supplier Payment Pending : <b>  (<?=number_format($trialTotal,2);?>)</b>
			</div>
			<?php endif;?>
			
				<table class="table table-bordered  tbl_reorder rpt_frame"
					style="width: 98%; margin-bottom: 5px; margin-left: 2%; margin-right: 2%;">
					<thead>
						<tr>
							<th width="4%" class="center">Sl.</th>
							<th width="35%" class="center">Vendor</th>
							<th width="15%" class="center"> Purchase Amt. </th>
							<th width="15%" class="center"> Adj Amt.</th>
							<th width="15%" class="center"> Paid Amt. </th>							
						</tr>
					</thead>
				<tbody>
			<?
			
			if (count ( $this->purchHistList) > 0) :
			$offset = 0;
				foreach ( $this->purchHistList as $coll ) : ?>
				<tr>
							<td width="4%" class="center"><?=@++$offset;?></td>
							<td width="35%" align="left"><?=$coll['ven_name']?></td>
							<td width="15%" align="right"><b><?=$coll['prh_purch_total']?></b> </td>
							<td width="15%" align="right"><b><?=$coll['prh_pay_adjustment']?></b></td>							
							<td width="15%" align="right"><b><?=$coll['prh_pay_amount']?></b> <?$paidTotal+=$coll['prh_pay_amount'];?> </td>
				</tr>
				<?php endforeach ?>
							<?endif?>
			<tr>
				<td align="right" colspan="4"> <b style="color: darkblue;">Total Cash Paid (-) </b></td>
				<td width="15%" align="right"><b class="doubleUnderline" style="color: darkblue;"><?=number_format($paidTotal,2)?></b> </td>
			</tr>

			</tbody>
		</table>
				<div class="" style="margin-left: 3%;">
					Payment Pending for the Day: <b> (<?=number_format(($cPurchaseTotal['total_prh_amt'] -$cPurchaseTotal['total_adjamt']) - $cPurchaseTotal['total_payment_amt'],2)?>)</b>
				</div>
				<div class="card-block" style="padding-top: 8%; padding-left: 3%;">
					<h5 class="title-margin">
						<b> Expenses </b>
					</h5>
				</div>

			<?php 
			$prTotal = 	$this->expenseList['sum']['0'];
			$crTotal =  $this->expenseList['upto']['0'];
			$this->expenseList = $this->expenseList['list'];
			$trialTotal = $prTotal['total_expense_amt'];
			?>
	
			
		<table class="table table-bordered  tbl_reorder rpt_frame"
					style="width: 98%; margin-bottom: 5px; margin-left: 2%; margin-right: 2%;">
					<thead>
						<tr>
							<th width="4%" class="center">Sl.</th>
							<th width="20%" class="center">Vendor</th>
							<th width="20%" class="center">Main Head</th>
							<th width="33%" class="center">Category</th>
							<th width="15%" class="center">Total</th>
						</tr>
					</thead>
					<tbody>
			<?
			
			if (count ( $this->expenseList) > 0) :
				$offset = 0;
				foreach ( $this->expenseList as $coll ) :?> 
				<tr>
							<td width="4%" class="center"><?=@++$offset;?></td>
							<td width="20%" class="center"><?=$coll['ven_name'];?></td>
							<td width="20%" align="left"><?=$coll['main_head'];?></td>
							<td width="33%" class="center"><?=$coll['cat_name'];?></td>
							<td width="15%" align="right"><b><?=$coll['exp_amount']?></b> <?php $expTotal+=$coll['exp_amount'];?> </td></tr>
				<?php endforeach ?>
				<?endif?>
			<tr>
				<td align="right" colspan="4"><b style="color: darkblue;">Total Expense Amount (-)</b></td>
				<td width="15%" align="right"><b class="doubleUnderline" style="color: darkblue;"><?=number_format($expTotal,2)?></b> </td>
			</tr>

			</tbody>
		</table>
		
			<div class="card-block" style="padding-top: 2%; padding-left: 3%;">

			</div>
						<?php /* v($cSalesTotal['total_trh_coll'],
					$cPurchaseTotal['total_payment_amt'],$crTotal['total_expense_amt']) */?>
		
				<div style="margin-left: 3%;padding-bottom: 10px;">
					<b style="color: darkblue;">Closing Balance: <i class="doubleUnderline"> <?=number_format($cSalesTotal['total_trh_coll']- 
					($cPurchaseTotal['total_payment_amt']+ $crTotal['total_expense_amt']),2);?></i></b>
				</div>
				
				
			<div class="card-block" style="padding-top: 2%; padding-left: 3%;">
				<h5 class="title-margin">
					<b>  </b>
				</h5>
			</div>


				<div style="position: fixed; bottom: 0; width: 100%;">
					<table class="rpt_tbl">
						<thead>
							<tr>
								<td><div class="title-margin rpt_footer"></div></td>
							</tr>
							<tr>
								<td><div class="title-margin rpt_footer">
										<small> <br> Report Generated On : 26/02/2022 14:49:43
										</small>
									</div></td>
							</tr>
						</thead>
					</table>
				</div>

			</div>
			<?php endif;?>
			</div>
		</div>
	</div>
</form>


<script type="text/javascript">
$(".tbl_reorder").on("click",".up,.down", function () {
	  var row = $(this).parents("tr:first");
	  if($(this).is('.up')){
	    row.insertBefore(row.prev());
	  }
	  else{
	    row.insertAfter(row.next());
	  }
	});

$(document).ready(function(){
    $("#f_dtfrom").datepicker(

    		
    	    {dateFormat: 'dd/mm/yy',changeMonth: true,changeYear: true,yearRange: '-100:+0',
        onSelect: function(selected) {
          $("#f_dtto").datepicker("option","minDate", selected)
        }
    });
    $("#f_dtto").datepicker(
    		
    	    { dateFormat: 'dd/mm/yy',changeMonth: true,changeYear: true,yearRange: '-100:+0',
        onSelect: function(selected) {
           $("#f_dtfrom").datepicker("option","maxDate", selected)
        }
    });  
});

</script>


<style>
.modal-dialog {
	width: 60%;
}
</style>

