<?php
$this->modeNo = $val['modeNo'];
$f_mode = $val['f_mode'];
$mode = $val['mode'];
?>
<form method="get" id="filter" name="filter" action="<?=APPURL?>reports/rptexpense/expensecategory">
<div style="padding-left: 10px; padding-right: 10px;">
<div class="col-md-12 card filter-card">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">Report : CATEGORY WISE STATEMENT OF EXPENSE </h5>
	</div>
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="10%">Main Head</th>

				<th align="center" width="10%">Period(Month/Period)</th>
				<th class="pr_month" width="10%">Month</th>
				<th class="pr_fdt" width="10%">From</th>
				<th class="pr_tdt" width="10%">To</th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_mainhead->show()?>
              		</div>
				</td>
				<td align="center">
					<div class="form-group ">
                	<?=$this->form->f_period->show()?>
              		</div>
				</td>
				<td class="pr_month">
					<div class="form-group ">
                	<?=$this->form->f_monthpick->show()?>
              		</div>
				</td>
				<td class="pr_fdt">
					<div class="form-group ">
                	<?=$this->form->f_dtfrom->show()?>
              		</div>
				</td>
				<td class="pr_tdt">
					<div class="form-group ">
                	<?=$this->form->f_dtto->show()?>
              		</div>
				</td>
			</tr>
			<tr style="font-size: 0.8em;">
				<th width="10%">Main Cat.</th>
				<th width="10%">Sub Cat.</th>
				<th width="10%">Cat.</th>
				<th width="10%"></th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_pCatSelect->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_sCatSelect->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_cCatSelect->show()?>
              		</div>
				</td>
				<td align="center">
	              <div class="form-group ">
	              	<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
	</div>



<div class="col-md-12 card" style="height: 100%; padding-left: 5px; padding-right: 5px;">
<div id="report">
<?php include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
<?php  // include_once __DIR__ . '/../../../../public_html/asfruits/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
		<div style="margin-top: 3%;">
				<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
						<tr>
							<th width="100%">
								<table style="margin-bottom: 1px;" width="100%">
									<tbody>
										<tr>
											<th width="12%">
												<div class="title-margin" style="">
												<img alt="" src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/babana1.png" style="margin-top: 2px;margin-left: 1px;width: 80%;padding-left: 2%;">
												</div>
											</th> 
										
											<th colspan="2" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="60%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">A.S.  	 BANANA MERCHANT
													</div>
											</th>
											<th colspan="" style="padding-left: 1px; font-family: Tahoma; text-align: center;" width="10%">
												<div style="font-size: 25px; transform: scale(1, 2); font-family: f1; font-family: Times;">
													</div>
											</th>
										</tr>
									</tbody>
								</table>
							</th>
						</tr>
						<tr>
							<td width="22%" colspan="4" align="center">
								<div style="font-size: 15px; transform: scale(1, 2); font-family: f1; font-family: Times;"><?=@$_SESSION ['COMP_LABL2']?>
									</div>
							</td>
						</tr>
						<tr>
							<th class="empty" colspan="10"
								style="border-top: 1px solid black;">
								<table class="rpt_tbl" style="margin-top: 13px;">
									<tr style="border: medium none;">
										<th style="border: medium none;"><div class="center"
												style="width: 96%;">CATEGORY WISE STATEMENT OF EXPENSE</div></th>
									</tr>
								</table>

							</th>
						</tr>
							</thead>
						</table>
					</div>
		</div>
		<table class="rpt_frame">
			<thead>
				<tr>
					<td class="empty" colspan="4" style="border: 1px solid white;">
					</td>
					<td class="empty" colspan="2" style="border: 1px solid white;">
					<?php $date = new DateTime();$date = $date->format('d/m/Y')?>
					Date : <?=$date;?></td>
				</tr>
				<tr>
					<th class="empty" colspan="6"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="12%"class="center">Main Head</th>
					<th width="9%" class="center">Main Category</th>
					<th width="9%" class="center">Sub Category</th>
					<th width="9%" class="center">Category</th>
					<th width="4%" class="center">Amount</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->expenseList)>0):?>
				<?php foreach($this->expenseList as $expense):
				//$encExpId = $crypt->encode($expense['exp_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$expense['main_head_txt']?>
					</td>
					<td><?=$expense['pcat']?></td>
					<td><?=$expense['scat']?></td>
					<td><?=$expense['ccat']?></td>
					<td align="right">
					<?$sum+=$expense['sum'];?>	<?=$expense['sum'];?>			
					</td>
				</tr>
				<?php endforeach?>
				<tr>
				<th colspan="5"> Total:</th>
				<th style="text-align: right;"> <?=number_format($sum,3)?></th>
				</tr>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>Expense MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</div>
</form>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
	toggledtoptions();
	/*$('#id_dtdys').hide();
	$('#id_days').hide();
	$('#id_date').hide();*/

	
	$('#f_period1').on('click',function() {
		toggledtoptions();
	});

	$('#f_period2').on('click',function() {
		toggledtoptions();
	});
});

function toggledtoptions(){
	//$('#f_monthpick').val('');
	//$('#pr_fdt').val('');
	//$('#pr_fdt').val('');
	if($('#f_period1').is(':checked')){
		$('.pr_month').show();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
	else if($('#f_period2').is(':checked')){
		$('.pr_month').hide();
		$('.pr_fdt').show();
		$('.pr_tdt').show();
	}
	else{
		$('.pr_month').hide();
		$('.pr_fdt').hide();
		$('.pr_tdt').hide();
	}
}
  
$(document).ready(function() {
	var source = '<?=APPURL?>'+ 'accounts/expense/getlive/ajax/ajax/type/filter';
	$('#f_pCatSelect').on('change',function() {
		getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');
		$('#f_cCatSelect').empty();
	});
	getJaxData($('#f_pCatSelect').val(),'f_sCatSelect',source,'parent');

	$('#f_sCatSelect').on('change',function() {
		getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
	});
	getJaxData($('#f_sCatSelect').val(),'f_cCatSelect',source,'sub');
});

</script>
