<div class="card-block"
	style="padding-top: 3%; padding-left: 3%; padding-bottom: 5px; margin-top: 3%;">

	<h5 class="title-margin">
		STOCK SUMMARY <b> </b>
		<button name="cmdPrint" value="  Print  "
			onclick="$('#report').printElement();"
			class="btn btn btn-primary pull-right"
			style="padding: 2px 12px; padding-top: 2px;">Print</button>
	</h5>

</div>
<form method="get" id="filter" name="filter"
	action='reports/rptexpense/inventory'>
	<div
		style="display: flex; flex-direction: row; flex-wrap: wrap; justify-content: center; align-items: center;">
		<div class="col-md-12 card"
			style="height: 100%; width: 95%; padding-left: 5px; padding-right: 5px; padding-bottom: 3%; padding-top: 6px;">
			<div class="col-md-12 card filter-card">
				<table class="" width="100%" style="margin-left: 2%;">
					<tr style="font-size: 0.8em;">
						<th class="pr_fdt" width="16%"><div class="">Date</div></th>
						<th class="pr_tdt" width="8%"><div class=""></div></th>
						<th width="20%"></th>
					</tr>
					<tr>
						<td class="pr_fdt">
							<div class="form-group">
                	<?=$this->form->f_dtfrom->show()?>
              		</div>
						</td>
						<td class="pr_tdt"></td>
						<td align="center">
							<div class="form-group ">
								<button class="btn <?=$this->filter_class?>" type="submit">View</button>
							</div>
						</td>
					</tr>
				</table>
			</div>
			<div id="report">
<?php //include_once __DIR__ . '/../../../public/css/printstyle.php.css';?>
<?php include_once __DIR__ . '/../../../../public_html/asfruits/css/printstyle_rpt.php.css';?>



				
			<div  class="card" style="margin-top: 2%; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
			
				<div class="col-md-12 card">
				<div class="card-block" style="padding-top: 8%;">
					<h4 class="title-margin"><u> STOCK - SUMMARY : <?=$this->title?> </u></h4>
				</div>
				</div>
				
		<table class="rpt_frame" style="width: 95%;margin-left: 2%;">
			<thead>
				<tr>
					<th width="10%" class="center">Sl No</th>
					<th width="65%" class="center">Item Name</th>
					<th width="10%" class="center">Count</th>
					<th width="10%" class="center">Weight (Kg.)</th>
				</tr>
			</thead>
			<tbody>
			<?//if(count($this->inventoryList)>0):?>
				<?php foreach($this->inventoryList as $bill):?>
				<tr>
					<td class="center"><?=@++$ioffset;?></td>
					<td align="left"><span style="font-size: large;" > <?=$bill['item_name']?></span></td>
					<td align="center"><?=$bill['count_balance']; $cnttotal+=$bill['count_balance'];?></td>
					<td align="right"><?=number_format($bill['qty_balance'],2); $qtotal+=$bill['qty_balance'];?></td>

				</tr>
				<?php endforeach?>
				<tr><td colspan="2" align="right"><b> Total:</b> </td>
					<td align="center"> <b><?=$cnttotal;?></b></td>
					<td align="right"> <b><?=number_format($qtotal,2)?></b></td>
				</tr>
			<?//endif?>
			</tbody>
		</table>



				<div style="position: fixed; bottom: 0; width: 100%;">
					<table class="rpt_tbl">
						<thead>
							<tr>
								<td><div class="title-margin rpt_footer"></div></td>
							</tr>
							<tr>
								<td><div class="title-margin rpt_footer">
										<small> <br> Report Generated On : 26/02/2022 14:49:43
										</small>
									</div></td>
							</tr>
						</thead>
					</table>
				</div>

			</div>
				</div>
		</div>
	</div>
</form>


<script type="text/javascript">


$(document).ready(function(){
    $("#f_dtfrom").datepicker(
    	    {dateFormat: 'dd/mm/yy',changeMonth: true,changeYear: true,yearRange: '-100:+0',
        onSelect: function(selected) {
          $("#f_dtto").datepicker("option","minDate", selected)
        }
    }); 
});

</script>


<style>
.modal-dialog {
	width: 60%;
}
</style>
