<div class="card-block" style="padding-top: 2%;">
	<div class="full-width">
		<?=x(array('link'=>'erp_masters/customer/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')))?>
	</div>
	<h5 class="title-margin">List of Customers</h5>
</div>
<form method="get" id="filter" name="filter" action="list">
	<div class="col-md-12 card filter-card">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="24%">Code</th>
				<th>Customer: Company</th>
				<th>Name</th>
				<th>Address</th>
			</tr>
			<tr>
				<td width="24%">
					<div class="form-group ">
                	<?=$this->form->f_code->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_customer->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_name->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_house->show()?>
              		</div>
				</td>
				<td width="15%" align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
	</div>

<div class="col-md-12">
	<div class="card">
		<table class="table table-bordered grid">
			<thead>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="9%" class="center">Code</th>
					<th width="15%" class="center">Customer:Company</th>
					<th width="15%" class="center">Name</th>
					<th width="15%" class="center">Address</th>
					<th width="15%" class="center">Mobile</th>
					<th width="10%" class="center">Edit</th>
					<th width="6%" class="center">View</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->customerList)>0):?>
				<?php foreach($this->customerList as $customer):
					$encCustId = $this->encode($customer['cust_id']);
				?>
				<tr>
					<td class="center"><?=@++$this->offset;?></td>
					<td><?=$customer['cust_id']?></td>
					<td><?=$customer['cust_name']?></td>
					<td><?=$customer['con_name']?></td>
					<td><?=$customer['con_house']?></td>
					<td><?=$customer['con_mobile']?></td>
					<td class="center">
						<?=x(array('link'=>'erp_masters/customer/edit','ref'=>$encCustId,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>  
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_masters/customer/view','ref'=>$encCustId,'label'=>'<i class="fas fa-search"></i>'))?> 
					</td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?$this->customerObj->pagination();?>
	</div>
</div>
</form>
