<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">Report: Vehicle</h5>
	</div>	
		<form method="get" id="filter" name="filter" action="">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="8%">No</th>
				<th>Type</th>
				<th  width="15%">Employee</th>
				<th  width="20%">Customer</th>
				<th width="15%">Status</th>
			</tr>
			<tr>
				<td width="8%">
					<div class="form-group ">
                	<?=$this->form->f_vhlno->show()?>
              		</div>
				</td>
				<td width="5%">
					<div class="form-group ">
                	<?=$this->form->f_type->show()?>
              		</div>
				</td>
				<td  width="15%">
					<div class="form-group ">
                	<?=$this->form->f_name->show()?>
              		</div>
				</td>
				<td  width="20%">
					<div class="form-group ">
                	<?=$this->form->f_customer->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_status->show()?>
              		</div>
				</td>
				<td width="15%" align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
	</div>

<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
				<thead>
					<tr>
						<th width="1%" rowspan="3">
							<div class="title-margin">
								<img width="50" alt=""
									src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
									style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
							</div>
						</th>
					</tr>
					<tr>
						<th ><div class="center" style="width: 79%;">Abdullah
								Salem Trading Est</div></th>
					</tr>
					<tr>
						<th width=""><div class="center"
								style="margin-top: 0px; margin-bottom: 10px; width: 79%;">Vehicle Employee Contract Report</div></th>
					</tr>
				</thead>
			</table>
		</div>
		<table class="rpt_frame">
			<thead>
				<tr>
					<th class="empty" colspan="11"></th>
				</tr>			
				<tr>
					<th width="3%" class="center">Sl.</th>
					<th width="4%" class="center">Vehicle</th>
					<th width="4%" class="center">Type</th>
					<th width="10%" class="center">Customer</th>
					<th width="10%" class="center">Employee</th>
					<th width="4%" class="center">Start Date</th>
					<th width="4%" class="center">End Date</th>
					<th width="3%" class="center">Status</th>
					<th width="5%" class="center">Project</th>
					<th width="5%" class="center">Location</th>
					<th width="10%" class="center">Note</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->contractList)>0):?>
				<?php foreach($this->contractList as $vehivle):
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$vehivle['vhl_no']?></td>
					<td><?=$vehivle['type_name']?></td>
					<td><?=$vehivle['cust_name']?></td>
					<td><?=$vehivle['emp_name']?></td>
					<td align="center" ><?=$vehivle['sts_start_date']?></td>
					<td align="center" ><?=$vehivle['sts_end_date']?></td>
					<td align="center" ><?=$vehivle['status']?></td>					
					<td><?=$vehivle['emc_project']?></td>
					<td><?=$vehivle['emc_location']?></td>
					<td><?=$vehivle['emc_note']?></td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>Vehicle MIS Report - Vehicle Employee Contract (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</div>
</form>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
</script>

