<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">Report: <?=$this->title?></h5>
	</div>
	<form method="get" id="filter" name="filter" action="">
	<?php if($ref==''):?>
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="24%">No</th>
				<th>Type</th>
				<th>Model</th>
				<th>Company</th>
				<th width="15%">Expiry Month</th>
			</tr>
			<tr>
				<td width="24%">
					<div class="form-group ">
                	<?=$this->form->f_vhlno->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_type->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_model->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_company->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group">
                	<?=$this->form->f_monthpick->show()?>
              		</div>
				</td>
				<td align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
		<?php endif?>
		</form>
	</div>

<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
				<thead>
					<tr>
						<th width="1%" rowspan="3">
							<div class="title-margin">
								<img width="50" alt=""
									src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
									style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
							</div>
						</th>
					</tr>
					<tr>
						<th ><div class="center" style="width: 79%;">Abdullah
								Salem Trading Est</div></th>
					</tr>
					<tr>
						<th width=""><div class="center"
								style="margin-top: 0px; margin-bottom: 10px; width: 79%;"><?=$this->title;?></div></th>
					</tr>
				</thead>
			</table>
		</div>
		<table class="rpt_frame">
			<thead>
				<tr>
					<th class="empty" colspan="11"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="9%" class="center">Vehicle No</th>
					<th width="9%" class="center">File No</th>
					<th width="15%" class="center">Type</th>
					<th width="15%" class="center">Model</th>
					<th width="5%" class="center">Company</th>
					<th width="6%" class="center">Doc No</th>
					<th width="6%" class="center">Issue Date</th>
					<th width="6%" class="center">Expiry Date</th>
				</tr>
			</thead>
			<tbody>
			
			<?if(count($this->vehicleList)>0):?>
				<?php foreach($this->vehicleList as $vehicle):
					if ($ref!='') {
						if ($vehicle ['doc_type'] == 3)
							$tpropPropList [$vehicle ['vhl_id']] = $vehicle ['doc_type'];
						
						if ($vehicle ['doc_type'] == 2) {
							if (isset ( $tpropPropList [$vehicle ['vhl_id']] ))
								continue;
						}
					}
				
				
				$encvhlId = $this->encode($vehicle['vhl_id']);
				$encFileId = $this->encode($vehicle['file_id']);
				//s($vehicle);
				
				?>
				<?php if($grouph!=$vehicle['doc_type']):?>
				<tr><td colspan="10"><b>&nbsp;&nbsp;<?=$this->docMst[$vehicle['doc_type']]?></b></td></tr>
				<?php $sl = 1;?>
				<?php endif;?>
				<tr>
					<td class="center"><?=@$sl++;?></td>
					<td><?=x(array('link'=>'erp_vehicle/master/view','ref'=>$encvhlId,'label'=>$vehicle['vhl_no']))?> </td>
					<td><?=$vehicle['vhl_fileno']?></td>
					<td><?=$vehicle['type_name']?></td>
					<td><?=$vehicle['vhl_model']?></td>
					<td><?=$vehicle['comp_disp_name']?></td>
					<td align="center"><?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>$vehicle['doc_no'],array("exten"=>$vehicle['file_exten'])))?>
					</td>
					<td><?=$vehicle['doc_issue_date']?></td>
					<td><?=$vehicle['doc_expiry_date']?></td>
				</tr>
				<?php $grouph=$vehicle['doc_type'];?>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
				<tr><td>&nbsp;</td></tr>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y H:i')?>
						<td><div class="title-margin rpt_footer"><small><?=$this->title;?></small></div><div class="rpt_footer" style="float: right;"><small>(<?=$date?>)</small></div></td>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</div>
</form>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
</script>

