<?

if ($formRender):?>

<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" name="edit" action='users/<?=APPURL?>manage/compdept/edit/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true">×</span></button>
		<h4 class="modal-title">Update user details</h4>
	</div>
	<div class="modal-body">
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >First
						Name</label>
					<div class="col-sm-9">
                    <?=$this->form->fname->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Last
						Name</label>
					<div class="col-sm-9">
                    <?=$this->form->lname->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >User
						Name</label>
					<div class="col-sm-9">
                    <?=$this->form->uname->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Designation</label>
					<div class="col-sm-9">
                    <?=$this->form->desig->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Department</label>
					<div class="col-sm-9">
                    <?=$this->form->dept->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Status</label>
					<div class="col-sm-9">
                    <?=$this->form->status->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Update</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>

<?endif?>
