<td colspan="12">
	<div class="full-width"
		style="padding-top: 2px; border-bottom-width: 0px; padding-left: 5px;">
		<div class="col-md-13">
			<div id="accordion" class="panel-group">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title1"> <?=$this->versionsDocs['0']['doc_dyn_label']?></h4>
					</div>
					<div class="panel-collapse" id="collapse2">
						<div class="panel-body">

							<table aria-describedby="" class="table table-bordered no-footer">
								<thead class="border-top">
									<tr role="row">
										<th width="8%" class="center">Document No</th>
										<th width="8%" class="center">Issue Date</th>
										<th width="8%" class="center">Expiry Date</th>
										<th width="3%" class="center">View</th>
									</tr>
								</thead>
								<tbody>
								
								<?php foreach ($this->versionsDocs as $doc):

								$encFileId = $this->encode($doc['file_id']);
								?>
									<tr>
										<td class="center">
                                            <?=$doc['doc_no']?>
                                        </td>
										<td class="center">
                                            <?=$doc['doc_issue_date']?>
                                        </td>
										<td class="center">
                                            <?=$doc['doc_expiry_date']?>
                                        </td>
										<td >
                                            <?php if($doc['doc_id']):?>
                                            <?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>'<i class="glyphicon glyphicon-file text-info">'.$doc['file_name'].'</i>',array("param"=>'opener')))?>
                                            <?php endif;?>
                                            </td>
									</tr>
																	<?php 
								endforeach;?>
									
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</td>

