<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" id="renew" name="renew" action="erp_manage/company/renew/ref/<?=$this->param['ref']?>" enctype="multipart/form-data">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Renew Company Documents</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-2 form-label" >Company
						</label>
					<div class="col-sm-4">
                   		<?=$this->docDetails['comp_name']?>
                  </div>

					<label class="col-sm-2 form-label" >Document
						</label>
					<div class="col-sm-4">
                    	<?=$this->docDetails['doc_dyn_label']?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Document No
						</label>
					<div class="col-sm-4">
                    <?=$this->form->docno->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Details
						</label>
					<div class="col-sm-4">
                    <?=$this->form->docdesc->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Date of Issue
						</label>
					<div class="col-sm-4">
                    <?=$this->form->doi->show()?>
                  </div>
					<label class="col-sm-2 form-label" >Date of Expiry
						</label>
					<div class="col-sm-4">
                    <?=$this->form->doe->show()?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-2 form-label" >Document</label>
					<div class="col-sm-4">
                    <?=$this->form->my_files->show()?>
                  </div>

					<label class="col-sm-2 form-label" >Remainder </label>
					<div class="col-sm-4 mt-3">
                    <?=$this->form->addRemainder->show()?>
                  </div>
				</div>
		</div>
    	<div class="modal-footer">
    		<button type="button" class="btn btn-primary submit-alias livepost" >Renew</button>
    		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
    	</div>
	</div>
</div>
<style>
.modal-dialog{
	width: 75%;
}
</style>
