<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
	
		<h5 class="title-margin">Report: <?=$this->title?></h5>
	</div>
		<form method="get" id="filter" name="filter" action="">
		<table class="" width="100%">
			<tr style="font-size: 0.8em;">
				<th width="20%">Customer</th>
				<th width="10%">Expiry Month</th>
				<th width="15%">Type</th>
				<th width="15%" >Building</th>
				<th width="15%">Property</th>
				<th width="15%"></th>
			</tr>
			<tr>	
				<td>
					<div class="form-group ">
                	<?=$this->form->f_selCustomer->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group">
                	<?=$this->form->f_monthpick->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group">
                	<?=$this->form->f_type->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group">
                	<?=$this->form->f_building->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group">
                	<?=$this->form->f_property->show()?>
              		</div>
				</td>
				<td align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
		</form>
	</div>

<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php //include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
<?php include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
							<thead>
								<tr>
									<th width="1%" rowspan="4">
										<div class="title-margin">
											<img width="50" alt=""
												src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
												style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
										</div>
									</th>
								</tr>
								<tr>
									<th><div class="center" style="width: 79%;">ABDULLAH BIN SALEM TRADING EST.</div></th>
								</tr>
								<tr>
									<th width="">
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%; font-family: f11; font-size:9pt;">
											<b> مؤسسة عبدالله بن سالم للتجارة </b>
										</div>

									</th>
								</tr>
								<tr>
									<th>
										<div class="center"
											style="margin-top: 0px; margin-bottom: 10px; width: 79%;"><?=$this->title?></div>
									</th>
								</tr>
							</thead>
						</table>
					</div>
					<table class="rpt_frame">
			<thead>
				<tr>
					<td class="empty" colspan="5" style="border: 1px solid white;">
					</td>
					<td class="empty" style="border: 1px solid white;">
					<?php $date = new DateTime();$date = $date->format('d/m/Y')?>
					Date : <?=$date;?></td>
				</tr>
				<tr>
					<th class="empty" colspan="6"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="18%" class="center">Customer Name</th>
					<th width="5%" class="center">Date.</th>
					<th width="5%" class="center">File No.</th>
					<th width="22%" class="center">Particulares</th>
					<th width="12%" class="center">Amount Received</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->collList)>0):?>
				<?php foreach($this->collList as $coll):
				$encPayId = $this->encode($coll['coll_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$coll['cust_name']?> <?=$coll['cdmd_note'];?>
					</td>
					<td align="center"><?=$coll['coll_date']?></td>
					<td align="center"><?=$coll['coll_file_no']?></td>
					<td align="left"><?=$coll['bill_no']?> <?=$coll['cdmd_narr']?> </td>
					<td align="right">
					<?=x(array('link'=>'erp_invoice/collection/view','ref'=>$encPayId,'label'=>number_format($coll['coll_amount'],3),array("param"=>'class="facebox"')))?>
					
					<? $total+=$coll['coll_amount'];?></td>
				</tr>
				<?php endforeach?>
				<tr><td colspan="5" align="right"><b> Total:</b> </td>
					<td align="right"> <b><?=number_format($total,3)?></b></td>
				</tr>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</form>
</div>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
</script>
<style>
.modal-dialog{
	width: 95%;
}
</style>

