<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">Report: <?=$this->title?></h5>
	</div>
	<form method="get" id="filter" name="filter" action="">
	<?php if($ref==''):?>
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="12%">Property No</th>
				<th width="12%">Building</th>
				<th width="12%">Category</th>
				<th width="12%">Type</th>
				<th width="15%">Expiry Month</th>
				<th width="15%"></th>
			</tr>
			<tr>	
				<td>
					<div class="form-group ">
                	<?=$this->form->f_propno->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_building->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_prop_cat->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_prop_type->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group">
                	<?=$this->form->f_monthpick->show()?>
              		</div>
				</td>
				<td align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
		</form>
		<?php endif?>
	</div>

<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include_once __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
			<table class="rpt_tbl">
				<thead>
					<tr>
						<th width="1%" rowspan="3">
							<div class="title-margin">
								<img width="50" alt=""
									src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
									style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
							</div>
						</th>
					</tr>
					<tr>
						<th ><div class="center" style="width: 79%;">Abdullah
								Salem Trading Est</div></th>
					</tr>
					<tr>
						<th width=""><div class="center"
								style="margin-top: 0px; margin-bottom: 10px; width: 79%;"><?=$this->title;?></div></th>
					</tr>
				</thead>
			</table>
		</div>
		<table class="rpt_frame">
			<thead>
				<tr>
					<th class="empty" colspan="12"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="8%">File No</th>
					<th width="8%" class="center">Property No</th>
					<th width="12%" class="center">Building</th>
					<th width="5%" class="center">Category</th>
					<th width="5%" class="center">Type</th>
					<th width="15%" class="center">Agreement By</th>
					<th width="10%" class="center">Mobile no</th>
					<th width="6%" class="center">Doc No</th>
					<th width="6%" class="center">Issue Date</th>
					<th width="6%" class="center">Expiry Date</th>
					<th width="6%" class="center">Rent Amount</th>
				</tr>
			</thead>
			<tbody>
			
			<?if(count($this->propertyList)>0):?>
				<?php foreach($this->propertyList as $property):
					if ($ref!='') {
						if ($property ['doc_type'] == 3)
							$tpropPropList [$property ['prop_id']] = $property ['doc_type'];
						
						if ($property ['doc_type'] == 2) {
							if (isset ( $tpropPropList [$property ['prop_id']] ))
								continue;
						}
					}
				
				
				$encPropId = $this->encode($property['prop_id']);
				$encFileId = $this->encode($property['file_id']);
				//s($property);
				
				?>
				<?php if($grouph!=$property['doc_type']):?>
				<tr><td colspan="10"><b>&nbsp;&nbsp;<?=$this->docMst[$property['doc_type']]?></b></td></tr>
				<?php $sl = 1;?>
				<?php endif;?>
				<tr>
					<td class="center"><?=@$sl++;?></td>
					<td><?=x(array('link'=>'erp_projects/master/view','ref'=>$encPropId,'label'=>$property['prop_fileno']))?> </td>
					<td><?=$property['prop_no']?></td>
					<td><?=$property['bld_name']?></td>
					<td><? echo $property['prop_cat']==1?"Shop":"Flat";?></td>
					<td><?=$this->propType[$property['prop_type']]?></td>
					<td><?=$property['agr_tenant']?></td>
					<td align="center"><?=$property['agr_mobile']?></td>
					<td align="center"><?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>$property['doc_no'],array("param"=>'opener')))?>
					</td>
					<td><?=$property['doc_issue_date']?></td>
					<td><?=$property['doc_expiry_date']?></td>
					<td align="right"><?=$property['agr_amount']?></td>
				</tr>
				<?php $grouph=$property['doc_type'];?>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
				<tr><td>&nbsp;</td></tr>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y H:i')?>
						<td><div class="title-margin rpt_footer"><small><?=$this->title;?></small></div><div class="rpt_footer" style="float: right;"><small>(<?=$date?>)</small></div></td>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</div>
</form>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
</script>

