<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">Report: Projects Meter </h5>
	</div>
</div>
<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
				<thead>
					<tr>
						<th width="1%" rowspan="3">
							<div class="title-margin">
								<img width="50" alt=""
									src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
									style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
							</div>
						</th>
					</tr>
					<tr>
						<th ><div class="center" style="width: 79%;">Abdullah
								Salem Trading Est</div></th>
					</tr>
					<tr>
						<th width=""><div class="center"
								style="margin-top: 0px; margin-bottom: 10px; width: 79%;">Projects Meter Report</div></th>
					</tr>
				</thead>
			</table>
		</div>
		<table class="rpt_frame">
			<thead>
				<tr>
					<th class="empty" colspan="10"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="6%" class="center">File No</th>
					<th width="6%" class="center">Prop No</th>
					<th width="6%" class="center">Cat.</th>		
					<th width="6%" class="center">Level</th>		
					<th width="6%" class="center">Water Meter</th>								
					<th width="6%" class="center">Elc. Meter</th>
					<th width="6%" class="center">Ele. Account</th>
					<th width="10%" class="center">Ele. Recharge</th>
					<th width="8%" class="center">Status</th>
				</tr>
			</thead>
			<tbody>
			<? if(count($this->propertyList)>0):?>
				<?php foreach($this->propertyList as $property):
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$property['prop_fileno']?></td>
					<td><?=$property['prop_no']?></td>
					<td class="center"><? echo $property['prop_cat']==1?"Shop":
					($property['prop_building_type']==1?"Building":"Flat");?></td>
					<td><? echo $this->propLevel[$property['prop_level']]?></td>				
					<td><?=$property['prop_water']?></td>	
					<td><?=$property['prop_elec_meter']?></td>				
					<td><?=$property['prop_elec_account']?></td>
					<td><?=$property['prop_elec_recharge']?></td>
					<td><?=$property['property_status']?></td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>Projects Meter MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</div>
</form>
<script type="text/javascript">           
$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });
});
</script>

