<div style="margin-top:1%;">
	<div class="col-md-12 card filter-card" style="margin-bottom: 0px;">
	<div class="card-block" style="padding-top: 1%;">
	<div class="full-width">
		<button name="cmdPrint" value="  Print  " onclick="$('#report').printElement();" class="btn btn btn-primary pull-right" style="padding: 2px 12px;">Print</button></div>
		<h5 class="title-margin">Report: Employees</h5>
	</div>
	<form method="get" id="filter" name="filter" action="">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="15%">Company</th>
				<th width="15%">Department</th>
				<th width="15%">Designation</th>
				<th width="15%">Nationality</th>
				<th width="15%"></th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_company->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_dept->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_desig->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_natonality->show()?>
              		</div>
				</td>
				<td width="15%" align="center">
	              <div class="form-group ">
					<button class="btn <?= $this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
		</form>
	</div>
<div class="col-md-12 " style="height: 100%; padding-left: 1%; padding-right: 1%;">
<div id="report">
<?php include __DIR__ . '/../../../public/css/printstyle_rpt.php.css';?>
	<div  class="card" style="margin-top: 10px; padding-left: 5px; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
					<div style="margin-top: 3%;">
						<table class="rpt_tbl">
						<thead>
							<tr>
								<th width="1%" rowspan="3">
									<div class="title-margin">
										<img width="50" alt=""
											src="http://<?=$_SERVER ['HTTP_HOST']?>/css/images/ast.png"
											style="padding-top: 6px; padding-left: 0px; margin-left: 42px; margin-top: 5px;">
									</div>
								</th>
							</tr>
							<tr>
								<th ><div class="center" style="width: 79%;">Abdullah
										Salem Trading Est</div></th>
							</tr>
							<tr>
								<th width=""><div class="center"
										style="margin-top: 0px; margin-bottom: 10px; width: 79%;">Employee Report</div></th>
							</tr>
						</thead>
						</table>
					</div>
					<table class="rpt_frame">
			<thead>
				<tr>
					<th class="empty" colspan="10"></th>
				</tr>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="5%" class="center">File No</th>
					<th width="15%" class="center">Name</th>
					<th width="15%" class="center">Company</th>
					<th width="15%" class="center">Department</th>
					<th width="6%" class="center">Designation</th>
					<th width="10%" class="center">Nationality</th>
					<th width="10%" class="center">DOB</th>
					<th width="6%" class="center">DOJ</th>
					<th width="6%" class="center">Pay</th>
				</tr>
			</thead>
			<tbody>
			<?if(count( $this->employeeList)>0):?>
				<?php foreach( $this->employeeList as $employee):
				$encEmpId = $this->encode($employee['emp_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$employee['emp_fileno'];?></td>
					<td><?=$employee['emp_fname']?>&nbsp;<?=$employee['emp_mname']?>&nbsp;<?=$employee['emp_lname']?></td>
					<td><?=$employee['comp_disp_name']?></td>
					<td><?=$employee['dept_name']?></td>
					<td><?=$employee['desig_name']?></td>
					<td class="center"><?= $this->nation[$employee['emp_nationality']]?></td>
					<td><?=$employee['emp_dob']?></td>
					<td><?=$employee['emp_doj']?></td>
					<td align="right"><?=$employee['pay_total']?></td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format('d/m/y')?>
						<th><div class="title-margin rpt_footer"><h5>Employee MIS Report (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
</div>
</div>
<script type="text/javascript">                  
$(document).ready(function() {
	var source = '<?=APPURL?>'+ 'erp_employee/master/getlive';
	$('#f_company').on('change',function() {
		getJaxData($('#f_company').val(),'f_dept',source);
	});
	getJaxData($('#f_company').val(),'f_dept',source);
});
</script>

