<?$offset = $this->tenantsObj->_voffset;?>
<form method="get" id="filter" name="filter" action="list">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<!-- CONTAINER -->
			<div class="main-container container">
				<!-- PAGE-HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">List of Tenants</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Manage
								Tenants</li>
						</ol>
					</div>
					<div class="ms-auto pageheader-btn">
                        <?=x(array('link'=>'erp_property/tenants/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')),'<br><br>')?>
                        <a href="javascript:void(0);"
							class="btn btn-success btn-icon text-white"> <span> <i
								class="fe fe-log-in"></i>
						</span> Export
						</a>
					</div>
				</div>
				<!-- PAGE-HEADER END -->
				<!-- ROW -->
				<div class="row row-sm">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Filters</h3>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-3">
										<div class="form-group">
											<label for="file_no" class="form-label">Name</label>
                                            <?=$this->form->tnt_full_name->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label for="name" class="form-label">Phone No.</label>
                                            <?=$this->form->tnt_phone->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Mobile No.</label>
                                            <?=$this->form->tnt_tele->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Company</label>
                                            <?=$this->form->tnt_comp_name->show()?>
                                        </div>
									</div>
								</div>
								<button class="btn <?=$this->filter_class?> mt-4 mb-0"
									type="submit">Filter</button>
								<input class="btn btn-secondary mt-4 mb-0" name="clear"
									type="submit" value="All"></input>
							</div>
						</div>
					</div>
					<div class="">
						<div class="">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Properties</h3>
								</div>
								<div class="card-body">
									<div class="table-responsive export-table">
                                        <table aria-describedby="" class="table table-bordered no-footer">
                                                <thead class="border-top">
                                                  <tr role="row">
											<th width="5%" class="center">Sl No</th>
											<th width="20%" class="center">Tenants Name</th>
											<th width="20%" class="center">Company Name</th>
											<th width="12%" class="center">Tenant Type</th>
											<th width="12%" class="center">National/Expart</th>
											<th width="8%" class="center">Phone No.</th>
											<th width="8%" class="center">Mobile No.</th>
											<th width="8%" class="center">Id. No.</th>
											<th width="8%" class="center">CR. No.</th>
											<th width="5%" class="center">Edit</th>
											<th width="5%" class="center">View</th>
										</tr>
									</thead>
									<tbody>
                                        <?if(count($this->TenantsList)>0):?>
                                        <?php
                                            foreach ($this->TenantsList as $tenant) :
                                                $encTntId = $this->encode($tenant['tnt_id']);
                                                ?>
                                        <tr
											onclick="getContentX('<?=APPURL.'erp_property/tenants/'?>tenant_agr','<?=$encTntId;?>','tnt_target_<?=$tenant['tnt_id'];?>');"
											style="cursor: pointer;">
											<td class="center">
                                                <?=@++$offset;?>
                                            </td>
											<td>
                                                <?=$tenant['tnt_full_name']?>
                                            </td>
											<td>
                                                <?=$tenant['tnt_comp_name']?>
                                            </td>
											<td>
                                                <?=$tenant['tnt_expat']?>
                                            </td>
											<td>
                                                <?=$tenant['tnt_agr_type']?>
                                            </td>
											<td>
                                                <?=$tenant['tnt_phone']?>
                                            </td>
											<td>
                                                <?=$tenant['tnt_tele']?>
                                            </td>
											<td>
                                                <?=$tenant['tnt_id_no']?>
                                            </td>
											<td>
                                                <?=$tenant['tnt_crno']?>
                                            </td>
											<td class="center">
                                                <?=x(array('link'=>'erp_property/tenants/edit','ref'=>array('ref'=>$encTntId),'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>
                                            </td>
											<td class="center">
                                                <?=x(array('link'=>'erp_property/tenants/view','ref'=>array('ref'=>$encTntId),'label'=>'<i class="fas fa-search"></i>',array("param"=>'class="facebox"')))?>
                                            </td>
										</tr>
										<tr id='tnt_target_<?=$tenant['tnt_id'];?>'
											class="tnt_target"></tr>
                                        <?php endforeach?>
                                        <?endif?>
                                    </tbody>
								</table>
                                <?$this->tenantsObj->pagination();?>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>

			</div>
		</div>
	</div>




</form>
<script type="text/javascript">
function getContentX(postlink, refId, target) {
    $('.tnt_target').html('');
    getContent(postlink, refId, target);
}
</script>
<style>
.table-bordered, .text-wrap table, .table-bordered th, .text-wrap table th,
	.table-bordered td, .text-wrap table td {
	border: 1px solid #c6dcf9;
	border-bottom-width: 1px;
}

.table>:not(:last-child)>:last-child>* {
	border-bottom-color: #9fb3ce;
}
</style>