<td colspan="11">
	<div class="full-width" style="padding-top: 2px; border-bottom-width: 0px;padding-left: 50px;">
		<div class="col-md-13">
			<div id="accordion" class="panel-group">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title1">
							Lease Contract - 
						</h4>
					</div>
					<div class="panel-collapse" id="collapse2">
						<div class="panel-body">
	
							<table class="table table-bordered">
								<thead>
									<tr>
										<th width="10%"class="center">Agreement No.</th>
										<th width="12%"class="center">Rent Amount</th>
										<th width="10%"class="center">Start Date </th>
										<th width="10%"class="center">End Date</th>
										<th width="10%"class="center">Pay Schedule</th>
										<th width="10%"class="center">Payments</th>
										<th width="5%"class="center">Edit</th>
										<th width="5%"class="center">View</th>
										<th width="5%"class="center">Download</th>
										<th width="5%"class="center">Delete</th>
									</tr>
								</thead>
								<tbody>
								<?php foreach ($this->leaseDocs as $doc):
								$doi = DateTime::createFromFormat(DFS_DB,$doc['doc_issue_date']);
								$doi = $doi->format(DF_DD);
								$doe = DateTime::createFromFormat(DFS_DB,$doc['doc_expiry_date']);
								$doe = $doe->format(DF_DD);
								$encFileId = $this->encode($doc['file_id']);
								$encDocId1 = $this->encode($doc['doc_id']);
								?>
									<tr>
										<td><?=x(array('link'=>'erp_property/master/propdocsview','ref'=>$encDocId1,'label'=>$doc['doc_no'],array("param"=>'class="facebox"')))?></td>
										<td class="center"><?=$doc['agr_rent']?></td>
										<td class="center"><?=$doi?></td>
										<td class="center"><?=$doe?></td>
										<td align="center"> <?if(true):?><?=x(array('link'=>'erp_property/master/payoptions','ref'=>$encDocId1,'label'=>'<i style="font-size: 25px;" class="glyphicon glyphicon-usd text-info"></i>',array("param"=>'class="facebox"')))?><?endif?></td>
										<td class="center"><?php if($doc['to_collect']):?> <?=x(array('link'=>'erp_property/tenants/tenant_payments','ref'=>$encDocId1,'label'=>"<b>".$doc['collected']." / ".$doc['to_collect']."</b></td>",array("param"=>'class="facebox"')))?><?php endif;?></td>										
										<td class="center"> <?if(!$delete1Off):?><?=x(array('link'=>'erp_property/master/propdocsedit','ref'=>$encDocId1,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?><?endif?></td>
										<td class="center"> <?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>'<i class="fas fa-search"></i>',array("exten"=>$doc['file_exten'])))?></td>
										<td class="center"> <?=x(array('link'=>'default/default/download','ref'=>$encFileId,'label'=>'<i class="glyphicon glyphicon-download-alt text-info"></i>',array("param"=>'opener')))?></td>
										<td class="center">
										<?if(!$delete1Off):?>
											<?=x(array('link'=>'erp_property/master/propdocsdelete','ref'=>$encDocId1,'label'=>'<i class="glyphicon glyphicon-trash text-info"></i>',array("param"=>'class="facebox"')))?>
										<?endif?></td>
									</tr>
								<?php 
								$delete1Off = true;
								endforeach;?>
								</tbody>
							</table>
	
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</td>
