<div class="dynamic-popup" id="dynamic-popup">
	<!--  -->
	<form name="form" method="post" id="edit" action='erp_property/master/payoptions/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
		<div class="modal-header">
			<h4 class="card-title">Agreement Payment</h4>
			<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
				<span aria-hidden="true">×</span>
			</button>
		</div>
		<div class="modal-body">

				<div class="row mb-4" style="margin-top: 15px;">
				 <div id="mh_varis" class="col-sm-12">
                    <table width="100%" id="multi_table">
					<tr style="font-size: 0.8em;">
						<th width="15%" style="padding-bottom: 5px;">Rent Amount</th>
						<th width="20%" style="padding-bottom: 5px;">Demand Date</th>
						<th width="15%" style="padding-bottom: 5px;">Amount Paid</th>
					</tr>
					<?php foreach($this->tenPayment as $row):?>
					<tbody id="">
					<tr class="" index="<?=$i?>">
						<td align="center">
		                	<?=$row['popt_amount']?>
						</td>
						<td align="center">
		                	<?=$row['cdmd_date']?>
						</td>
						<td align="center">
		                	<?=$row['collected']?>
						</td>
					</tr>
					<?php endforeach;?>
					</tbody>
					</table>
                 </div>
                 </div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>

<script type="text/javascript">


</script>
