<div class="dynamic-popup" id="dynamic-popup">
	<form name="form" method="post" id="edit" action='erp_manage/calllog/edit/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
		<div class="modal-content modal-content-demo">
			<div class="modal-header">
				<h4 class="card-title">Add Call Log</h4>
				<button type="button" aria-label="Close" class="btn-close" data-bs-dismiss="modal">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body" style="margin-top:0px;">
				<div class="row g-3 mb-2">
					<div class="col-sm-6">
						<label class="form-label">Phone Number</label>
						<?=$this->form->phone_no->show()?>
					</div>
					<div class="col-sm-6">
						<label class="form-label">Name</label>
						<?=$this->form->name->show()?>
					</div>
				</div>
				<div class="row g-3 mb-2">
					<div class="col-sm-6">
						<label class="form-label">Email</label>
						<?=$this->form->email->show()?>
					</div>
					<div class="col-sm-6">
						<div class="row">
							<div class="col-6">
								<label class="form-label">Date</label>
								<?=$this->form->date->show()?>
							</div>
							<div class="col-6">
								<label class="form-label">Time</label>
								<?=$this->form->time->show()?>
							</div>
						</div>
					</div>
				</div>
				<div class="row g-3 mb-2">
					<div class="col-sm-6">
						<label class="form-label">Log Subject</label>
						<?=$this->form->logtype->show()?>
					</div>
					<div class="col-sm-6">
						<label class="form-label">Status</label>
						<?=$this->form->clog_sts_for->show()?>
					</div>
				</div>
				<div class="row g-3 mb-2">
					<div class="col-12">
						<label class="form-label">Summary</label>
						<?=$this->form->log->show()?>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary submit-alias livepost">Update Log</button>
				<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
			</div>
		</div>
	</form>
</div>

<style>
.modal-dialog {
	width: 65%;
}
</style>



<script>
$(document).ready(function($) {
    $('body').on('change', 'input.time', function() {
        const timePattern = /^([01]?[0-9]|2[0-3]):[0-5][0-9]$/; // Regex for valid HH:mm format
        const value = $(this).val().trim();

        if (!timePattern.test(value)) {
            // Clear the input if it doesn't match the time format
            $(this).val("");
        }
    });
});

document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('input').forEach(function (input) {
        input.addEventListener('focus', function () {
            this.setAttribute('autocomplete', 'new-' + Math.random().toString(36).substring(2));
        });
    });
});

</script>