<form method="get" id="filter" name="filter" action="list">
	<div class="main-content mt-0 hor-content">
		<div class="side-app">
			<!-- CONTAINER -->
			<div class="main-container container">
				<!-- PAGE-HEADER -->
				<div class="page-header">
					<div>
						<h1 class="page-title">Properties</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="javascript:void(0);">Home</a>
							</li>
							<li class="breadcrumb-item active" aria-current="page">Employees</li>
						</ol>
					</div>
					<div class="ms-auto pageheader-btn">
                        <?=x(array('link'=>'erp_property/master/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')),'<br><br>')?>
                        <?=x(array('link'=>'erp_masters/building/list','label'=>'<button class="btn btn-success pull-right" >Buildings</button>',''),'<br><br>')?>
                        <a href="javascript:void(0);"
							class="btn btn-success btn-icon text-white"> <span> <i
								class="fe fe-log-in"></i>
						</span> Export
						</a>
					</div>
				</div>
				<!-- PAGE-HEADER END -->
				<!-- ROW -->
				<div class="row row-sm">
					<div class="col-lg-12">
						<div class="card">
							<div class="card-header">
								<h3 class="card-title">Filters</h3>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-3">
										<div class="form-group">
											<label for="file_no" class="form-label">File.No</label>
                                            <?=$this->form->f_fileno->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label for="name" class="form-label">Prop No</label>
                                            <?=$this->form->f_propno->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Building</label>
                                            <?=$this->form->f_building->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Category</label>
                                            <?=$this->form->f_prop_cat->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Status</label>
                                            <?=$this->form->f_prop_status->show()?>
                                        </div>
									</div>
									<div class="col-lg-3">
										<div class="form-group">
											<label class="form-label"> Tenant</label>
                                            <?=$this->form->f_tenant->show()?>
                                        </div>
									</div>
								</div>
								<button class="btn <?=$this->filter_class?> mt-4 mb-0"
									type="submit">Filter</button>
								<input class="btn btn-secondary mt-4 mb-0" name="clear"
									type="submit" value="All"></input>
							</div>
						</div>
					</div>
					<div class="">
						<div class="">
							<div class="card">
								<div class="card-header">
									<h3 class="card-title">Employees</h3>
								</div>
								<div class="card-body">
									<div class="table-responsive export-table">
										<table id="file-datatable"
											class="table table-bordered text-nowrap key-buttons border-bottom w-100">
											<thead>
												<tr>
													<th width="5%" class="center">Sl No</th>
													<th width="5%" class="center">File No.</th>
													<th width="6%" class="center">Property No</th>
													<th width="10%" class="center">Building Name</th>
													<th width="7%" class="center">Category</th>
													<th width="15%" class="center">Tenant</th>
													<th width="7%" class="center">Level</th>
													<th width="10%" class="center">Status</th>
													<th width="5%" class="center">Rent</th>
													<th width="5%" class="center">Edit</th>
													<th width="5%" class="center">View</th>
													<!--<th width="6%" class="center">Delete</th>-->
												</tr>
											</thead>
											<tbody>
                                                <?if(count($this->propertyList)>0):?>
                                                <?php

                                                    foreach ($this->propertyList as $property) :
                                                        $encPropId = $this->encode($property['prop_id']);
                                                        ?>
                                                <tr>
													<td class="center">
                                                        <?=@++$this->offset;?>
                                                    </td>
													<td>
                                                        <?=$property['prop_fileno']?>
                                                    </td>
													<td>
                                                        <?=$property['prop_no']?>
                                                    </td>
													<td>
                                                        <?=$property['bld_name']?>
                                                    </td>
													<td class="center">
                                                        <?

                                                        echo $property['prop_cat'] == 1 ? "Shop" : ($property['prop_building_type'] == 1 ? "Building" : "Flat");
                                                        ?>
                                                    </td>
													<td>
                                                        <? if($property['prop_status']==2): ?>
                                                        <? echo $property['agr_tenant']?>
                                                        <?php endif?>
                                                    </td>
													<td>
                                                        <? echo $this->propLevel[$property['prop_level']]?>
                                                    </td>
													<td class="center" <? if($property['prop_status']==1): ?>
														style="color: red; font-weight: bold" <?php endif?>>
                                                        <?=$property['property_status']?>
                                                        <?php if($property['prop_building_type']==""):?>
                                                        <?=x(array('link'=>'erp_property/master/status','ref'=>$encPropId,'label'=>'<i class="fas fa-star-half-alt"></i>',array("param"=>'class="facebox"')))?>
                                                        <?php endif?>
                                                    </td>
													<td class="center">
                                                        <?=x(array('link'=>'erp_report/property/paymentcollection','ref'=>array('f_property'=>$property['prop_id']),'label'=>'<i class="fas fa-tasks"></i>',array("param"=>'wide_opener')))?>
                                                    </td>
													<td class="center">
                                                        <?=x(array('link'=>'erp_property/master/edit','ref'=>$encPropId,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>
                                                    </td>
													<td class="center">
                                                        <?=x(array('link'=>'erp_property/master/view','ref'=>$encPropId,'label'=>'<i class="fas fa-search"></i>'))?>
                                                    </td>
												</tr>
                                                <?php endforeach?>
                                                <?endif?>
                                            </tbody>
										</table>
                                        <?$this->propertyObj->pagination();?>
                                        <div class="row row-sm">
											<div class="col-lg-12">
                                                <?=x(array('link' => 'erp_report/property/property','label' => '
                                            		<div class="col-md-3">
                                            			<div class="card">
                                            					<div class="card-block">
                                            					<div class="card-block">
                                            						<h4 class="card-title center">Properties</h4>
                                            						<p class="card-text">
                                            							<small class="text-muted"></small>
                                            						</p>
                                            					</div>
                                            				</div>
                                            			</div>
                                            		</div>
                                            	',array("param" => 'wide_opener')), '<br><br>')?>
                                                                                            <?=x(array('link' => 'erp_report/property/propdocument','label' => '
                                            		<div class="col-md-3">
                                            			<div class="card">
                                            					<div class="card-block">
                                            					<div class="card-block">
                                            						<h4 class="card-title center">Prop Document</h4>
                                            						<p class="card-text">
                                            							<small class="text-muted"></small>
                                            						</p>
                                            					</div>
                                            				</div>
                                            			</div>
                                            		</div>
                                            	',array("param" => 'wide_opener')), '<br><br>')?>
                                                                                            <?=x(array('link' => 'erp_report/property/propdocument','ref' => array('ref' => 'exp'),'label' => '
                                            		<div class="col-md-3">
                                            			<div class="card">
                                            					<div class="card-block" style="background-color: ;">
                                            					<div class="card-block">
                                            						<h4 class="card-title center">Doc Expiry</h4>
                                            						<p class="card-text">
                                            							<small class="text-muted"></small>
                                            						</p>
                                            					</div>
                                            				</div>
                                            			</div>
                                            		</div>
                                            	',array("param" => 'wide_opener')), '<br><br>')?>
                                                                                            <?=x(array('link' => 'erp_property/rent/propertypay','label' => '
                                            		<div class="col-md-3">
                                            			<div class="card">
                                            					<div class="card-block" style="background-color: ;">
                                            					<div class="card-block">
                                            						<h4 class="card-title center">Rent Schedule</h4>
                                            						<p class="card-text">
                                            							<small class="text-muted"></small>
                                            						</p>
                                            					</div>
                                            				</div>
                                            			</div>
                                            		</div>
                                            	',array("param" => 'wide_opener')), '<br><br>')?>
                                                                                            <?=x(array('link' => 'erp_report/property/propvacant','label' => '
                                            	<div class="col-md-3">
                                            		<div class="card">
                                            				<div class="card-block" style="background-color: ;">
                                            				<div class="card-block">
                                            					<h4 class="card-title center">Property Status</h4>
                                            					<p class="card-text">
                                            						<small class="text-muted"></small>
                                            					</p>
                                            				</div>
                                            			</div>
                                            		</div>
                                            	</div>
                                            ',array("param" => 'wide_opener')), '<br><br>')?>
                                                                                            <?=x(array('link' => 'erp_report/property/propertymeter','label' => '
                                            	<div class="col-md-3">
                                            		<div class="card">
                                            				<div class="card-block" style="background-color: ;">
                                            				<div class="card-block">
                                            					<h4 class="card-title center">Property Meter</h4>
                                            					<p class="card-text">
                                            						<small class="text-muted"></small>
                                            					</p>
                                            				</div>
                                            			</div>
                                            		</div>
                                            	</div>
                                            ',array("param" => 'wide_opener')), '<br><br>')?>
                                                                                            <?=x(array('link' => 'erp_report/property/tenantagreements','label' => '
                                            	<div class="col-md-3">
                                            		<div class="card">
                                            				<div class="card-block" style="background-color: ;">
                                            				<div class="card-block">
                                            					<h4 class="card-title center">Tenant Agreements</h4>
                                            					<p class="card-text">
                                            						<small class="text-muted"></small>
                                            					</p>
                                            				</div>
                                            			</div>
                                            		</div>
                                            	</div>
                                            ',array("param" => 'wide_opener')), '<br><br>')?>
                                            </div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

</form>