<div id="report">
	<style type="text/css">
body {
	font-family: Roboto, "Helvetica Neue", Arial, Helvetica, sans-serif;
	margin: 0;
}

.card &gt ;.card-block &gt ;*:last-child, .card &gt ;*:last-child {
	margin-bottom: 0 !important;
}

.card {
	background-color: #fff;
	border-radius: 3px;
	margin-bottom: 30px;
	position: relative;
}

table {
	background-color: transparent;
}

table {
	border-collapse: collapse;
	border-spacing: 0;
}

table.rpt_tbl {
	width: 100%;
}

th {
	text-align: left;
}

td, th {
	padding: 0;
}

.center {
	text-align: center;
}

.title-margin {
	margin-top: -25px;
}

table.rpt_frame {
	margin-bottom: 20px;
	max-width: 100%;
	width: 100%;
}

table.rpt_frame tr {
	border: 1px solid #777;
}

table.rpt_frame th, .rpt_frame td {
	border: 1px solid #ababab;
	font-size: 14px;
	padding: 3px;
}

table.rpt_tbl {
	width: 100%;
}

.rpt_footer {
	margin-left: 6px;
	margin-top: -20px;
	padding-left: 0;
}

h5, .h5 {
	font-size: 14px;
}

h4, .h4, h5, .h5, h6, .h6 {
	margin-bottom: 10px;
	margin-top: 10px;
}

h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {
	color: inherit;
	font-family: inherit;
	font-weight: 500;
	line-height: 1.1;
}

@media print {
	table.rpt_frame   thead {
		display: table-header-group;
	}
	table.rpt_frame  thead th {
		border-top-style: solid;
		border-top-width: 2px;
	}
}

table.rpt_frame  thead th.empty {
	border-left: 1px solid white;
	border-right: 1px solid white;
	border-top: 1px solid white;
}

table.rpt_frame tr {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    border-color: #777 -moz-use-text-color;
    border-image: none;
    border-style: solid none;
    border-width: 1px medium;
}


table.rpt_frame th, .rpt_frame td {
    border: 1px none #ababab;
    font-size: 14px;
    padding: 3px;
}

</style>
	<div class="card"
		style="margin-top: 10px; padding-left: 2%; border-right-width: 1px; margin-right: 0px; padding-right: 5px;">
		<div style="margin-top: 1%;">
			<table class="rpt_tbl">
				<thead>
					<tr>
						<th><div class="center" style="float: right; width: 35%;">&nbsp;</div></th>
					</tr>
					<tr>
						<th><div class="center" style="float: right; width: 50%;"><i>File No: <?=$this->propertyDetail['prop_fileno']?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Prop No: <?=$this->propertyDetail['prop_no']?></i></div></th>
					</tr>
					<tr>
						<th><div class="center" style="float: right; width: 35%;">&nbsp;</div></th>
					</tr>
					<tr>
						<th width=""><div class="center"
								style="margin-top: 0px; margin-bottom: 10px; width: 79%;"><?=strtoupper($this->propertyDetail['prop_name'])?></div></th>
					</tr>
										<tr>
						<th width=""><div class="center"
								style="margin-top: 0px; margin-bottom: 10px; width: 79%;">&nbsp;</div></th>
					</tr>
				</thead>
			</table>
		</div>
		<table class="rpt_frame" style="max-width: 60%; float: left; margin-right: 2%;">
			<thead>
				<tr style="border-top: medium none;"> 
					<th width="35%">Property No</th>
					<th> <?=$this->propertyDetail['prop_no']?></th>
				</tr>
				<tr>
					<th>Property Building</th>
					<th><?=$this->propertyDetail['bld_name']?></th>
				</tr>
				<tr>
					<th>Property Name</th>
					<th><?=$this->propertyDetail['prop_name']?></th>
				</tr>
				<tr>
					<th>Category</th>
					<th><?=$vtcat[$this->propertyDetail['prop_cat']]?></th>
				</tr>
				<tr>
					<th>Type</th>
					<th><?=$propType[$this->propertyDetail['prop_type']]?></th>
				</tr>
				<tr>
					<th>Level</th>
					<th><?=$this->propLevel[$this->propertyDetail['prop_level']]?></th>
				</tr>
				<tr>
					<th>Elecricity No</th>
					<th>[<?=$this->propertyDetail['prop_elec_meter']?>]-[<?=$this->propertyDetail['prop_elec_account']?>]-[<?=$this->propertyDetail['prop_elec_recharge']?>]</th>
				</tr>
				<tr>
					<th>Water Meter No</th>
					<th><?=$this->propertyDetail['prop_water']?></th>
				</tr>
				<tr>
					<th>Remarks</th>
					<th><?=$this->propertyDetail['prop_remarks']?></th>
				</tr>
				<tr>
					<th>File No.</th>
					<th><?=$this->propertyDetail['prop_fileno']?></th>
				</tr>
			</thead>		
		</table>
		<div>
			<table class="" style="max-width: 35%; display: table; margin-left: 0px;">
				<thead>
					<tr>
						<th class="center"><div>
								
							</div></th>
					</tr>
				</thead>
			</table>
		</div>

		<div style="display: table; width: 95%;"><label><b>Agreement Details</b></label>
				<table class="rpt_frame">
					<thead>
						<tr>
							<th width="5%"class="center">Doc No.</th>
							<th width="10%"class="center">Agreement By</th>
							<th width="4%"class="center">Rent Amount</th>
							<th width="4%"class="center">Agreement Amount</th>
							<th width="15%"class="center">Payment Details</th>
							<th width="7%"class="center">Start Date </th>
							<th width="7%"class="center">End Date</th>
						</tr>
					</thead>
					<tbody>
					<?php foreach ($this->propDocs as $doc):
					$this->doi='';
					if($doc['doc_issue_date']){
						$this->doi = DateTime::createFromFormat(DFS_DB,$doc['doc_issue_date']);
						$this->doi = $this->doi->format(DF_DD);
					}
					$this->doe='';
					if($doc['doc_expiry_date']){
					$this->doe = DateTime::createFromFormat(DFS_DB,$doc['doc_expiry_date']);
					$this->doe = $this->doe->format(DF_DD);
					}
					$encFileId = $this->encode($doc['file_id']);
					$encDocId = $this->encode($doc['doc_id']);
					?>
						<tr>
							<th><?=$doc['doc_no']?></th>
							<th><?=$doc['agr_tenant']?></th>
							<th class="center"><?=$doc['agr_rent']?></th>
							<th class="center"><?=$doc['agr_amount']?></th>
							<th class="center"><?=$doc['agr_paydet']?></th>
							<th class="center"><?=$this->doi?></th>
							<th class="center"><?=$this->doe?></th>
						</tr>
					<?php endforeach;?>
					</tbody>
				</table>
				</div>
		<table class="rpt_frame" style="max-width: 30%; float: left; margin-right: 2%;">
			<thead>
				<tr style="border-top: medium none;"> 
					<th width="35%">Mobile</th>
					<th> <?=$doc['agr_mobile']?></th>
				</tr>
				<tr>
					<th>Telephone</th>
					<th><?=$doc['agr_tele']?></th>
				</tr>
				<tr>
					<th>ID/Passport No</th>
					<th><?=$doc['agr_idno']?></th>
				</tr>
				
				<tr>
					<th>Agreement Tenant Type</th>
					<th><?=($doc['agr_comp']==1?"Company":"Individual");?></th>
				</tr>
				
				<tr>
					<th>Citizenship</th>
					<th><?=($doc['agr_expat']==1?"National":"Expartiate");?></th>
				</tr>
				<tr>
					<th>CR No.</th>
					<th><?=$doc['agr_crno']?></th>
				</tr>
			</thead>		
		</table>
<?php 
require_once __DIR__ . '/../../admin/!model/proppayoption.php';
$payOptObj	= new proppayoption();
if($doc['doc_id'])
$payOptionDet = $payOptObj->getPayOptiosByDocAndProperty( array (
		'popt_prop_id' => $doc['doc_ref_id'],'popt_doc_id' => $doc['doc_id'],
) );
$options=array(1=>"Cash",2=>"Cheque","3"=>"--   --");
$bank = array('options'=>array('1'=>"Bank Muscat", '2'=>'Bank Dhofar',"3"=>"NBO","4"=>"OAB","5"=>"HSBC","6"=>"FAB",'7'=>'Bank Sohar','8'=>'SBI','9'=>'Bank of Baroda','10'=>'NBA','11'=>'Bank Nizwa'));
?>		
			
		<table class="rpt_frame" style="max-width: 59%; float: left; margin-right: 2%;margin-left: 3%;">
			<thead>
			<tr style="border-top: medium none;"> 
					<th colspan="5">Payment Schedule</th>
				</tr>
				<tr style="border-top: medium none;"> 
					<th width="12%"> Date</th>
					<th width="18%"> Mode</th>
					<th width="18%"> Amount</th>
					<th width="30%"> Bank</th>
					<th width="18%"> Cheque No</th>
				</tr>
				<?php foreach ($payOptionDet as $payDet):?>
				<tr style="border-top: medium none;"> 
					<th> <?=$payDet['pay_date']?></th>
					<th> <?=$options[$payDet['popt_type']]?></th>
					<th> <?=$payDet['popt_amount']?></th>
					<th> <?=$bank[$payDet['popt_bank']]?></th>
					<th> <?=$payDet['popt_chqno']?></th>
				</tr>
				<?php endforeach;?>
			</thead>		
		</table>		
		<div>
			<table class="rpt_tbl">
				<thead>
					<tr><?php $date = new DateTime();
					$date = $date->format("d/m/Y : h:i:sA")?>
						<th><div class="title-margin rpt_footer"><h5>Property Profile (<?=$date?>)</h5></div></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>