<?$offset = $this->itemObj->_voffset;?>
<div class="card-block" style="padding-top: 2%;">
	<div class="full-width">
		<?=x(array('link'=>'erp_masters/item/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')))?>
	</div>
	<h5 class="title-margin">List of Items</h5>
</div>
<form method="get" id="filter" name="filter" action="">
<div class="col-md-12 card filter-card">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="24%">Code</th>
				<th>Item Name</th>
				<th>Description</th>
				<th>Price</th>
			</tr>
			<tr>
				<td width="24%">
					<div class="form-group ">
                	<?=$this->form->f_code->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_name->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_remarks->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_price->show()?>
              		</div>
				</td>
				<td width="15%" align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
	</div>

<div class="col-md-12 list_table">
	<div class="card">
		<table class="table table-bordered grid">
			<thead>
				<tr>
					<th width="5%" class="center">Sl No</th>
					<th width="9%" class="center">Item Code</th>
					<th width="15%" class="center">Item Name</th>
					<th width="15%" class="center">Description</th>
					<th width="15%" class="center">Price</th>
					<th width="10%" class="center">Edit</th>
					<th width="6%" class="center">View</th>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->ItemsList)>0):?>
				<?php foreach($this->ItemsList as $item):
					$encItemId = $this->encode($item['item_id']);
				?>
				<tr>
					<td class="center"><?=@++$offset;?></td>
					<td><?=$item['item_code']?></td>
					<td><?=$item['item_name']?></td>
					<td><?=$item['item_remarks']?></td>
					<td><?=$item['item_price']?></td>
					<td class="center">
						<?=x(array('link'=>'erp_masters/item/edit','ref'=>array('ref'=>$encItemId),'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>  
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_masters/item/view','ref'=>array('ref'=>$encItemId),'label'=>'<i class="fas fa-search"></i>',array("param"=>'class="facebox"')))?> 
					</td>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?$this->itemObj->pagination();?>
	</div>
</div>
</form>
