<div class="dynamic-popup" id="dynamic-popup">
	<div class="modal-header">
		<button aria-label="Close" class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true">×</span></button>
		<h4 class="modal-title">Item Details</h4>
	</div>
	<div class="modal-body">
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Item Code</label>
					<div class="col-sm-6">
                     <?=$this->itemDetail['item_code']?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Item Name</label>
					<div class="col-sm-6">
                     <?=$this->itemDetail['item_name']?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Price</label>
					<div class="col-sm-6">
                    <?=$this->itemDetail['item_price']?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Remarks</label>
					<div class="col-sm-6">
                    <?=$this->itemDetail['item_remarks']?>
                  </div>
				</div>
				<div class="row mb-4">
					<label class="col-sm-3 form-label" >Unit</label>
					<div class="col-sm-6">
                    <?=$this->itemDetail['item_unit']?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function($) {
	$('.modal-dialog').css('width', '550px');
})
</script>
