<div class="dynamic-popup" id="dynamic-popup"><!--  -->
	<form name="form" method="post" id="edit" action='erp_invoice/bill/editenable/ref/<?=$this->param['ref']?>' style="margin-bottom: 0px;">
	<div class="modal-header">
		<button aria-label="Close" class="btn-close" data-bs-dismiss="modal"><span aria-hidden="true">×</span></button>
		<h4 class="modal-title">  Caution !! Enable Edit / Cancel Bill  &nbsp;<i class="glyphicon glyphicon-alert" style="color:red">............</i> 
		</h4>
	</div>
	<div class="modal-body">
			<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-3 form-label" >Status</label>
					<div class="col-sm-9">
                    <?=$this->form->eedit->show()?>
                  </div>
				</div>
				<div class="row mb-4" style="margin-top: 15px;">
					<label class="col-sm-3 form-label" >Note</label>
					<div class="col-sm-9">
                    <?=$this->form->note->show()?>
                  </div>
				</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary submit-alias livepost" >Update</button>
		<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
	</div>
</form>	
</div>