<div class="card-block" style="padding-top: 2%;">
	<div class="full-width">
		<?=x(array('link'=>'erp_invoice/bill/add','label'=>'<button class="btn btn-success pull-right" >Add</button>',array("param"=>'class="facebox"')),'<br><br>')?>
	</div>
	<h5 class="title-margin">List of invoices</h5>
	
	
</div>
<form method="get" id="filter" name="filter" action="list">
	<div class="col-md-12 card filter-card">
		<table class="">
			<tr style="font-size: 0.8em;">
				<th width="8%">Company</th>
				<th width="15%">Customer</th>
				<th width="8%">Bill No.</th>
				<th width="10%">Ref No</th>
			</tr>
			<tr>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_company->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_customer->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_billno->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
                	<?=$this->form->f_refno->show()?>
              		</div>
				</td>
			</tr>
			</table>
			<table class="">
			<tr style="font-size: 0.8em;">
				<th width="10%">Payment Type</th>
				<th width="8%">Month</th>
				<th width="9%">Item</th>
				<th width="9%">Location</th>
				<th width="10%"></th>
			</tr>
			<tr><td>
					<div class="form-group ">
                	<?=$this->form->f_paymode->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group">
                	<?=$this->form->f_monthpick->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group ">
						<?=$this->form->f_item->show()?>
              		</div>
				</td>
				<td>
					<div class="form-group">
                	<?=$this->form->f_location->show()?>
              		</div>
				</td>
				<td width="5%" align="center">
	              <div class="form-group ">
					<button class="btn <?=$this->filter_class?>" type="submit" >Filter</button>
					<input class="btn btn-secondary" name="clear" type="submit" value="All"></input>
	              </div>
				</td>
			</tr>
		</table>
	</div>

<div class="col-md-12">
	<div class="card">
		<table class="table table-bordered grid">
			<thead>
				<tr>
					<th width="2%" class="center">Sl.</th>
					<th width="2%" class="center">Bill No</th>
					<th width="2%" class="center">Date</th>
					<th width="3%" class="center">Review</th>
					<th width="2%" class="center">Location</th>
					<th width="14%" class="center">Customer</th>
					<th width="5%" class="center">Ref No</th>
					<th width="8%" class="center">Remarks</th>
					<th width="8%" class="center">Bill Month</th>
					<th width="2%" class="center">Status</th>
					<th width="3%" class="center">Bill Amount</th>
					<th width="3%" class="center">Credit</th>
					<th width="2%" class="center">Edit</th>
					<th width="4%" class="center">View</th>
					<?php if($_SESSION['user_acl']['erp_invoice/bill/approval']):?>
					<th width="2%" class="center">Approve</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
			<?if(count($this->billList)>0):
				$mode=array(1=>"Paid", 2=>'Credit',3=>'Return',4=>'Cancelled' );
				 foreach($this->billList as $bill):
					$encBillId = $this->encode($bill['bill_id']);
					$bill['bill_cancellation_status']==1?$trclass = 'class="strikeout"':$trclass='';
				?>
				<tr <?=$trclass;?>>
					<td class="center"><?=@++$this->offset;?></td>
					<td>
					<?=x(array('link'=>'erp_invoice/bill/miniview','ref'=>$encBillId,'label'=>$bill['bill_book_no']<>''?$bill['bill_book_no']." (AST/".sprintf("%04s", $bill['bill_id']).")": "AST/".sprintf("%04s", $bill['bill_id']),array("param"=>'class="facebox"')))?> </td>
					<td><?=$bill['bill_disp_date']?></td>
					<td><?=$bill['bill_review_date']?></td>
					<td><?=$bill['bill_location']?></td>
					<td><?=$bill['cust_name']?></td>
					<td><?=$bill['bill_refno']?></td>
					<td><?=$bill['bill_remarks']?></td>
					<td><?=$bill['bill_month']?></td>
					<td><?=$mode[$bill['bill_pstatus']]?></td>
					<td><?=number_format($bill['bill_total'],3)?></td>	
					<td><?=number_format($bill['bill_credit_amt'],3)?></td>						
					<td class="center">
						<?php if($bill['bill_app_status']==''):?>
							<?=x(array('link'=>'erp_invoice/bill/edit','ref'=>$encBillId,'label'=>'<i class="fas fa-edit"></i>',array("param"=>'class="facebox"')))?>
						<?php elseif($bill['bill_app_status']==1 && $bill['bill_cancellation_status'] <> 1 && $bill['cdet_bill_id']==""):?>
							<?=x(array('link'=>'erp_invoice/bill/editenable','ref'=>$encBillId,'label'=>'<i class="glyphicon glyphicon-retweet" style="color:red"></i>',array("param"=>'class="facebox"')))?>
						<?php endif?>
  
					</td>
					<td class="center">
						<?=x(array('link'=>'erp_invoice/bill/miniview','ref'=>$encBillId,'label'=>'<i class="fas fa-search"></i>',array("param"=>'class="facebox"')))?>
						<?=x(array('link'=>'erp_invoice/bill/view','ref'=>$encBillId,'label'=>'<i class="glyphicon glyphicon glyphicon-print text-info" style="margin-left: 2px;"></i>',array("param"=>'wide_opener')))?> 
					</td>
					<?php if($_SESSION['user_acl']['erp_invoice/bill/approval']):?>
					<td class="center">
						<?php if($bill['bill_app_status']==''):?>
							<?=x(array('link'=>'erp_invoice/bill/approval','ref'=>$encBillId,'label'=>'<span class="glyphicon glyphicon-ok-circle" style="color:#31708f;font-size: 1.2em;"> </span>',array("param"=>'class="facebox"')))?>
						<?php endif?>
					</td>
					<?php endif;?>
				</tr>
				<?php endforeach?>
			<?endif?>
			</tbody>
		</table>
		<?$this->billObj->pagination();?>
		
		<?=x(array('link'=>'erp_masters/customer/add','label'=>'<button class="btn btn-success pull-right" style="padding: 4px 10px;">+Customer</button>',array("param"=>'class="facebox"')))?>
		<?=x(array('link'=>'erp_masters/item/add','label'=>'<button class="btn btn-success pull-right" style="padding: 4px 10px; margin-right: 5px;">+Item</button>',array("param"=>'class="facebox"')))?>
		
	</div>
</div>
</form>


<?=x(array('link'=>'erp_report/invoice/billbycustomer','label'=>'
	<div class="col-md-3">
		<div class="card">
				<div class="card-block" style="background-color: ;">
				<div class="card-block">
					<h4 class="card-title center">Outstanding Summary</h4>
					<p class="card-text">
						<small class="text-muted"></small>
					</p>
				</div>
			</div>
		</div>
	</div>
', array("param"=>'wide_opener')),'<br><br>')?>

<?=x(array('link'=>'erp_report/invoice/billoutstanding','label'=>'
	<div class="col-md-3">
		<div class="card">
				<div class="card-block" style="background-color: ;">
				<div class="card-block">
					<h4 class="card-title center">Outstanding In Detail</h4>
					<p class="card-text">
						<small class="text-muted"></small>
					</p>
				</div>
			</div>
		</div>
	</div>
', array("param"=>'wide_opener')),'<br><br>')?>

<?=x(array('link'=>'erp_report/invoice/billlisting','label'=>'
	<div class="col-md-3">
		<div class="card">
				<div class="card-block" style="background-color: ;">
				<div class="card-block">
					<h4 class="card-title center">Bill Listing</h4>
					<p class="card-text">
						<small class="text-muted"></small>
					</p>
				</div>
			</div>
		</div>
	</div>
', array("param"=>'wide_opener')),'<br><br>')?>


<script type="text/javascript"> 

function doSearch(text, backgroundColor) {
    if (window.find && window.getSelection) {
        document.designMode = "on";
        var sel = window.getSelection();
        sel.collapse(document.body, 0);

        while (window.find(text)) {
            document.execCommand("HiliteColor", false, backgroundColor);
            sel.collapseToEnd();
        }
        document.designMode = "off";
    }
}


$(document).ready(function() {
    $('#f_monthpick').MonthPicker({ Button: false });

doSearch('<?= @$this->valid['f_refno']; ?>','yellow');

jQuery(document).keyup(function(e){
    if(e.keyCode==27){
     return false;
    }
});



});
</script>
